package generations.gg.generations.core.generationscore.common.world.item

object MailTypes {
    @JvmField val AIR = MailType("air")
    @JvmField val BLOOM = MailType("bloom")
    @JvmField val BRICK = MailType("brick")
    @JvmField val BRIDGE_D = MailType("bridge_d")
    @JvmField val BRIDGE_M = MailType("bridge_m")
    @JvmField val BRIDGE_S = MailType("bridge_s")
    @JvmField val BRIDGE_T = MailType("bridge_t")
    @JvmField val BRIDGE_V = MailType("bridge_v")
    @JvmField val BUBBLE = MailType("bubble")
    @JvmField val DREAM = MailType("dream")
    @JvmField val FAB = MailType("fab")
    @JvmField val FAVORED = MailType("favored")
    @JvmField val FLAME = MailType("flame")
    @JvmField val GLITTER = MailType("glitter")
    @JvmField val GRASS = MailType("grass")
    @JvmField val GREET = MailType("greet")
    @JvmField val HARBOR = MailType("harbor")
    @JvmField val HEART = MailType("heart")
    @JvmField val INQUIRY = MailType("inquiry")
    @JvmField val LIKE = MailType("like")
    @JvmField val MECH = MailType("mech")
    @JvmField val MOSAIC = MailType("mosaic")
    @JvmField val ORANGE = MailType("orange")
    @JvmField val REPLY = MailType("reply")
    @JvmField val RETRO = MailType("retro")
    @JvmField val RSVP = MailType("rsvp")
    @JvmField val SHADOW = MailType("shadow")
    @JvmField val SNOW = MailType("snow")
    @JvmField val SPACE = MailType("space")
    @JvmField val STEEL = MailType("steel")
    @JvmField val THANKS = MailType("thanks")
    @JvmField val TROPIC = MailType("tropic")
    @JvmField val TUNNEL = MailType("tunnel")
    @JvmField val WAVE = MailType("wave")
    @JvmField val WOOD = MailType("wood")
}
