package generations.gg.generations.core.generationscore.common.world.level.block

import generations.gg.generations.core.generationscore.common.GenerationsCore
import generations.gg.generations.core.generationscore.common.util.GenerationsUtils.registerBlock
import generations.gg.generations.core.generationscore.common.world.item.GenerationsItems
import generations.gg.generations.core.generationscore.common.world.level.block.decorations.PokeDollBlock
import net.minecraft.core.Holder
import net.minecraft.world.item.Item
import net.minecraft.world.level.block.Block

@Suppress("unused")
object GenerationsPokeDolls: BlockPlatformRegistry() {
    /**
     * Pokedolls
     */
    val ARCEUS_POKEDOLL = registerBlockItem("arceus", false)
    val ARTICUNO_POKEDOLL = registerBlockItem("articuno", false)
    val AZELF_POKEDOLL = registerBlockItem("azelf", false)
    val AZURILL_POKEDOLL = registerBlockItem("azurill", false)
    val BALTOY_POKEDOLL = registerBlockItem("baltoy", false)
    val BLASTOISE_POKEDOLL = registerBlockItem("blastoise", false)
    val BLUEGHOST_POKEDOLL = registerBlockItem("blueghost", false)
    val CELEBI_POKEDOLL = registerBlockItem("celebi", false, 0.15f)
    val CHARIZARD_POKEDOLL = registerBlockItem("charizard", false)
    val CHIKORITA_POKEDOLL = registerBlockItem("chikorita", false)
    val CLEFAIRY_POKEDOLL = registerBlockItem("clefairy", false)
    val CRESSELIA_POKEDOLL = registerBlockItem("cresselia", false)
    val CUBONE_POKEDOLL = registerBlockItem("cubone", false)
    val CYNDAQUIL_POKEDOLL = registerBlockItem("cyndaquil", false)
    val DARKRAI_POKEDOLL = registerBlockItem("darkrai", false)
    val DEOXYS_POKEDOLL = registerBlockItem("deoxys", false)
    val DIALGA_POKEDOLL = registerBlockItem("dialga", false)
    val DITTO_POKEDOLL = registerBlockItem("ditto", false)
    val DUSKULL_POKEDOLL = registerBlockItem("duskull", false)
    val EEVEE_POKEDOLL = registerBlockItem("eevee", false)
    val EKANS_POKEDOLL = registerBlockItem("ekans", false)
    val ENTEI_POKEDOLL = registerBlockItem("entei", false)
    val GIRATINA_ALTERED_POKEDOLL = registerBlockItem("giratina_altered", false)
    val GIRATINA_ORIGINAL_POKEDOLL = registerBlockItem("giratina_origin", false)
    val GROUDON_POKEDOLL = registerBlockItem("groudon", false)
    val GULPIN_POKEDOLL = registerBlockItem("gulpin", false)
    val HERACROSS_POKEDOLL = registerBlockItem("heracross", false)
    val HOOH_POKEDOLL = registerBlockItem("hooh", false)
    val JIGGLYPUFF_POKEDOLL = registerBlockItem("jigglypuff", false)
    val JIRACHI_POKEDOLL = registerBlockItem("jirachi", false)
    val KECLEON_POKEDOLL = registerBlockItem("kecleon", false)
    val KRABBY_POKEDOLL = registerBlockItem("krabby", false, 0.2f)
    val KYOGRE_POKEDOLL = registerBlockItem("kyogre", false)
    val LAPRAS_POKEDOLL = registerBlockItem("lapras", false)
    val LATIAS_POKEDOLL = registerBlockItem("latias", false)
    val LATIOS_POKEDOLL = registerBlockItem("latios", false)
    val LITTEN_POKEDOLL = registerBlockItem("litten", false)
    val LOTAD_POKEDOLL = registerBlockItem("lotad", false)
    val LUGIA_POKEDOLL = registerBlockItem("lugia", false)
    val MANAPHY_POKEDOLL = registerBlockItem("manaphy", false)
    val MARILL_POKEDOLL = registerBlockItem("marill", false)
    val MEOWTH_POKEDOLL = registerBlockItem("meowth", false)
    val MESPRIT_POKEDOLL = registerBlockItem("mesprit", false)
    val MEW_POKEDOLL = registerBlockItem("mew", false)
    val MEWTWO_POKEDOLL = registerBlockItem("mewtwo", false)
    val MOLTRES_POKEDOLL = registerBlockItem("moltres", false)
    val MUDKIP_POKEDOLL = registerBlockItem("mudkip", false)
    val PALKIA_POKEDOLL = registerBlockItem("palkia", false)
    val PICHU_POKEDOLL = registerBlockItem("pichu", false)
    val PIKACHU_POKEDOLL = registerBlockItem("pikachu", false)
    val POPPLIO_POKEDOLL = registerBlockItem("popplio", false)
    val POLIWHIRL_POKEDOLL = registerBlockItem("poliwhirl", false)
    val PURPLEGHOST_POKEDOLL = registerBlockItem("purpleghost", false)
    val RAIKOU_POKEDOLL = registerBlockItem("raikou", false)
    val RAYQUAZA_POKEDOLL = registerBlockItem("rayquaza", false)
    val REGICE_POKEDOLL = registerBlockItem("regice", false)
    val REGIGIGAS_POKEDOLL = registerBlockItem("regigigas", false)
    val REGIROCK_POKEDOLL = registerBlockItem("regirock", false)
    val REGISTEEL_POKEDOLL = registerBlockItem("registeel", false)
    val RHYDON_POKEDOLL = registerBlockItem("rhydon", false)
    val ROWLET_POKEDOLL = registerBlockItem("rowlet", false)
    val SABLEYE_POKEDOLL = registerBlockItem("sableye", false)
    val SEEDOT_POKEDOLL = registerBlockItem("seedot", false)
    val SHAYMIN_LAND_POKEDOLL = registerBlockItem("shaymin_land", false)
    val SHAYMIN_SKY_POKEDOLL = registerBlockItem("shaymin_sky", false)
    val SKITTY_POKEDOLL = registerBlockItem("skitty", false)
    val SMOOCHUM_POKEDOLL = registerBlockItem("smoochum", false)
    val SNORLAX_POKEDOLL = registerBlockItem("snorlax", false)
    val SUBSTITUTE_POKEDOLL = registerBlockItem("substitute", false)
    val SUICUNE_POKEDOLL = registerBlockItem("suicune", false)
    val SWABLU_POKEDOLL = registerBlockItem("swablu", false)
    val TOGEPI_POKEDOLL = registerBlockItem("togepi", false)
    val TORCHIC_POKEDOLL = registerBlockItem("torchic", false)
    val TOTODILE_POKEDOLL = registerBlockItem("totodile", false)
    val TREECKO_POKEDOLL = registerBlockItem("treecko", false)
    val UXIE_POKEDOLL = registerBlockItem("uxie", false)
    val VENUSAUR_POKEDOLL = registerBlockItem("venusaur", false)
    val WAILMER_POKEDOLL = registerBlockItem("wailmer", false)
    val WYNAUT_POKEDOLL = registerBlockItem("wynaut", false)
    val ZAPDOS_POKEDOLL = registerBlockItem("zapdos", false)
    val ZERAORA_POKEDOLL = registerBlockItem("zeraora", false)

    /**
     * Pokedolls Shiny
     */
    val SHINY_ARCEUS_POKEDOLL = registerBlockItem("arceus", true)
    val SHINY_ARTICUNO_POKEDOLL = registerBlockItem("articuno", true)
    val SHINY_AZELF_POKEDOLL = registerBlockItem("azelf", true)
    val SHINY_AZURILL_POKEDOLL = registerBlockItem("azurill", true)
    val SHINY_BALTOY_POKEDOLL = registerBlockItem("baltoy", true)
    val SHINY_BLASTOISE_POKEDOLL = registerBlockItem("blastoise", true)
    val SHINY_CELEBI_POKEDOLL = registerBlockItem("celebi", true, 0.15f)
    val SHINY_CHARIZARD_POKEDOLL = registerBlockItem("charizard", true)
    val SHINY_CHIKORITA_POKEDOLL = registerBlockItem("chikorita", true)
    val SHINY_CLEFAIRY_POKEDOLL = registerBlockItem("clefairy", true)
    val SHINY_CRESSELIA_POKEDOLL = registerBlockItem("cresselia", true)
    val SHINY_CUBONE_POKEDOLL = registerBlockItem("cubone", true)
    val SHINY_CYNDAQUIL_POKEDOLL = registerBlockItem("cyndaquil", true)
    val SHINY_DARKRAI_POKEDOLL = registerBlockItem("darkrai", true)
    val SHINY_DEOXYS_POKEDOLL = registerBlockItem("deoxys", true)
    val SHINY_DIALGA_POKEDOLL = registerBlockItem("dialga", true)
    val SHINY_DITTO_POKEDOLL = registerBlockItem("ditto", true)
    val SHINY_DUSKULL_POKEDOLL = registerBlockItem("duskull", true)
    val SHINY_EEVEE_POKEDOLL = registerBlockItem("eevee", true)
    val SHINY_EKANS_POKEDOLL = registerBlockItem("ekans", true)
    val SHINY_ENTEI_POKEDOLL = registerBlockItem("entei", true)
    val SHINY_GIRATINA_ALTERED_POKEDOLL = registerBlockItem("giratina_altered", true)
    val SHINY_GIRATINA_ORIGIN_POKEDOLL = registerBlockItem("giratina_origin", true)
    val SHINY_GROUDON_POKEDOLL = registerBlockItem("groudon", true)
    val SHINY_GULPIN_POKEDOLL = registerBlockItem("gulpin", true)
    val SHINY_HERACROSS_POKEDOLL = registerBlockItem("heracross", true)
    val SHINY_HOOH_POKEDOLL = registerBlockItem("hooh", true)
    val SHINY_JIGGLYPUFF_POKEDOLL = registerBlockItem("jigglypuff", true)
    val SHINY_JIRACHI_POKEDOLL = registerBlockItem("jirachi", true)
    val SHINY_KECLEON_POKEDOLL = registerBlockItem("kecleon", true)
    val SHINY_KRABBY_POKEDOLL = registerBlockItem("krabby", true, 0.2f)
    val SHINY_KYOGRE_POKEDOLL = registerBlockItem("kyogre", true)
    val SHINY_LAPRAS_POKEDOLL = registerBlockItem("lapras", true)
    val SHINY_LATIAS_POKEDOLL = registerBlockItem("latias", true)
    val SHINY_LATIOS_POKEDOLL = registerBlockItem("latios", true)
    val SHINY_LITTEN_POKEDOLL = registerBlockItem("litten", true)
    val SHINY_LOTAD_POKEDOLL = registerBlockItem("lotad", true)
    val SHINY_LUGIA_POKEDOLL = registerBlockItem("lugia", true)
    val SHINY_MANAPHY_POKEDOLL = registerBlockItem("manaphy", true)
    val SHINY_MARILL_POKEDOLL = registerBlockItem("marill", true)
    val SHINY_MEOWTH_POKEDOLL = registerBlockItem("meowth", true)
    val SHINY_MESPRIT_POKEDOLL = registerBlockItem("mesprit", true)
    val SHINY_MEW_POKEDOLL = registerBlockItem("mew", true)
    val SHINY_MEWTWO_POKEDOLL = registerBlockItem("mewtwo", true)
    val SHINY_MOLTRES_POKEDOLL = registerBlockItem("moltres", true)
    val SHINY_MUDKIP_POKEDOLL = registerBlockItem("mudkip", true)
    val SHINY_PALKIA_POKEDOLL = registerBlockItem("palkia", true)
    val SHINY_PICHU_POKEDOLL = registerBlockItem("pichu", true)
    val SHINY_PIKACHU_POKEDOLL = registerBlockItem("pikachu", true)
    val SHINY_POPPLIO_POKEDOLL = registerBlockItem("popplio", true)
    val SHINY_POLIWHIRL_POKEDOLL = registerBlockItem("poliwhirl", true)
    val SHINY_RAIKOU_POKEDOLL = registerBlockItem("raikou", true)
    val SHINY_RAYQUAZA_POKEDOLL = registerBlockItem("rayquaza", true)
    val SHINY_REGICE_POKEDOLL = registerBlockItem("regice", true)
    val SHINY_REGIGIGAS_POKEDOLL = registerBlockItem("regigigas", true)
    val SHINY_REGIROCK_POKEDOLL = registerBlockItem("regirock", true)
    val SHINY_REGISTEEL_POKEDOLL = registerBlockItem("registeel", true)
    val SHINY_ROWLET_POKEDOLL = registerBlockItem("rowlet", true)
    val SHINY_SABLEYE_POKEDOLL = registerBlockItem("sableye", true)
    val SHINY_SEEDOT_POKEDOLL = registerBlockItem("seedot", true)
    val SHINY_RHYDON_POKEDOLL = registerBlockItem("rhydon", true)
    val SHINY_SHAYMIN_LAND_POKEDOLL = registerBlockItem("shaymin_land", true)
    val SHINY_SHAYMIN_SKY_POKEDOLL = registerBlockItem("shaymin_sky", true)
    val SHINY_SKITTY_POKEDOLL = registerBlockItem("skitty", true)
    val SHINY_SMOOCHUM_POKEDOLL = registerBlockItem("smoochum", true)
    val SHINY_SNORLAX_POKEDOLL = registerBlockItem("snorlax", true)
    val SHINY_SUBSTITUTE_POKEDOLL = registerBlockItem("substitute", true)
    val SHINY_SUICUNE_POKEDOLL = registerBlockItem("suicune", true)
    val SHINY_SWABLU_POKEDOLL = registerBlockItem("swablu", true)
    val SHINY_TOGEPI_POKEDOLL = registerBlockItem("togepi", true)
    val SHINY_TORCHIC_POKEDOLL = registerBlockItem("torchic", true)
    val SHINY_TOTODILE_POKEDOLL = registerBlockItem("totodile", true)
    val SHINY_TREECKO_POKEDOLL = registerBlockItem("treecko", true)
    val SHINY_UXIE_POKEDOLL = registerBlockItem("uxie", true)
    val SHINY_VENUSAUR_POKEDOLL = registerBlockItem("venusaur", true)
    val SHINY_WAILMER_POKEDOLL = registerBlockItem("wailmer", true)
    val SHINY_WYNAUT_POKEDOLL = registerBlockItem("wynaut", true)
    val SHINY_ZERAORA_POKEDOLL = registerBlockItem("zeraora", true)
    val SHINY_ZAPDOS_POKEDOLL = registerBlockItem("zapdos", true)


    private fun registerBlockItem(name: String, shiny: Boolean, scale: Float = 1.0f): Holder<Block> {
        val block = registerBlock<Block>(this, (if (shiny) "shiny_" else "") + name + "_doll", { PokeDollBlock(name, shiny, scale) })
        GenerationsItems.ITEMS.create(((if (shiny) "shiny_" else "") + name + "_doll"), { GenerationsBlockItem(block, Item.Properties()) })
        return block
    }

    override fun init() {
        GenerationsCore.LOGGER.info("Registering Generations PokeDolls")
        super.init()
    }
}
