package generations.gg.generations.core.generationscore.common.world.level.block

import dev.architectury.registry.registries.DeferredRegister
import dev.architectury.registry.registries.RegistrySupplier
import generations.gg.generations.core.generationscore.common.GenerationsCore
import generations.gg.generations.core.generationscore.common.util.GenerationsUtils.registerBlock
import generations.gg.generations.core.generationscore.common.world.item.GenerationsItems
import generations.gg.generations.core.generationscore.common.world.level.block.decorations.PokeDollBlock
import net.minecraft.core.registries.Registries
import net.minecraft.world.item.BlockItem
import net.minecraft.world.item.Item
import net.minecraft.world.level.block.Block

@Suppress("unused")
object GenerationsPokeDolls {
    val POKEDOLLS: DeferredRegister<Block> = DeferredRegister.create(GenerationsCore.MOD_ID, Registries.BLOCK)

    /**
     * Pokedolls
     */
    val ARCEUS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("arceus", false)
    val ARTICUNO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("articuno", false)
    val AZELF_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("azelf", false)
    val AZURILL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("azurill", false)
    val BALTOY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("baltoy", false)
    val BLASTOISE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("blastoise", false)
    val BLUEGHOST_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("blueghost", false)
    val CELEBI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("celebi", false, 0.15f)
    val CHARIZARD_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("charizard", false)
    val CHIKORITA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("chikorita", false)
    val CLEFAIRY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("clefairy", false)
    val CRESSELIA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("cresselia", false)
    val CUBONE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("cubone", false)
    val CYNDAQUIL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("cyndaquil", false)
    val DARKRAI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("darkrai", false)
    val DEOXYS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("deoxys", false)
    val DIALGA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("dialga", false)
    val DITTO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("ditto", false)
    val DUSKULL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("duskull", false)
    val EEVEE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("eevee", false)
    val EKANS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("ekans", false)
    val ENTEI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("entei", false)
    val GIRATINA_ALTERED_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("giratina_altered", false)
    val GIRATINA_ORIGINAL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("giratina_origin", false)
    val GROUDON_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("groudon", false)
    val GULPIN_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("gulpin", false)
    val HERACROSS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("heracross", false)
    val HOOH_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("hooh", false)
    val JIGGLYPUFF_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("jigglypuff", false)
    val JIRACHI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("jirachi", false)
    val KECLEON_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("kecleon", false)
    val KRABBY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("krabby", false, 0.2f)
    val KYOGRE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("kyogre", false)
    val LAPRAS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("lapras", false)
    val LATIAS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("latias", false)
    val LATIOS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("latios", false)
    val LITTEN_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("litten", false)
    val LOTAD_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("lotad", false)
    val LUGIA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("lugia", false)
    val MANAPHY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("manaphy", false)
    val MARILL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("marill", false)
    val MEOWTH_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("meowth", false)
    val MESPRIT_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mesprit", false)
    val MEW_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mew", false)
    val MEWTWO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mewtwo", false)
    val MOLTRES_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("moltres", false)
    val MUDKIP_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mudkip", false)
    val PALKIA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("palkia", false)
    val PICHU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("pichu", false)
    val PIKACHU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("pikachu", false)
    val POPPLIO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("popplio", false)
    val POLIWHIRL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("poliwhirl", false)
    val PURPLEGHOST_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("purpleghost", false)
    val RAIKOU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("raikou", false)
    val RAYQUAZA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("rayquaza", false)
    val REGICE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("regice", false)
    val REGIGIGAS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("regigigas", false)
    val REGIROCK_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("regirock", false)
    val REGISTEEL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("registeel", false)
    val RHYDON_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("rhydon", false)
    val ROWLET_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("rowlet", false)
    val SABLEYE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("sableye", false)
    val SEEDOT_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("seedot", false)
    val SHAYMIN_LAND_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("shaymin_land", false)
    val SHAYMIN_SKY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("shaymin_sky", false)
    val SKITTY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("skitty", false)
    val SMOOCHUM_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("smoochum", false)
    val SNORLAX_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("snorlax", false)
    val SUBSTITUTE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("substitute", false)
    val SUICUNE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("suicune", false)
    val SWABLU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("swablu", false)
    val TOGEPI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("togepi", false)
    val TORCHIC_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("torchic", false)
    val TOTODILE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("totodile", false)
    val TREECKO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("treecko", false)
    val UXIE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("uxie", false)
    val VENUSAUR_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("venusaur", false)
    val WAILMER_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("wailmer", false)
    val WYNAUT_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("wynaut", false)
    val ZAPDOS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("zapdos", false)
    val ZERAORA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("zeraora", false)

    /**
     * Pokedolls Shiny
     */
    val SHINY_ARCEUS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("arceus", true)
    val SHINY_ARTICUNO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("articuno", true)
    val SHINY_AZELF_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("azelf", true)
    val SHINY_AZURILL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("azurill", true)
    val SHINY_BALTOY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("baltoy", true)
    val SHINY_BLASTOISE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("blastoise", true)
    val SHINY_CELEBI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("celebi", true, 0.15f)
    val SHINY_CHARIZARD_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("charizard", true)
    val SHINY_CHIKORITA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("chikorita", true)
    val SHINY_CLEFAIRY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("clefairy", true)
    val SHINY_CRESSELIA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("cresselia", true)
    val SHINY_CUBONE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("cubone", true)
    val SHINY_CYNDAQUIL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("cyndaquil", true)
    val SHINY_DARKRAI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("darkrai", true)
    val SHINY_DEOXYS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("deoxys", true)
    val SHINY_DIALGA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("dialga", true)
    val SHINY_DITTO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("ditto", true)
    val SHINY_DUSKULL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("duskull", true)
    val SHINY_EEVEE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("eevee", true)
    val SHINY_EKANS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("ekans", true)
    val SHINY_ENTEI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("entei", true)
    val SHINY_GIRATINA_ALTERED_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("giratina_altered", true)
    val SHINY_GIRATINA_ORIGIN_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("giratina_origin", true)
    val SHINY_GROUDON_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("groudon", true)
    val SHINY_GULPIN_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("gulpin", true)
    val SHINY_HERACROSS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("heracross", true)
    val SHINY_HOOH_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("hooh", true)
    val SHINY_JIGGLYPUFF_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("jigglypuff", true)
    val SHINY_JIRACHI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("jirachi", true)
    val SHINY_KECLEON_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("kecleon", true)
    val SHINY_KRABBY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("krabby", true, 0.2f)
    val SHINY_KYOGRE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("kyogre", true)
    val SHINY_LAPRAS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("lapras", true)
    val SHINY_LATIAS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("latias", true)
    val SHINY_LATIOS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("latios", true)
    val SHINY_LITTEN_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("litten", true)
    val SHINY_LOTAD_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("lotad", true)
    val SHINY_LUGIA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("lugia", true)
    val SHINY_MANAPHY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("manaphy", true)
    val SHINY_MARILL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("marill", true)
    val SHINY_MEOWTH_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("meowth", true)
    val SHINY_MESPRIT_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mesprit", true)
    val SHINY_MEW_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mew", true)
    val SHINY_MEWTWO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mewtwo", true)
    val SHINY_MOLTRES_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("moltres", true)
    val SHINY_MUDKIP_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("mudkip", true)
    val SHINY_PALKIA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("palkia", true)
    val SHINY_PICHU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("pichu", true)
    val SHINY_PIKACHU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("pikachu", true)
    val SHINY_POPPLIO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("popplio", true)
    val SHINY_POLIWHIRL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("poliwhirl", true)
    val SHINY_RAIKOU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("raikou", true)
    val SHINY_RAYQUAZA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("rayquaza", true)
    val SHINY_REGICE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("regice", true)
    val SHINY_REGIGIGAS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("regigigas", true)
    val SHINY_REGIROCK_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("regirock", true)
    val SHINY_REGISTEEL_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("registeel", true)
    val SHINY_ROWLET_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("rowlet", true)
    val SHINY_SABLEYE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("sableye", true)
    val SHINY_SEEDOT_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("seedot", true)
    val SHINY_RHYDON_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("rhydon", true)
    val SHINY_SHAYMIN_LAND_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("shaymin_land", true)
    val SHINY_SHAYMIN_SKY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("shaymin_sky", true)
    val SHINY_SKITTY_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("skitty", true)
    val SHINY_SMOOCHUM_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("smoochum", true)
    val SHINY_SNORLAX_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("snorlax", true)
    val SHINY_SUBSTITUTE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("substitute", true)
    val SHINY_SUICUNE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("suicune", true)
    val SHINY_SWABLU_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("swablu", true)
    val SHINY_TOGEPI_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("togepi", true)
    val SHINY_TORCHIC_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("torchic", true)
    val SHINY_TOTODILE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("totodile", true)
    val SHINY_TREECKO_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("treecko", true)
    val SHINY_UXIE_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("uxie", true)
    val SHINY_VENUSAUR_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("venusaur", true)
    val SHINY_WAILMER_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("wailmer", true)
    val SHINY_WYNAUT_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("wynaut", true)
    val SHINY_ZERAORA_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("zeraora", true)
    val SHINY_ZAPDOS_POKEDOLL: RegistrySupplier<Block> = registerBlockItem("zapdos", true)


    private fun registerBlockItem(name: String, shiny: Boolean, scale: Float = 1.0f): RegistrySupplier<Block> {
        val block = registerBlock<Block>(
            POKEDOLLS, (if (shiny) "shiny_" else "") + name + "_doll"
        ) { PokeDollBlock(name, shiny, scale) }
        GenerationsItems.ITEMS.register(
            (if (shiny) "shiny_" else "") + name + "_doll"
        ) { BlockItem(block.get(), Item.Properties()) }
        return block
    }

    fun init() {
        GenerationsCore.LOGGER.info("Registering Generations PokeDolls")
        POKEDOLLS.register()
    }
}
