package generations.gg.generations.core.generationscore.forge.datagen.generators.items;

import dev.architectury.registry.registries.RegistrySupplier;
import generations.gg.generations.core.generationscore.GenerationsCore;
import generations.gg.generations.core.generationscore.world.item.GenerationsArmor;
import generations.gg.generations.core.generationscore.world.item.GenerationsItems;
import generations.gg.generations.core.generationscore.world.item.GenerationsTools;
import generations.gg.generations.core.generationscore.world.item.curry.CurryType;
import generations.gg.generations.core.generationscore.world.level.block.*;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.client.model.generators.ItemModelBuilder;
import net.minecraftforge.client.model.generators.ItemModelProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.Objects;
import java.util.function.BiConsumer;

public class ItemDatagen extends ItemModelProvider {

    public ItemDatagen(PackOutput packOutput, ExistingFileHelper existingFileHelper) {
        super(packOutput, GenerationsCore.MOD_ID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        GenerationsItems.POKEBALLS.forEach(pokeball -> createItem(pokeball, "pokeballs/"));

        createItem(GenerationsItems.POTION, "restoration/");
        createItem(GenerationsItems.SUPER_POTION, "restoration/");
        createItem(GenerationsItems.HYPER_POTION, "restoration/");
        createItem(GenerationsItems.MAX_POTION, "restoration/");
        createItem(GenerationsItems.REVIVE, "restoration/");
        createItem(GenerationsItems.MAX_REVIVE, "restoration/");
        createItem(GenerationsItems.ETHER, "restoration/");
        createItem(GenerationsItems.MAX_ETHER, "restoration/");
        createItem(GenerationsItems.ELIXIR, "restoration/");
        createItem(GenerationsItems.MAX_ELIXIR, "restoration/");
        createItem(GenerationsItems.PP_UP, "restoration/");
        createItem(GenerationsItems.PP_MAX, "restoration/");
        createItem(GenerationsItems.FULL_HEAL, "restoration/");
        createItem(GenerationsItems.FULL_RESTORE, "restoration/");
        createItem(GenerationsItems.ANTIDOTE, "restoration/");
        createItem(GenerationsItems.PARALYZE_HEAL, "restoration/");
        createItem(GenerationsItems.AWAKENING, "restoration/");
        createItem(GenerationsItems.BURN_HEAL, "restoration/");
        createItem(GenerationsItems.ICE_HEAL, "restoration/");
        /*createItem(GenerationsItems.RARE_CANDY, "restoration/");
        createItem(GenerationsItems.XS_CANDY, "restoration/");
        createItem(GenerationsItems.S_CANDY, "restoration/");
        createItem(GenerationsItems.M_CANDY, "restoration/");
        createItem(GenerationsItems.L_CANDY, "restoration/");
        createItem(GenerationsItems.XL_CANDY, "restoration/");*/
        createItem(GenerationsItems.HEALTH_FEATHER, "restoration/");
        createItem(GenerationsItems.MUSCLE_FEATHER, "restoration/");
        createItem(GenerationsItems.RESIST_FEATHER, "restoration/");
        createItem(GenerationsItems.GENIUS_FEATHER, "restoration/");
        createItem(GenerationsItems.CLEVER_FEATHER, "restoration/");
        createItem(GenerationsItems.SWIFT_FEATHER, "restoration/");
//        createItem(GenerationsItems.HP_UP, "restoration/");
//        createItem(GenerationsItems.PROTEIN, "restoration/");
//        createItem(GenerationsItems.IRON, "restoration/");
//        createItem(GenerationsItems.CALCIUM, "restoration/");
//        createItem(GenerationsItems.ZINC, "restoration/");
//        createItem(GenerationsItems.CARBOS, "restoration/");
        createItem(GenerationsItems.X_ATTACK, "restoration/");
        createItem(GenerationsItems.X_DEFENSE, "restoration/");
        createItem(GenerationsItems.X_SPECIAL_ATTACK, "restoration/");
        createItem(GenerationsItems.X_SPECIAL_DEFENSE, "restoration/");
        createItem(GenerationsItems.X_SPEED, "restoration/");
        createItem(GenerationsItems.X_ACCURACY, "restoration/");
        createItem(GenerationsItems.DIRE_HIT, "restoration/");
        createItem(GenerationsItems.GUARD_SPEC, "restoration/");
        createItem(GenerationsItems.PURPLE_JUICE, "restoration/");
        createItem(GenerationsItems.RED_JUICE, "restoration/");
        createItem(GenerationsItems.YELLOW_JUICE, "restoration/");
        createItem(GenerationsItems.BLUE_JUICE, "restoration/");
        createItem(GenerationsItems.GREEN_JUICE, "restoration/");
        createItem(GenerationsItems.PINK_JUICE, "restoration/");
        createItem(GenerationsItems.COLORFUL_SHAKE, "restoration/");
        createItem(GenerationsItems.PERILOUS_SOUP, "restoration/");
        createItem(GenerationsItems.RARE_SODA, "restoration/");
        createItem(GenerationsItems.ULTRA_RARE_SODA, "restoration/");
        createMint(GenerationsItems.ADAMANT_MINT, "red");
        createMint(GenerationsItems.BOLD_MINT, "purple");
        createMint(GenerationsItems.BRAVE_MINT, "red");
        createMint(GenerationsItems.CALM_MINT, "pink");
        createMint(GenerationsItems.CAREFUL_MINT, "pink");
        createMint(GenerationsItems.GENTLE_MINT, "pink");
        createMint(GenerationsItems.HASTY_MINT, "green");
        createMint(GenerationsItems.IMPISH_MINT, "purple");
        createMint(GenerationsItems.JOLLY_MINT, "green");
        createMint(GenerationsItems.LONELY_MINT, "red");
        createMint(GenerationsItems.LAX_MINT, "purple");
        createMint(GenerationsItems.MILD_MINT, "blue");
        createMint(GenerationsItems.MODEST_MINT, "blue");
        createMint(GenerationsItems.NAIVE_MINT, "green");
        createMint(GenerationsItems.NAUGHTY_MINT, "red");
        createMint(GenerationsItems.RASH_MINT, "blue");
        createMint(GenerationsItems.RELAXED_MINT, "purple");
        createMint(GenerationsItems.SASSY_MINT, "pink");
        createMint(GenerationsItems.SERIOUS_MINT, "yellow");
        createMint(GenerationsItems.TIMID_MINT, "green");
        createMint(GenerationsItems.QUIET_MINT, "blue");
        createItem(GenerationsItems.FRESH_WATER, "restoration/");
        createItem(GenerationsItems.SODA_POP, "restoration/");
        createItem(GenerationsItems.LEMONADE, "restoration/");
        createItem(GenerationsItems.MOOMOO_MILK, "restoration/");
        createItem(GenerationsItems.LUMIOSE_GALETTE, "restoration/");
        createItem(GenerationsItems.SHALOUR_SABLE, "restoration/");
        createItem(GenerationsItems.CASTELIACONE, "restoration/");
        createItem(GenerationsItems.OLD_GATEAU, "restoration/");
        createItem(GenerationsItems.BIG_MALASADA, "restoration/");
        createItem(GenerationsItems.LAVA_COOKIE, "restoration/");
        createItem(GenerationsItems.RAGE_CANDY_BAR, "restoration/");
        createItem(GenerationsItems.BLUE_FLUTE, "restoration/");
        createItem(GenerationsItems.RED_FLUTE, "restoration/");
        createItem(GenerationsItems.YELLOW_FLUTE, "restoration/");
        createItem(GenerationsItems.HEAL_POWDER, "restoration/");
        createItem(GenerationsItems.ENERGY_POWDER, "restoration/");
        createItem(GenerationsItems.ENERGY_ROOT, "restoration/");
        createItem(GenerationsItems.REVIVAL_HERB, "restoration/");
        createItem(GenerationsItems.SWEET_HEART, "restoration/");
        createItem(GenerationsItems.BASIC_SWEET_POKE_PUFF, "restoration/");
        createItem(GenerationsItems.BASIC_CITRUS_POKE_PUFF, "restoration/");
        createItem(GenerationsItems.BASIC_MINT_POKE_PUFF, "restoration/");
        createItem(GenerationsItems.BASIC_MOCHA_POKE_PUFF, "restoration/");
        createItem(GenerationsItems.BASIC_SPICE_POKE_PUFF, "restoration/");

        createItem(GenerationsItems.DYNAMAX_CANDY, "restoration/");
        createItem(GenerationsItems.MAX_HONEY, "restoration/");
        createItem(GenerationsItems.MAX_MUSHROOMS, "restoration/");
        createItem(GenerationsItems.MAX_POWDER, "restoration/");
        createItem(GenerationsItems.MAX_SOUP, "restoration/");

        createItem(GenerationsItems.Z_INGOT, "ingots/");
        createItem(GenerationsItems.ALUMINUM_INGOT, "ingots/");
        createItem(GenerationsItems.ALUMINUM_PLATE, "materials/");

        createItem(GenerationsItems.KOMALA_COFFEE, "consumable/");
        createItem(GenerationsItems.OMELETTE, "consumable/");
        createItem(GenerationsItems.PINAP_JUICE, "consumable/");
        createItem(GenerationsItems.ROSERADE_TEA, "consumable/");
        createItem(GenerationsItems.TAPU_COCOA, "consumable/");

        createHeldItem(GenerationsItems.ABSORB_BULB);
        createHeldItem(GenerationsItems.ADRENALINE_ORB);
        createHeldItem(GenerationsItems.AIR_BALLOON);
        createHeldItem(GenerationsItems.AMULET_COIN);
        createHeldItem(GenerationsItems.BERRY_JUICE);
        createHeldItem(GenerationsItems.BINDING_BAND);
        createHeldItem(GenerationsItems.BLACK_FLUTE);
        createHeldItem(GenerationsItems.BLUNDER_POLICY);
        createHeldItem(GenerationsItems.BRIGHT_POWDER);
        createHeldItem(GenerationsItems.CELL_BATTERY);
        createHeldItem(GenerationsItems.CHARCOAL);
        createHeldItem(GenerationsItems.CHOICE_BAND);
        createHeldItem(GenerationsItems.CLEANSE_TAG);
        createHeldItem(GenerationsItems.DAMP_ROCK);
        createHeldItem(GenerationsItems.DESTINY_KNOT);
        createHeldItem(GenerationsItems.EJECT_BUTTON);
        createHeldItem(GenerationsItems.EJECT_PACK);
        createHeldItem(GenerationsItems.EVERSTONE);
        createHeldItem(GenerationsItems.EVIOLITE);
        createHeldItem(GenerationsItems.EXP_ALL);
        createHeldItem(GenerationsItems.EXPERT_BELT);
        createHeldItem(GenerationsItems.FLAME_ORB);
        createHeldItem(GenerationsItems.FLOAT_STONE);
        createHeldItem(GenerationsItems.FLUFFY_TAIL);
        createHeldItem(GenerationsItems.FOCUS_SASH);
        createHeldItem(GenerationsItems.GRIP_CLAW);
        createHeldItem(GenerationsItems.HEAT_ROCK);
        createHeldItem(GenerationsItems.ICY_ROCK);
        createHeldItem(GenerationsItems.IRON_BALL);
        createHeldItem(GenerationsItems.LAGGING_TAIL);
        createHeldItem(GenerationsItems.LEEK);
        createHeldItem(GenerationsItems.LIFE_ORB);
        createHeldItem(GenerationsItems.LIGHT_BALL);
        createHeldItem(GenerationsItems.LUCKY_PUNCH);
        createHeldItem(GenerationsItems.LUMINOUS_MOSS);
        createHeldItem(GenerationsItems.MACHO_BRACE);
        createHeldItem(GenerationsItems.MENTAL_HERB);
        createHeldItem(GenerationsItems.METAL_POWDER);
        createHeldItem(GenerationsItems.METRONOME);
        createHeldItem(GenerationsItems.POKE_DOLL);
        createHeldItem(GenerationsItems.POKE_TOY);
        createHeldItem(GenerationsItems.POWER_ANKLET);
        createHeldItem(GenerationsItems.POWER_BAND);
        createHeldItem(GenerationsItems.POWER_BELT);
        createHeldItem(GenerationsItems.POWER_BRACER);
        createHeldItem(GenerationsItems.POWER_HERB);
        createHeldItem(GenerationsItems.POWER_LENS);
        createHeldItem(GenerationsItems.POWER_WEIGHT);
        createHeldItem(GenerationsItems.PRISM_SCALE);
        createHeldItem(GenerationsItems.PROTECTIVE_PADS);
        createHeldItem(GenerationsItems.QUICK_POWDER);
        createHeldItem(GenerationsItems.RED_CARD);
        createHeldItem(GenerationsItems.RING_TARGET);
        createHeldItem(GenerationsItems.ROOM_SERVICE);
        createHeldItem(GenerationsItems.SCOPE_LENS);
        createHeldItem(GenerationsItems.SHED_SHELL);
        createHeldItem(GenerationsItems.SHELL_BELL);
        createHeldItem(GenerationsItems.SMOKE_BALL);
        createHeldItem(GenerationsItems.SMOOTH_ROCK);
        createHeldItem(GenerationsItems.SNOWBALL);
        createHeldItem(GenerationsItems.SOOTHE_BELL);
        createHeldItem(GenerationsItems.SOUL_DEW);
        createHeldItem(GenerationsItems.STICKY_BARB);
        createHeldItem(GenerationsItems.TERRAIN_EXTENDER);
        createHeldItem(GenerationsItems.THICK_CLUB);
        createHeldItem(GenerationsItems.THROAT_SPRAY);
        createHeldItem(GenerationsItems.TOXIC_ORB);
        createHeldItem(GenerationsItems.UP_GRADE);
        createHeldItem(GenerationsItems.UTILITY_UMBRELLA);
        createHeldItem(GenerationsItems.WEAKNESS_POLICY);
        createHeldItem(GenerationsItems.WHITE_FLUTE);
        createHeldItem(GenerationsItems.WHITE_HERB);
        createHeldItem(GenerationsItems.WIDE_LENS);
        createHeldItem(GenerationsItems.ZOOM_LENS);

        createHeldItem(GenerationsItems.AGUAV_BERRY, "berries/");
        createHeldItem(GenerationsItems.APICOT_BERRY, "berries/");
        createHeldItem(GenerationsItems.ASPEAR_BERRY, "berries/");
        createHeldItem(GenerationsItems.BABIRI_BERRY, "berries/");
        createHeldItem(GenerationsItems.BELUE_BERRY, "berries/");
        createHeldItem(GenerationsItems.BLUK_BERRY, "berries/");
        createHeldItem(GenerationsItems.CHARTI_BERRY, "berries/");
        createHeldItem(GenerationsItems.CHERI_BERRY, "berries/");
        createHeldItem(GenerationsItems.CHESTO_BERRY, "berries/");
        createHeldItem(GenerationsItems.CHILAN_BERRY, "berries/");
        createHeldItem(GenerationsItems.CHOPLE_BERRY, "berries/");
        createHeldItem(GenerationsItems.COBA_BERRY, "berries/");
        createHeldItem(GenerationsItems.COLBUR_BERRY, "berries/");
        createHeldItem(GenerationsItems.CORNN_BERRY, "berries/");
        createHeldItem(GenerationsItems.CUSTAP_BERRY, "berries/");
        createHeldItem(GenerationsItems.DRASH_BERRY, "berries/");
        createHeldItem(GenerationsItems.DURIN_BERRY, "berries/");
        createHeldItem(GenerationsItems.EGGANT_BERRY, "berries/");
        createHeldItem(GenerationsItems.ENIGMA_BERRY, "berries/");
        createHeldItem(GenerationsItems.FIGY_BERRY, "berries/");
        createHeldItem(GenerationsItems.GANLON_BERRY, "berries/");
        createHeldItem(GenerationsItems.GINEMA_BERRY, "berries/");
        createHeldItem(GenerationsItems.GREPA_BERRY, "berries/");
        createHeldItem(GenerationsItems.HABAN_BERRY, "berries/");
        createHeldItem(GenerationsItems.HONDEW_BERRY, "berries/");
        createHeldItem(GenerationsItems.IAPAPA_BERRY, "berries/");
        createHeldItem(GenerationsItems.JABOCA_BERRY, "berries/");
        createHeldItem(GenerationsItems.KASIB_BERRY, "berries/");
        createHeldItem(GenerationsItems.KEBIA_BERRY, "berries/");
        createHeldItem(GenerationsItems.KEE_BERRY, "berries/");
        createHeldItem(GenerationsItems.KELPSY_BERRY, "berries/");
        createHeldItem(GenerationsItems.KUO_BERRY, "berries/");
        createHeldItem(GenerationsItems.LANSAT_BERRY, "berries/");
        createHeldItem(GenerationsItems.LEPPA_BERRY, "berries/");
        createHeldItem(GenerationsItems.LIECHI_BERRY, "berries/");
        createHeldItem(GenerationsItems.LUM_BERRY, "berries/");
        createHeldItem(GenerationsItems.MAGO_BERRY, "berries/");
        createHeldItem(GenerationsItems.MAGOST_BERRY, "berries/");
        createHeldItem(GenerationsItems.MARANGA_BERRY, "berries/");
        createHeldItem(GenerationsItems.MICLE_BERRY, "berries/");
        createHeldItem(GenerationsItems.NANAB_BERRY, "berries/");
        createHeldItem(GenerationsItems.NINIKU_BERRY, "berries/");
        createHeldItem(GenerationsItems.NOMEL_BERRY, "berries/");
        createHeldItem(GenerationsItems.NUTPEA_BERRY, "berries/");
        createHeldItem(GenerationsItems.OCCA_BERRY, "berries/");
        createHeldItem(GenerationsItems.ORAN_BERRY, "berries/");
        createHeldItem(GenerationsItems.PAMTRE_BERRY, "berries/");
        createHeldItem(GenerationsItems.PASSHO_BERRY, "berries/");
        createHeldItem(GenerationsItems.PAYAPA_BERRY, "berries/");
        createHeldItem(GenerationsItems.PECHA_BERRY, "berries/");
        createHeldItem(GenerationsItems.PERSIM_BERRY, "berries/");
        createHeldItem(GenerationsItems.PETAYA_BERRY, "berries/");
        createHeldItem(GenerationsItems.PINAP_BERRY, "berries/");
        createHeldItem(GenerationsItems.POMEG_BERRY, "berries/");
        createHeldItem(GenerationsItems.PUMKIN_BERRY, "berries/");
        createHeldItem(GenerationsItems.QUALOT_BERRY, "berries/");
        createHeldItem(GenerationsItems.RABUTA_BERRY, "berries/");
        createHeldItem(GenerationsItems.RAWST_BERRY, "berries/");
        createHeldItem(GenerationsItems.RAZZ_BERRY, "berries/");
        createHeldItem(GenerationsItems.RINDO_BERRY, "berries/");
        createHeldItem(GenerationsItems.ROSELI_BERRY, "berries/");
        createHeldItem(GenerationsItems.ROWAP_BERRY, "berries/");
        createHeldItem(GenerationsItems.SALAC_BERRY, "berries/");
        createHeldItem(GenerationsItems.SHUCA_BERRY, "berries/");
        createHeldItem(GenerationsItems.SITRUS_BERRY, "berries/");
        createHeldItem(GenerationsItems.SPELON_BERRY, "berries/");
        createHeldItem(GenerationsItems.STARF_BERRY, "berries/");
        createHeldItem(GenerationsItems.STRIB_BERRY, "berries/");
        createHeldItem(GenerationsItems.TAMATO_BERRY, "berries/");
        createHeldItem(GenerationsItems.TANGA_BERRY, "berries/");
        createHeldItem(GenerationsItems.TOPO_BERRY, "berries/");
        createHeldItem(GenerationsItems.TOUGA_BERRY, "berries/");
        createHeldItem(GenerationsItems.WACAN_BERRY, "berries/");
        createHeldItem(GenerationsItems.WATMEL_BERRY, "berries/");
        createHeldItem(GenerationsItems.WEPEAR_BERRY, "berries/");
        createHeldItem(GenerationsItems.WIKI_BERRY, "berries/");
        createHeldItem(GenerationsItems.YACHE_BERRY, "berries/");
        createHeldItem(GenerationsItems.YAGO_BERRY, "berries/");

        createHeldItem(GenerationsItems.BURN_DRIVE, "drives/");
        createHeldItem(GenerationsItems.CHILL_DRIVE, "drives/");
        createHeldItem(GenerationsItems.DOUSE_DRIVE, "drives/");
        createHeldItem(GenerationsItems.SHOCK_DRIVE, "drives/");

        createHeldItem(GenerationsItems.BUG_GEM, "gems/");
        createHeldItem(GenerationsItems.DARK_GEM, "gems/");
        createHeldItem(GenerationsItems.DRAGON_GEM, "gems/");
        createHeldItem(GenerationsItems.ELECTRIC_GEM, "gems/");
        createHeldItem(GenerationsItems.FAIRY_GEM, "gems/");
        createHeldItem(GenerationsItems.FIGHTING_GEM, "gems/");
        createHeldItem(GenerationsItems.FIRE_GEM, "gems/");
        createHeldItem(GenerationsItems.FLYING_GEM, "gems/");
        createHeldItem(GenerationsItems.GHOST_GEM, "gems/");
        createHeldItem(GenerationsItems.GRASS_GEM, "gems/");
        createHeldItem(GenerationsItems.GROUND_GEM, "gems/");
        createHeldItem(GenerationsItems.ICE_GEM, "gems/");
        createHeldItem(GenerationsItems.NORMAL_GEM, "gems/");
        createHeldItem(GenerationsItems.POISON_GEM, "gems/");
        createHeldItem(GenerationsItems.PSYCHIC_GEM, "gems/");
        createHeldItem(GenerationsItems.ROCK_GEM, "gems/");
        createHeldItem(GenerationsItems.STEEL_GEM, "gems/");
        createHeldItem(GenerationsItems.WATER_GEM, "gems/");

        createHeldItem(GenerationsItems.FULL_INCENSE, "incense/");
        createHeldItem(GenerationsItems.LAX_INCENSE, "incense/");
        createHeldItem(GenerationsItems.LUCK_INCENSE, "incense/");
        createHeldItem(GenerationsItems.ODD_INCENSE, "incense/");
        createHeldItem(GenerationsItems.PURE_INCENSE, "incense/");
        createHeldItem(GenerationsItems.ROCK_INCENSE, "incense/");
        createHeldItem(GenerationsItems.ROSE_INCENSE, "incense/");
        createHeldItem(GenerationsItems.SEA_INCENSE, "incense/");
        createHeldItem(GenerationsItems.WAVE_INCENSE, "incense/");

        createHeldItem(GenerationsItems.ABOMASITE, "megastones/");
        createHeldItem(GenerationsItems.ABSOLITE, "megastones/");
        createHeldItem(GenerationsItems.AERODACTYLITE, "megastones/");
        createHeldItem(GenerationsItems.AGGRONITE, "megastones/");
        createHeldItem(GenerationsItems.ALAKAZITE, "megastones/");
        createHeldItem(GenerationsItems.ALTARIANITE, "megastones/");
        createHeldItem(GenerationsItems.AMPHAROSITE, "megastones/");
        createHeldItem(GenerationsItems.AUDINITE, "megastones/");
        createHeldItem(GenerationsItems.BANETTITE, "megastones/");
        createHeldItem(GenerationsItems.BEEDRILLITE, "megastones/");
        createHeldItem(GenerationsItems.BLASTOISINITE, "megastones/");
        createHeldItem(GenerationsItems.BLAZIKENITE, "megastones/");
        createHeldItem(GenerationsItems.CAMERUPTITE, "megastones/");
        createHeldItem(GenerationsItems.CHARIZARDITE_X, "megastones/");
        createHeldItem(GenerationsItems.CHARIZARDITE_Y, "megastones/");
        createHeldItem(GenerationsItems.DIANCITE, "megastones/");
        createHeldItem(GenerationsItems.GALLADITE, "megastones/");
        createHeldItem(GenerationsItems.GARCHOMPITE, "megastones/");
        createHeldItem(GenerationsItems.GARDEVOIRITE, "megastones/");
        createHeldItem(GenerationsItems.GENGARITE, "megastones/");
        createHeldItem(GenerationsItems.GLALITITE, "megastones/");
        createHeldItem(GenerationsItems.GYARADOSITE, "megastones/");
        createHeldItem(GenerationsItems.HERACRONITE, "megastones/");
        createHeldItem(GenerationsItems.HOUNDOOMINITE, "megastones/");
        createHeldItem(GenerationsItems.KANGASKHANITE, "megastones/");
        createHeldItem(GenerationsItems.LATIASITE, "megastones/");
        createHeldItem(GenerationsItems.LATIOSITE, "megastones/");
        createHeldItem(GenerationsItems.LOPUNNNITE, "megastones/");
        createHeldItem(GenerationsItems.LUCARIONITE, "megastones/");
        createHeldItem(GenerationsItems.MANECTITE, "megastones/");
        createHeldItem(GenerationsItems.MAWILITE, "megastones/");
        createHeldItem(GenerationsItems.MEDICHAMITE, "megastones/");
        createHeldItem(GenerationsItems.METAGROSSITE, "megastones/");
        createHeldItem(GenerationsItems.MEWTWONITE_X, "megastones/");
        createHeldItem(GenerationsItems.MEWTWONITE_Y, "megastones/");
        createHeldItem(GenerationsItems.PIDGEOTITE, "megastones/");
        createHeldItem(GenerationsItems.PINSIRITE, "megastones/");
        createHeldItem(GenerationsItems.SABLENITE, "megastones/");
        createHeldItem(GenerationsItems.SALAMENCITE, "megastones/");
        createHeldItem(GenerationsItems.SCEPTILITE, "megastones/");
        createHeldItem(GenerationsItems.SCIZORITE, "megastones/");
        createHeldItem(GenerationsItems.SHARPEDONITE, "megastones/");
        createHeldItem(GenerationsItems.SLOWBRONITE, "megastones/");
        createHeldItem(GenerationsItems.STEELIXITE, "megastones/");
        createHeldItem(GenerationsItems.SWAMPERTITE, "megastones/");
        createHeldItem(GenerationsItems.TYRANITARITE, "megastones/");
        createHeldItem(GenerationsItems.VENUSAURITE, "megastones/");

        createHeldItem(GenerationsItems.BUG_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.DARK_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.DRAGON_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.ELECTRIC_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.FAIRY_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.FIGHTING_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.FIRE_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.FLYING_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.GHOST_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.GRASS_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.GROUND_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.ICE_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.POISON_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.PSYCHIC_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.ROCK_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.STEEL_MEMORY_DRIVE, "memory/");
        createHeldItem(GenerationsItems.WATER_MEMORY_DRIVE, "memory/");

        createHeldItem(GenerationsItems.DRACO_PLATE, "plates/");
        createHeldItem(GenerationsItems.DREAD_PLATE, "plates/");
        createHeldItem(GenerationsItems.EARTH_PLATE, "plates/");
        createHeldItem(GenerationsItems.FIST_PLATE, "plates/");
        createHeldItem(GenerationsItems.FLAME_PLATE, "plates/");
        createHeldItem(GenerationsItems.ICICLE_PLATE, "plates/");
        createHeldItem(GenerationsItems.INSECT_PLATE, "plates/");
        createHeldItem(GenerationsItems.IRON_PLATE, "plates/");
        createHeldItem(GenerationsItems.MEADOW_PLATE, "plates/");
        createHeldItem(GenerationsItems.MIND_PLATE, "plates/");
        createHeldItem(GenerationsItems.PIXIE_PLATE, "plates/");
        createHeldItem(GenerationsItems.SKY_PLATE, "plates/");
        createHeldItem(GenerationsItems.SPLASH_PLATE, "plates/");
        createHeldItem(GenerationsItems.SPOOKY_PLATE, "plates/");
        createHeldItem(GenerationsItems.STONE_PLATE, "plates/");
        createHeldItem(GenerationsItems.TOXIC_PLATE, "plates/");
        createHeldItem(GenerationsItems.ZAP_PLATE, "plates/");

        createHeldItem(GenerationsItems.BUGINIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.DARKINIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.DRAGONIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.ELECTRIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.FAIRIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.FIGHTINIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.FIRIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.FLYINIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.GHOSTIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.GRASSIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.GROUNDIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.ICIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.NORMALIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.POISONIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.PSYCHIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.ROCKIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.STEELIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.WATERIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.ALORAICHIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.DECIDIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.EEVIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.INCINIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.KOMMONIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.LUNALIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.LYCANIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.MARSHADIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.MEWNIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.MIMIKIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.PIKANIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.PIKASHUNIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.PRIMARIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.SNORLIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.SOLGANIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.TAPUNIUM_Z, "zcrystals/");
        createHeldItem(GenerationsItems.ULTRANECROZIUM_Z, "zcrystals/");

        GenerationsPokeDolls.POKEDOLLS.forEach(this::createPokedoll);

        createItem(GenerationsItems.RELIC_GOLD, "valuables/");
        createItem(GenerationsItems.RELIC_COPPER, "valuables/");
        createItem(GenerationsItems.RELIC_BAND, "valuables/");
        createItem(GenerationsItems.RELIC_SILVER, "valuables/");
        createItem(GenerationsItems.RELIC_STATUE, "valuables/");
        createItem(GenerationsItems.RELIC_VASE, "valuables/");
        createItem(GenerationsItems.RELIC_CROWN, "valuables/");
        createItem(GenerationsItems.HEART_SCALE, "valuables/");
        createItem(GenerationsItems.SHOAL_SHELL, "valuables/");
        createItem(GenerationsItems.SHOAL_SALT, "valuables/");
        createItem(GenerationsItems.STARDUST, "valuables/");
        createItem(GenerationsItems.RARE_BONE, "valuables/");
        createItem(GenerationsItems.SILVER_LEAF, "valuables/");
        createItem(GenerationsItems.STRANGE_SOUVENIR, "valuables/");
        createItem(GenerationsItems.SLOWPOKE_TAIL, "valuables/");
        createItem(GenerationsItems.ODD_KEYSTONE, "valuables/");
        createItem(GenerationsItems.ESCAPE_ROPE, "valuables/");
        createItem(GenerationsItems.BEACH_GLASS, "valuables/");
        createItem(GenerationsItems.CHALKY_STONE, "valuables/");
        createItem(GenerationsItems.LONE_EARRING, "valuables/");
        createItem(GenerationsItems.PRETTY_FEATHER, "valuables/");
        createItem(GenerationsItems.MARBLE, "valuables/");
        createItem(GenerationsItems.POLISHED_MUD_BALL, "valuables/");
        createItem(GenerationsItems.STRETCHY_SPRING, "valuables/");
        createItem(GenerationsItems.TROPICAL_SHELL, "valuables/");
        createItem(GenerationsItems.BALM_MUSHROOM, "valuables/");
        createItem(GenerationsItems.BIG_MUSHROOM, "valuables/");
        createItem(GenerationsItems.BIG_NUGGET, "valuables/");
        createItem(GenerationsItems.BIG_PEARL, "valuables/");
        createItem(GenerationsItems.GOLD_LEAF, "valuables/");
        createItem(GenerationsItems.SMALL_BOUQUET, "valuables/");
        createItem(GenerationsItems.BLUE_SHARD, "valuables/");
        createItem(GenerationsItems.ENIGMA_SHARD, "valuables/");
        createItem(GenerationsItems.COMET_SHARD, "valuables/");
        createItem(GenerationsItems.GREEN_SHARD, "valuables/");
        createItem(GenerationsItems.MEGASTONE_SHARD, "valuables/");
        createItem(GenerationsItems.NUGGET, "valuables/");
        createItem(GenerationsItems.PEARL, "valuables/");
        createItem(GenerationsItems.PEARL_STRING, "valuables/");
        createItem(GenerationsItems.RED_SHARD, "valuables/");
        createItem(GenerationsItems.STAR_PIECE, "valuables/");
        createItem(GenerationsItems.TINY_MUSHROOM, "valuables/");
        createItem(GenerationsItems.YELLOW_SHARD, "valuables/");
        createItem(GenerationsItems.HONEY, "valuables/");
        createItem(GenerationsItems.BUG_CANDY, "valuables/");
        createItem(GenerationsItems.DARK_CANDY, "valuables/");
        createItem(GenerationsItems.DRAGON_CANDY, "valuables/");
        createItem(GenerationsItems.ELECTRIC_CANDY, "valuables/");
        createItem(GenerationsItems.FAIRY_CANDY, "valuables/");
        createItem(GenerationsItems.FIGHTING_CANDY, "valuables/");
        createItem(GenerationsItems.FIRE_CANDY, "valuables/");
        createItem(GenerationsItems.FLYING_CANDY, "valuables/");
        createItem(GenerationsItems.GHOST_CANDY, "valuables/");
        createItem(GenerationsItems.GRASS_CANDY, "valuables/");
        createItem(GenerationsItems.GROUND_CANDY, "valuables/");
        createItem(GenerationsItems.ICE_CANDY, "valuables/");
        createItem(GenerationsItems.NORMAL_CANDY, "valuables/");
        createItem(GenerationsItems.POISON_CANDY, "valuables/");
        createItem(GenerationsItems.PSYCHIC_CANDY, "valuables/");
        createItem(GenerationsItems.ROCK_CANDY, "valuables/");
        createItem(GenerationsItems.STEEL_CANDY, "valuables/");
        createItem(GenerationsItems.WATER_CANDY, "valuables/");
        createItem(GenerationsItems.NULL_CANDY, "valuables/");

        GenerationsItems.BADGES.forEach(badge -> createItem(badge, "badges/"));
        GenerationsItems.RIBBONS.forEach(ribbon -> createItem(ribbon, "ribbons/"));

        createItem(GenerationsItems.DAWN_STONE, "natural/");
        createItem(GenerationsItems.DUSK_STONE, "natural/");
        createItem(GenerationsItems.FIRE_STONE, "natural/");
        createItem(GenerationsItems.ICE_STONE, "natural/");
        createItem(GenerationsItems.LEAF_STONE, "natural/");
        createItem(GenerationsItems.MOON_STONE, "natural/");
        createItem(GenerationsItems.SHINY_STONE, "natural/");
        createItem(GenerationsItems.SUN_STONE, "natural/");
        createItem(GenerationsItems.THUNDER_STONE, "natural/");
        createItem(GenerationsItems.WATER_STONE, "natural/");
        createItem(GenerationsItems.DAWN_STONE_SHARD, "natural/");
        createItem(GenerationsItems.DUSK_STONE_SHARD, "natural/");
        createItem(GenerationsItems.FIRE_STONE_SHARD, "natural/");
        createItem(GenerationsItems.ICE_STONE_SHARD, "natural/");
        createItem(GenerationsItems.LEAF_STONE_SHARD, "natural/");
        createItem(GenerationsItems.MOON_STONE_SHARD, "natural/");
        createItem(GenerationsItems.SHINY_STONE_SHARD, "natural/");
        createItem(GenerationsItems.SUN_STONE_SHARD, "natural/");
        createItem(GenerationsItems.THUNDER_STONE_SHARD, "natural/");
        createItem(GenerationsItems.WATER_STONE_SHARD, "natural/");
        createItem(GenerationsItems.CRYSTAL, "natural/");
        createItem(GenerationsItems.RUBY, "natural/");
        createItem(GenerationsItems.SAPPHIRE, "natural/");
        createItem(GenerationsItems.SILICON, "natural/");
        createItem(GenerationsItems.GROWTH_MULCH, "natural/");
        createItem(GenerationsItems.DAMP_MULCH, "natural/");
        createItem(GenerationsItems.STABLE_MULCH, "natural/");
        createItem(GenerationsItems.GOOEY_MULCH, "natural/");
        createItem(GenerationsItems.AMAZE_MULCH, "natural/");
        createItem(GenerationsItems.BOOST_MULCH, "natural/");
        createItem(GenerationsItems.RICH_MULCH, "natural/");
        createItem(GenerationsItems.SURPRISE_MULCH, "natural/");
        createItem(GenerationsItems.GALARICA_TWIG, "natural/");
        createItem(GenerationsItems.COVERED_OLD_AMBER, "natural/fossils/");
        createItem(GenerationsItems.COVERED_ARMOR_FOSSIL, "natural/fossils/");
//        createItem(GenerationsItems.COVERED_BIRD_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVERED_CLAW_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVERED_COVER_FOSSIL, "natural/fossils/");
        //createItem(GenerationsItems.COVERED_DINO_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVERED_DOME_FOSSIL, "natural/fossils/");
        //createItem(GenerationsItems.COVERED_DRAKE_FOSSIL, "natural/fossils/");
        //createItem(GenerationsItems.COVERED_FISH_FOSSIL, "natural/fossils/");
        //createItem(GenerationsItems.COVERED_HELIX_FOSSIL, "natural/fossils/");
        //createItem(GenerationsItems.COVERED_JAW_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVERED_PLUME_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVERED_ROOT_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVERED_SAIL_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVERED_SKULL_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.OLD_AMBER, "natural/fossils/");
        createItem(GenerationsItems.ARCTOVISH_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.ARCTOZOLT_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.ARMOR_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.BIRD_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.CLAW_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.COVER_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.DINO_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.DOME_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.DRACOVISH_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.DRACOZOLT_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.DRAKE_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.FISH_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.HELIX_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.JAW_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.PLUME_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.ROOT_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.SAIL_FOSSIL, "natural/fossils/");
        createItem(GenerationsItems.SKULL_FOSSIL, "natural/fossils/");

        GenerationsArmor.ARMOR.forEach(armor -> createItem(armor, "armor/"));
        GenerationsTools.TOOLS.forEach(this::handheldItem);

        createItem(GenerationsItems.MARK_CHARM, "player_items/");
        createItem(GenerationsItems.CATCHING_CHARM, "player_items/");
        createItem(GenerationsItems.EXP_CHARM, "player_items/");
        createItem(GenerationsItems.OLD_ROD, "player_items/");
        createItem(GenerationsItems.GOOD_ROD, "player_items/");
        createItem(GenerationsItems.SUPER_ROD, "player_items/");
        createItem(GenerationsItems.RUBY_ROD, "player_items/");
        createItem(GenerationsItems.CAMERA, "player_items/");
        createItem(GenerationsItems.SNAP_CAMERA, "player_items/");
        createItem(GenerationsItems.FILM, "player_items/");
        createItem(GenerationsItems.REPEL, "player_items/");
        createItem(GenerationsItems.SUPER_REPEL, "player_items/");
        createItem(GenerationsItems.MAX_REPEL, "player_items/");
        createItem(GenerationsItems.WAILMER_PAIL, "player_items/");
        createItem(GenerationsItems.SPRINK_LOTAD, "player_items/");
        /*
        createItem(GenerationsItems.RED_BIKE, "player_items/");
        createItem(GenerationsItems.ORANGE_BIKE, "player_items/");
        createItem(GenerationsItems.YELLOW_BIKE, "player_items/");
        createItem(GenerationsItems.GREEN_BIKE, "player_items/");
        createItem(GenerationsItems.BLUE_BIKE, "player_items/");
        createItem(GenerationsItems.PURPLE_BIKE, "player_items/");

         */
        createItem(GenerationsItems.ROTOM_CATALOG, "player_items/");
        createItem(GenerationsItems.POKEDEX, "player_items/");
        createItem(GenerationsItems.ITEM_FINDER, "player_items/");
        createItem(GenerationsItems.LURE_MODULE, "player_items/");
        createItem(GenerationsItems.BOTTLE_CAP, "player_items/");
        createItem(GenerationsItems.GOLD_BOTTLE_CAP, "player_items/");
        createItem(GenerationsItems.ABILITY_CAPSULE, "player_items/");
        createItem(GenerationsItems.ABILITY_PATCH, "player_items/");
        createItem(GenerationsItems.RANCH_UPGRADE, "player_items/");
        createItem(GenerationsItems.CORRUPTED_GEM, "player_items/");
        createItem(GenerationsItems.WISHING_STAR, "player_items/");
        createItem(GenerationsItems.UNCHARGED_DYNAMAX_BAND, "player_items/");

        createItem(GenerationsItems.ORB, "legend_items/");
        createItem(GenerationsItems.UNO_ORB, "legend_items/");
        createItem(GenerationsItems.DOS_ORB, "legend_items/");
        createItem(GenerationsItems.TRES_ORB, "legend_items/");
        createItem(GenerationsItems.MYSTICAL_ORB, "legend_items/");
        createItem(GenerationsItems.MARTIAL_ORB, "legend_items/");
        createItem(GenerationsItems.MALEVOLENT_ORB, "legend_items/");
        createItem(GenerationsItems.GENERATIONS_ORB, "legend_items/");
        createItem(GenerationsItems.ADAMANT_ORB, "legend_items/");
        createItem(GenerationsItems.GRISEOUS_ORB, "legend_items/");
        createItem(GenerationsItems.LUSTROUS_ORB, "legend_items/");
        createItem(GenerationsItems.SHATTERED_ICE_KEY_1, "legend_items/");
        createItem(GenerationsItems.SHATTERED_ICE_KEY_2, "legend_items/");
        createItem(GenerationsItems.SHATTERED_ICE_KEY_3, "legend_items/");
        createItem(GenerationsItems.SHATTERED_ICE_KEY_4, "legend_items/");
        createItem(GenerationsItems.ICEBERG_KEY, "legend_items/");
        createItem(GenerationsItems.CRUMBLED_ROCK_KEY_1, "legend_items/");
        createItem(GenerationsItems.CRUMBLED_ROCK_KEY_2, "legend_items/");
        createItem(GenerationsItems.CRUMBLED_ROCK_KEY_3, "legend_items/");
        createItem(GenerationsItems.CRUMBLED_ROCK_KEY_4, "legend_items/");
        createItem(GenerationsItems.ROCK_PEAK_KEY, "legend_items/");
        createItem(GenerationsItems.RUSTY_IRON_KEY_1, "legend_items/");
        createItem(GenerationsItems.RUSTY_IRON_KEY_2, "legend_items/");
        createItem(GenerationsItems.RUSTY_IRON_KEY_3, "legend_items/");
        createItem(GenerationsItems.RUSTY_IRON_KEY_4, "legend_items/");
        createItem(GenerationsItems.IRON_KEY, "legend_items/");
        createItem(GenerationsItems.FRAGMENTED_DRAGO_KEY_1, "legend_items/");
        createItem(GenerationsItems.FRAGMENTED_DRAGO_KEY_2, "legend_items/");
        createItem(GenerationsItems.FRAGMENTED_DRAGO_KEY_3, "legend_items/");
        createItem(GenerationsItems.FRAGMENTED_DRAGO_KEY_4, "legend_items/");
        createItem(GenerationsItems.DRAGO_KEY, "legend_items/");
        createItem(GenerationsItems.DISCHARGED_ELEKI_KEY_1, "legend_items/");
        createItem(GenerationsItems.DISCHARGED_ELEKI_KEY_2, "legend_items/");
        createItem(GenerationsItems.DISCHARGED_ELEKI_KEY_3, "legend_items/");
        createItem(GenerationsItems.DISCHARGED_ELEKI_KEY_4, "legend_items/");
        createItem(GenerationsItems.ELEKI_KEY, "legend_items/");
        createItem(GenerationsItems.SHATTERED_RELIC_SONG_1, "legend_items/");
        createItem(GenerationsItems.SHATTERED_RELIC_SONG_2, "legend_items/");
        createItem(GenerationsItems.SHATTERED_RELIC_SONG_3, "legend_items/");
        createItem(GenerationsItems.SHATTERED_RELIC_SONG_4, "legend_items/");
        createItem(GenerationsItems.RELIC_SONG, "legend_items/");
        createItem(GenerationsItems.RED_CHAIN, "legend_items/");
        createItem(GenerationsItems.RED_CHAIN_SHARD, "legend_items/");
        createItem(GenerationsItems.DNA_SPLICERS, "legend_items/");
        createItem(GenerationsItems.REINS_OF_UNITY, "legend_items/");
        createItem(GenerationsItems.N_SOLARIZER, "legend_items/");
        createItem(GenerationsItems.N_LUNARIZER, "legend_items/");
        createItem(GenerationsItems.LEGEND_FINDER, "legend_items/");
        createItem(GenerationsItems.HOOPA_RING, "legend_items/");
        createItem(GenerationsItems.FADED_RED_ORB, "legend_items/");
        createItem(GenerationsItems.RED_ORB, "legend_items/");
        createItem(GenerationsItems.FADED_BLUE_ORB, "legend_items/");
        createItem(GenerationsItems.BLUE_ORB, "legend_items/");
        createItem(GenerationsItems.JADE_ORB, "legend_items/");
        createItem(GenerationsItems.LIGHT_STONE, "legend_items/");
        createItem(GenerationsItems.DARK_STONE, "legend_items/");
        createItem(GenerationsItems.DRAGON_STONE, "legend_items/");
        createItem(GenerationsItems.RAINBOW_WING, "legend_items/");
        createItem(GenerationsItems.DARK_SOUL, "legend_items/");
        createItem(GenerationsItems.DRAGON_SOUL, "legend_items/");
//        createItem(GenerationsItems.MELODY_FLUTE, "legend_items/");
        createItem(GenerationsItems.SPARKLING_SHARD, "legend_items/");
        createItem(GenerationsItems.SPARKLING_STONE, "legend_items/");
        createItem(GenerationsItems.RUSTY_FRAGMENT, "legend_items/");
        createItem(GenerationsItems.RUSTY_SWORD, "legend_items/");
        createItem(GenerationsItems.CROWNED_SWORD, "legend_items/");
        createItem(GenerationsItems.RUSTY_SHIELD, "legend_items/");
        createItem(GenerationsItems.CROWNED_SHIELD, "legend_items/");
        createItem(GenerationsItems.SCROLL_PAGE, "legend_items/");
        createItem(GenerationsItems.SECRET_ARMOR_SCROLL, "legend_items/");
        createItem(GenerationsItems.ZYGARDE_CUBE, "legend_items/");
        createItem(GenerationsItems.MELTAN_BOX, "legend_items/");
        createItem(GenerationsItems.TIME_GLASS, "legend_items/");
        createItem(GenerationsItems.MOON_FLUTE, "legend_items/");
        createItem(GenerationsItems.SUN_FLUTE, "legend_items/");
        createItem(GenerationsItems.LAVA_CRYSTAL, "legend_items/");
        createItem(GenerationsItems.MAGMA_CRYSTAL, "legend_items/");
        createItem(GenerationsItems.JEWEL_OF_LIFE, "legend_items/");
        createItem(GenerationsItems.PRISON_BOTTLE_STEM, "legend_items/");
        createItem(GenerationsItems.PRISON_BOTTLE, "legend_items/");
        createItem(GenerationsItems.MIRROR, "legend_items/");
        createItem(GenerationsItems.DARK_CRYSTAL, "legend_items/");
        createItem(GenerationsItems.ICEROOT_CARROT, "legend_items/");
        createItem(GenerationsItems.SHADEROOT_CARROT, "legend_items/");
        createItem(GenerationsItems.ICY_WING, "legend_items/");
        createItem(GenerationsItems.ELEGANT_WING, "legend_items/");
        createItem(GenerationsItems.STATIC_WING, "legend_items/");
        createItem(GenerationsItems.BELLIGERENT_WING, "legend_items/");
        createItem(GenerationsItems.FIERY_WING, "legend_items/");
        createItem(GenerationsItems.SINISTER_WING, "legend_items/");
        createItem(GenerationsItems.REGIELEKI_ORB, "legend_items/");
        createItem(GenerationsItems.REGIDRAGO_ORB, "legend_items/");
        createItem(GenerationsItems.REGIROCK_ORB, "legend_items/");
        createItem(GenerationsItems.REGISTEEL_ORB, "legend_items/");
        createItem(GenerationsItems.REGICE_ORB, "legend_items/");
        createItem(GenerationsItems.SHARD_OF_WILLPOWER, "legend_items/");
        createItem(GenerationsItems.SHARD_OF_EMOTION, "legend_items/");
        createItem(GenerationsItems.SHARD_OF_KNOWLEDGE, "legend_items/");
        createItem(GenerationsItems.CRYSTAL_OF_WILLPOWER, "legend_items/");
        createItem(GenerationsItems.CRYSTAL_OF_EMOTION, "legend_items/");
        createItem(GenerationsItems.CRYSTAL_OF_KNOWLEDGE, "legend_items/");

        createItem(GenerationsItems.BIKE_FRAME, "utility_items/");
        createItem(GenerationsItems.BIKE_HANDLEBARS, "utility_items/");
        createItem(GenerationsItems.BIKE_SEAT, "utility_items/");
        createItem(GenerationsItems.BIKE_WHEEL, "utility_items/");
        createItem(GenerationsItems.TRADE_MONITOR, "utility_items/");
        createItem(GenerationsItems.TRADE_HOLDER_RIGHT, "utility_items/");
        createItem(GenerationsItems.TRADE_HOLDER_LEFT, "utility_items/");
        createItem(GenerationsItems.TRADE_PANEL, "utility_items/");
        createItem(GenerationsItems.GREEN_CLONER_TANK, "utility_items/");
        createItem(GenerationsItems.ORANGE_CLONER_TANK, "utility_items/");
        createItem(GenerationsItems.CLONER_CORD, "utility_items/");
        createItem(GenerationsItems.HIDDEN_IRON_DOOR, "utility_items/");
        createItem(GenerationsItems.HIDDEN_WOODEN_DOOR, "utility_items/");
        createItem(GenerationsItems.HIDDEN_LEVER, "utility_items/");
        createItem(GenerationsItems.HIDDEN_PRESSURE_PLATE, "utility_items/");
        createItem(GenerationsItems.HIDDEN_CUBE, "utility_items/");
        createItem(GenerationsItems.CHISEL, "utility_items/");
        createItem(GenerationsItems.GIFT_BOX, "utility_items/");
        createItem(GenerationsItems.POKEMON_EDITOR, "utility_items/");
        createItem(GenerationsItems.ZONE_WAND, "utility_items/");
        createItem(GenerationsItems.GROTTO_SPAWNER, "utility_items/");

        createItem(GenerationsItems.METEORITE, "form_items/");
        createItem(GenerationsItems.GRACIDEA, "form_items/");
        createItem(GenerationsItems.REVEAL_GLASS, "form_items/");
        createItem(GenerationsItems.ROCKSTAR_COSTUME, "form_items/");
        createItem(GenerationsItems.BELLE_COSTUME, "form_items/");
        createItem(GenerationsItems.POPSTAR_COSTUME, "form_items/");
        createItem(GenerationsItems.PHD_COSTUME, "form_items/");
        createItem(GenerationsItems.LIBRE_COSTUME, "form_items/");
        createItem(GenerationsItems.MEWTWO_ARMOR, "form_items/");
        createItem(GenerationsItems.PINK_NECTAR, "form_items/");
        createItem(GenerationsItems.PURPLE_NECTAR, "form_items/");
        createItem(GenerationsItems.RED_NECTAR, "form_items/");
        createItem(GenerationsItems.YELLOW_NECTAR, "form_items/");

        createItem(GenerationsItems.BACHS_FOOD_TIN, "curry/ingredients/");
        createItem(GenerationsItems.BOBS_FOOD_TIN, "curry/ingredients/");
        createItem(GenerationsItems.BOILED_EGG, "curry/ingredients/");
        createItem(GenerationsItems.BREAD, "curry/ingredients/");
        createItem(GenerationsItems.BRITTLE_BONES, "curry/ingredients/");
        createItem(GenerationsItems.COCONUT_MILK, "curry/ingredients/");
        createItem(GenerationsItems.FANCY_APPLE, "curry/ingredients/");
        createItem(GenerationsItems.FRESH_CREAM, "curry/ingredients/");
        createItem(GenerationsItems.FRIED_FOOD, "curry/ingredients/");
        createItem(GenerationsItems.FRUIT_BUNCH, "curry/ingredients/");
        createItem(GenerationsItems.INSTANT_NOODLES, "curry/ingredients/");
        createItem(GenerationsItems.LARGE_LEEK, "curry/ingredients/");
        createItem(GenerationsItems.MIXED_MUSHROOMS, "curry/ingredients/");
        createItem(GenerationsItems.MOOMOO_CHEESE, "curry/ingredients/");
        createItem(GenerationsItems.PACK_OF_POTATOES, "curry/ingredients/");
        createItem(GenerationsItems.PACKAGED_CURRY, "curry/ingredients/");
        createItem(GenerationsItems.PASTA, "curry/ingredients/");
        createItem(GenerationsItems.PRECOOKED_BURGER, "curry/ingredients/");
        createItem(GenerationsItems.PUNGENT_ROOT, "curry/ingredients/");
        createItem(GenerationsItems.SALAD_MIX, "curry/ingredients/");
        createItem(GenerationsItems.SAUSAGES, "curry/ingredients/");
        createItem(GenerationsItems.SMOKED_POKE_TAIL, "curry/ingredients/");
        createItem(GenerationsItems.SPICE_MIX, "curry/ingredients/");
        createItem(GenerationsItems.TIN_OF_BEANS, "curry/ingredients/");
        createItem(GenerationsItems.GIGANTAMIX, "curry/ingredients/");


        createItem(GenerationsItems.POKEMAIL_AIR, "mail/");
        createItem(GenerationsItems.POKEMAIL_AIR_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BLOOM, "mail/");
        createItem(GenerationsItems.POKEMAIL_BLOOM_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRICK, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRICK_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_D, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_D_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_M, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_M_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_S, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_S_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_T, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_T_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_V, "mail/");
        createItem(GenerationsItems.POKEMAIL_BRIDGE_V_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_BUBBLE, "mail/");
        createItem(GenerationsItems.POKEMAIL_BUBBLE_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_DREAM, "mail/");
        createItem(GenerationsItems.POKEMAIL_DREAM_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_FAB, "mail/");
        createItem(GenerationsItems.POKEMAIL_FAB_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_FAVORED, "mail/");
        createItem(GenerationsItems.POKEMAIL_FAVORED_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_FLAME, "mail/");
        createItem(GenerationsItems.POKEMAIL_FLAME_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_GLITTER, "mail/");
        createItem(GenerationsItems.POKEMAIL_GLITTER_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_GRASS, "mail/");
        createItem(GenerationsItems.POKEMAIL_GRASS_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_GREET, "mail/");
        createItem(GenerationsItems.POKEMAIL_GREET_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_HARBOR, "mail/");
        createItem(GenerationsItems.POKEMAIL_HARBOR_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_HEART, "mail/");
        createItem(GenerationsItems.POKEMAIL_HEART_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_INQUIRY, "mail/");
        createItem(GenerationsItems.POKEMAIL_INQUIRY_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_LIKE, "mail/");
        createItem(GenerationsItems.POKEMAIL_LIKE_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_MECH, "mail/");
        createItem(GenerationsItems.POKEMAIL_MECH_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_MOSAIC, "mail/");
        createItem(GenerationsItems.POKEMAIL_MOSAIC_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_ORANGE, "mail/");
        createItem(GenerationsItems.POKEMAIL_ORANGE_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_REPLY, "mail/");
        createItem(GenerationsItems.POKEMAIL_REPLY_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_RETRO, "mail/");
        createItem(GenerationsItems.POKEMAIL_RETRO_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_RSVP, "mail/");
        createItem(GenerationsItems.POKEMAIL_RSVP_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_SHADOW, "mail/");
        createItem(GenerationsItems.POKEMAIL_SHADOW_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_SNOW, "mail/");
        createItem(GenerationsItems.POKEMAIL_SNOW_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_SPACE, "mail/");
        createItem(GenerationsItems.POKEMAIL_SPACE_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_STEEL, "mail/");
        createItem(GenerationsItems.POKEMAIL_STEEL_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_THANKS, "mail/");
        createItem(GenerationsItems.POKEMAIL_THANKS_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_TROPIC, "mail/");
        createItem(GenerationsItems.POKEMAIL_TROPIC_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_TUNNEL, "mail/");
        createItem(GenerationsItems.POKEMAIL_TUNNEL_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_WAVE, "mail/");
        createItem(GenerationsItems.POKEMAIL_WAVE_CLOSED, "mail/");
        createItem(GenerationsItems.POKEMAIL_WOOD, "mail/");
        createItem(GenerationsItems.POKEMAIL_WOOD_CLOSED, "mail/");

        createItem(GenerationsItems.ABILITY_URGE, "unimplemented/");
        createItem(GenerationsItems.ADVENTURE_GUIDE, "unimplemented/");
        createItem(GenerationsItems.APRICORN_BOX, "unimplemented/");
        createItem(GenerationsItems.AQUA_SUIT, "unimplemented/");
        createItem(GenerationsItems.ARMOR_PASS, "unimplemented/");
        createItem(GenerationsItems.ARMORITE_ORE, "unimplemented/");
        createItem(GenerationsItems.AURORA_TICKET, "unimplemented/");
        createItem(GenerationsItems.AUTOGRAPH, "unimplemented/");
        createItem(GenerationsItems.AZURE_FLUTE, "unimplemented/");
        createItem(GenerationsItems.BAND_AUTOGRAPH, "unimplemented/");
        createItem(GenerationsItems.BASEMENT_KEY_1, "unimplemented/");
        createItem(GenerationsItems.BASEMENT_KEY_2, "unimplemented/");
        createItem(GenerationsItems.BERRY_PLANTER, "unimplemented/");
        createItem(GenerationsItems.BERRY_POUCH, "unimplemented/");
        createItem(GenerationsItems.BIKE_VOUCHER, "unimplemented/");
        createItem(GenerationsItems.BLACK_MANE_HAIR, "unimplemented/");
        createItem(GenerationsItems.BLUE_CARD, "unimplemented/");
        createItem(GenerationsItems.BLUE_PETAL, "unimplemented/");
        createItem(GenerationsItems.BLUE_SCARF, "unimplemented/");
        createItem(GenerationsItems.BLUE_SPHERE, "unimplemented/");
        createItem(GenerationsItems.CAMPING_GEAR, "unimplemented/");
        createItem(GenerationsItems.CARD_KEY_1, "unimplemented/");
        createItem(GenerationsItems.CARD_KEY_2, "unimplemented/");
        createItem(GenerationsItems.CARROT_SEEDS, "unimplemented/");
        createItem(GenerationsItems.CLEAR_BELL, "unimplemented/");
        createItem(GenerationsItems.COIN, "unimplemented/");
        createItem(GenerationsItems.COIN_CASE, "unimplemented/");
        createItem(GenerationsItems.COLRESS_MACHINE, "unimplemented/");
        createItem(GenerationsItems.COMMON_STONE, "unimplemented/");
        createItem(GenerationsItems.CONTEST_COSTUME_1, "unimplemented/");
        createItem(GenerationsItems.CONTEST_COSTUME_2, "unimplemented/");
        createItem(GenerationsItems.CONTEST_PASS, "unimplemented/");
        createItem(GenerationsItems.COURAGE_CANDY, "unimplemented/");
        createItem(GenerationsItems.COURAGE_CANDY_L, "unimplemented/");
        createItem(GenerationsItems.COURAGE_CANDY_XL, "unimplemented/");
        createItem(GenerationsItems.COUPON_1, "unimplemented/");
        createItem(GenerationsItems.COUPON_2, "unimplemented/");
        createItem(GenerationsItems.COUPON_3, "unimplemented/");
        createItem(GenerationsItems.CROWN_PASS, "unimplemented/");
        createItem(GenerationsItems.DATA_CARDS, "unimplemented/");
        createItem(GenerationsItems.DEVON_PARTS, "unimplemented/");
        createItem(GenerationsItems.DEVON_SCOPE, "unimplemented/");
        createItem(GenerationsItems.DEVON_SCUBA_GEAR, "unimplemented/");
        createItem(GenerationsItems.DIRE_HIT_2, "unimplemented/");
        createItem(GenerationsItems.DIRE_HIT_3, "unimplemented/");
        createItem(GenerationsItems.DISCOUNT_COUPON, "unimplemented/");
        createItem(GenerationsItems.DOWSING_MACHINE_1, "unimplemented/");
        createItem(GenerationsItems.DOWSING_MACHINE_2, "unimplemented/");
        createItem(GenerationsItems.DOWSING_MCHN, "unimplemented/");
        createItem(GenerationsItems.DRAGON_SKULL, "unimplemented/");
        createItem(GenerationsItems.DROPPED_ITEM_RED, "unimplemented/");
        createItem(GenerationsItems.DROPPED_ITEM_YELLOW, "unimplemented/");
        createItem(GenerationsItems.DYNITE_ORE, "unimplemented/");
        createItem(GenerationsItems.ELEVATOR_KEY, "unimplemented/");
        createItem(GenerationsItems.ENDORSEMENT, "unimplemented/");
        createItem(GenerationsItems.ENIGMA_STONE, "unimplemented/");
        createItem(GenerationsItems.EON_FLUTE, "unimplemented/");
        createItem(GenerationsItems.EON_TICKET, "unimplemented/");
        createItem(GenerationsItems.EXPLORER_KIT, "unimplemented/");
        createItem(GenerationsItems.FAME_CHECKER, "unimplemented/");
        createItem(GenerationsItems.FASHION_CASE, "unimplemented/");
        createItem(GenerationsItems.FESTIVAL_TICKET, "unimplemented/");
        createItem(GenerationsItems.FORAGE_BAG, "unimplemented/");
        createItem(GenerationsItems.GALACTIC_KEY, "unimplemented/");
        createItem(GenerationsItems.GB_SOUNDS, "unimplemented/");
        createItem(GenerationsItems.GO_GOGGLES, "unimplemented/");
        createItem(GenerationsItems.GOLD_TEETH, "unimplemented/");
        createItem(GenerationsItems.GOLDEN_NANAB_BERRY, "unimplemented/");
        createItem(GenerationsItems.GOLDEN_PINAP_BERRY, "unimplemented/");
        createItem(GenerationsItems.GOLDEN_RAZZ_BERRY, "unimplemented/");
        createItem(GenerationsItems.GRAM, "unimplemented/");
        createItem(GenerationsItems.GREEN_PETAL, "unimplemented/");
        createItem(GenerationsItems.GREEN_SCARF, "unimplemented/");
        createItem(GenerationsItems.GREEN_SPHERE, "unimplemented/");
        createItem(GenerationsItems.GREEN_TEA, "unimplemented/");
        createItem(GenerationsItems.GRUBBY_HANKY, "unimplemented/");
        createItem(GenerationsItems.HEALTH_CANDY, "unimplemented/");
        createItem(GenerationsItems.HEALTH_CANDY_L, "unimplemented/");
        createItem(GenerationsItems.HEALTH_CANDY_XL, "unimplemented/");
        createItem(GenerationsItems.HI_TECH_EARBUDS, "unimplemented/");
        createItem(GenerationsItems.HOLO_CASTER_1, "unimplemented/");
        createItem(GenerationsItems.HOLO_CASTER_2, "unimplemented/");
        createItem(GenerationsItems.HONOR_OF_KALOS, "unimplemented/");
        createItem(GenerationsItems.INTRIGUING_STONE, "unimplemented/");
        createItem(GenerationsItems.ITEM_DROP, "unimplemented/");
        createItem(GenerationsItems.ITEM_URGE, "unimplemented/");
        createItem(GenerationsItems.JOURNAL, "unimplemented/");
        createItem(GenerationsItems.KEY_STONE_1, "unimplemented/");
        createItem(GenerationsItems.KEY_STONE_2, "unimplemented/");
        createItem(GenerationsItems.KEY_TO_ROOM_1, "unimplemented/");
        createItem(GenerationsItems.KEY_TO_ROOM_2, "unimplemented/");
        createItem(GenerationsItems.KEY_TO_ROOM_4, "unimplemented/");
        createItem(GenerationsItems.KEY_TO_ROOM_6, "unimplemented/");
        createItem(GenerationsItems.LEAF_LETTER, "unimplemented/");
        createItem(GenerationsItems.LEGENDARY_CLUE, "unimplemented/");
        createItem(GenerationsItems.LENS_CASE, "unimplemented/");
        createItem(GenerationsItems.LETTER, "unimplemented/");
        createItem(GenerationsItems.LIBERTY_PASS, "unimplemented/");
        createItem(GenerationsItems.LIFT_KEY, "unimplemented/");
        createItem(GenerationsItems.LOCK_CAPSULE_1, "unimplemented/");
        createItem(GenerationsItems.LOCK_CAPSULE_2, "unimplemented/");
        createItem(GenerationsItems.LOOKER_TICKET, "unimplemented/");
        createItem(GenerationsItems.LOOT_SACK, "unimplemented/");
        createItem(GenerationsItems.LOST_ITEM_1, "unimplemented/");
        createItem(GenerationsItems.LOST_ITEM_2, "unimplemented/");
        createItem(GenerationsItems.LUNAR_FEATHER, "unimplemented/");
        createItem(GenerationsItems.LURE, "unimplemented/");
        createItem(GenerationsItems.MACHINE_PART, "unimplemented/");
        createItem(GenerationsItems.MAGMA_EMBLEM, "unimplemented/");
        createItem(GenerationsItems.MAGMA_SUIT, "unimplemented/");
        createItem(GenerationsItems.MAKEUP_BAG, "unimplemented/");
        createItem(GenerationsItems.MAX_LURE, "unimplemented/");
        createItem(GenerationsItems.MEDAL_BOX, "unimplemented/");
        createItem(GenerationsItems.MEGA_CHARM, "unimplemented/");
        createItem(GenerationsItems.MEGA_CUFF, "unimplemented/");
        createItem(GenerationsItems.MEGA_RING, "unimplemented/");
        createItem(GenerationsItems.MEMBER_CARD, "unimplemented/");
        createItem(GenerationsItems.METEORITE_SHARD, "unimplemented/");
        createItem(GenerationsItems.MIGHTY_CANDY, "unimplemented/");
        createItem(GenerationsItems.MIGHTY_CANDY_L, "unimplemented/");
        createItem(GenerationsItems.MIGHTY_CANDY_XL, "unimplemented/");
        createItem(GenerationsItems.MYSTIC_TICKET, "unimplemented/");
        createItem(GenerationsItems.OAKS_LETTER, "unimplemented/");
        createItem(GenerationsItems.OAKS_PARCEL, "unimplemented/");
        createItem(GenerationsItems.OLD_CHARM, "unimplemented/");
        createItem(GenerationsItems.OLD_LETTER, "unimplemented/");
        createItem(GenerationsItems.OLD_SEA_MAP, "unimplemented/");
        createItem(GenerationsItems.ORANGE_PETAL, "unimplemented/");
        createItem(GenerationsItems.PAIR_OF_TICKETS, "unimplemented/");
        createItem(GenerationsItems.PAL_PAD, "unimplemented/");
        createItem(GenerationsItems.PALE_SPHERE, "unimplemented/");
        createItem(GenerationsItems.PASS, "unimplemented/");
        createItem(GenerationsItems.PASS_ORB, "unimplemented/");
        createItem(GenerationsItems.PERMIT, "unimplemented/");
        createItem(GenerationsItems.PEWTER_CRUNCHIES, "unimplemented/");
        createItem(GenerationsItems.PINK_PETAL, "unimplemented/");
        createItem(GenerationsItems.PINK_SCARF, "unimplemented/");
        createItem(GenerationsItems.PLASMA_CARD, "unimplemented/");
        createItem(GenerationsItems.POFFIN, "unimplemented/");
        createItem(GenerationsItems.POFFIN_CASE, "unimplemented/");
        createItem(GenerationsItems.POINT_CARD, "unimplemented/");
        createItem(GenerationsItems.POKE_FLUTE, "unimplemented/");
        createItem(GenerationsItems.POKE_RADAR, "unimplemented/");
        createItem(GenerationsItems.POKEBLOCK_CASE, "unimplemented/");
        createItem(GenerationsItems.POKEBLOCK_KIT, "unimplemented/");
        createItem(GenerationsItems.POKEMON_BOX_LINK, "unimplemented/");
        createItem(GenerationsItems.POKETCH_BLUE, "unimplemented/");
        createItem(GenerationsItems.POKETCH_RED, "unimplemented/");
        createItem(GenerationsItems.POWDER_JAR, "unimplemented/");
        createItem(GenerationsItems.POWER_PLANT_PASS, "unimplemented/");
        createItem(GenerationsItems.PRISM_SPHERE, "unimplemented/");
        createItem(GenerationsItems.PROFESSORS_MASK, "unimplemented/");
        createItem(GenerationsItems.PROFS_LETTER, "unimplemented/");
        createItem(GenerationsItems.PROP_CASE, "unimplemented/");
        createItem(GenerationsItems.PURPLE_PETAL, "unimplemented/");
        createItem(GenerationsItems.QUICK_CANDY, "unimplemented/");
        createItem(GenerationsItems.QUICK_CANDY_L, "unimplemented/");
        createItem(GenerationsItems.QUICK_CANDY_XL, "unimplemented/");
        createItem(GenerationsItems.RADIANT_PETAL, "unimplemented/");
        createItem(GenerationsItems.RAINBOW_FLOWER, "unimplemented/");
        createItem(GenerationsItems.RAINBOW_PASS, "unimplemented/");
        createItem(GenerationsItems.RED_PETAL, "unimplemented/");
        createItem(GenerationsItems.RED_SCALE, "unimplemented/");
        createItem(GenerationsItems.RED_SPHERE, "unimplemented/");
        createItem(GenerationsItems.RESET_URGE, "unimplemented/");
        createItem(GenerationsItems.RIDE_PAGER, "unimplemented/");
        createItem(GenerationsItems.ROLLER_SKATES, "unimplemented/");
        createItem(GenerationsItems.ROTO_BARGAIN, "unimplemented/");
        createItem(GenerationsItems.ROTO_BOOST, "unimplemented/");
        createItem(GenerationsItems.ROTO_CATCH, "unimplemented/");
        createItem(GenerationsItems.ROTO_ENCOUNTER, "unimplemented/");
        createItem(GenerationsItems.ROTO_EXP_POINTS, "unimplemented/");
        createItem(GenerationsItems.ROTO_FRIENDSHIP, "unimplemented/");
        createItem(GenerationsItems.ROTO_HATCH, "unimplemented/");
        createItem(GenerationsItems.ROTO_HP_RESTORE, "unimplemented/");
        createItem(GenerationsItems.ROTO_PP_RESTORE, "unimplemented/");
        createItem(GenerationsItems.ROTO_PRIZE_MONEY, "unimplemented/");
        createItem(GenerationsItems.ROTO_STEALTH, "unimplemented/");
        createItem(GenerationsItems.RULE_BOOK, "unimplemented/");
        createItem(GenerationsItems.SACRED_ASH, "unimplemented/");
        createItem(GenerationsItems.SCANNER, "unimplemented/");
        createItem(GenerationsItems.SEAL_BAG, "unimplemented/");
        createItem(GenerationsItems.SEAL_CASE, "unimplemented/");
        createItem(GenerationsItems.SECRET_KEY_1, "unimplemented/");
        createItem(GenerationsItems.SECRET_KEY_2, "unimplemented/");
        createItem(GenerationsItems.SECRET_MEDICINE, "unimplemented/");
        createItem(GenerationsItems.SILPH_SCOPE, "unimplemented/");
        createItem(GenerationsItems.SILVER_NANAB_BERRY, "unimplemented/");
        createItem(GenerationsItems.SILVER_PINAP_BERRY, "unimplemented/");
        createItem(GenerationsItems.SILVER_RAZZ_BERRY, "unimplemented/");
        createItem(GenerationsItems.SILVER_WING, "unimplemented/");
        createItem(GenerationsItems.SINNOH_STONE, "unimplemented/");
        createItem(GenerationsItems.SMART_CANDY, "unimplemented/");
        createItem(GenerationsItems.SMART_CANDY_L, "unimplemented/");
        createItem(GenerationsItems.SMART_CANDY_XL, "unimplemented/");
        createItem(GenerationsItems.SONIAS_BOOK, "unimplemented/");
        createItem(GenerationsItems.SOOT_SACK, "unimplemented/");
        createItem(GenerationsItems.SPARKLING_STONE_1, "unimplemented/");
        createItem(GenerationsItems.SPARKLING_STONE_2, "unimplemented/");
        createItem(GenerationsItems.SPRAYDUCK, "unimplemented/");
        createItem(GenerationsItems.SQUIRT_BOTTLE, "unimplemented/");
        createItem(GenerationsItems.SS_TICKET, "unimplemented/");
        createItem(GenerationsItems.STORAGE_KEY_1, "unimplemented/");
        createItem(GenerationsItems.STORAGE_KEY_2, "unimplemented/");
        createItem(GenerationsItems.STYLE_CARD, "unimplemented/");
        createItem(GenerationsItems.SUITE_KEY, "unimplemented/");
        createItem(GenerationsItems.SUPER_LURE, "unimplemented/");
        createItem(GenerationsItems.SURGE_BADGE, "unimplemented/");
        createItem(GenerationsItems.TEACHY_TV, "unimplemented/");
        createItem(GenerationsItems.TIDAL_BELL, "unimplemented/");
        createItem(GenerationsItems.TM_CASE, "unimplemented/");
        createItem(GenerationsItems.TM_MATERIAL, "unimplemented/");
        createItem(GenerationsItems.TMV_PASS, "unimplemented/");
        createItem(GenerationsItems.TOTEM_STICKER, "unimplemented/");
        createItem(GenerationsItems.TOUGH_CANDY, "unimplemented/");
        createItem(GenerationsItems.TOUGH_CANDY_L, "unimplemented/");
        createItem(GenerationsItems.TOUGH_CANDY_XL, "unimplemented/");
        createItem(GenerationsItems.TOWN_MAP_1, "unimplemented/");
        createItem(GenerationsItems.TOWN_MAP_2, "unimplemented/");
        createItem(GenerationsItems.TOWN_MAP_3, "unimplemented/");
        createItem(GenerationsItems.TRAVEL_TRUNK_1, "unimplemented/");
        createItem(GenerationsItems.TRAVEL_TRUNK_2, "unimplemented/");
        createItem(GenerationsItems.TRI_PASS, "unimplemented/");
        createItem(GenerationsItems.UNOVA_STONE, "unimplemented/");
        createItem(GenerationsItems.UNOWN_REPORT, "unimplemented/");
        createItem(GenerationsItems.VS_RECORDER, "unimplemented/");
        createItem(GenerationsItems.VS_SEEKER, "unimplemented/");
        createItem(GenerationsItems.WHITE_MANE_HAIR, "unimplemented/");
        createItem(GenerationsItems.WISHING_CHIP, "unimplemented/");
        createItem(GenerationsItems.WISHING_PIECE, "unimplemented/");
        createItem(GenerationsItems.WOODEN_CROWN, "unimplemented/");
        createItem(GenerationsItems.WORKS_KEY, "unimplemented/");
        createItem(GenerationsItems.X_ACCURACY_2, "unimplemented/");
        createItem(GenerationsItems.X_ACCURACY_3, "unimplemented/");
        createItem(GenerationsItems.X_ACCURACY_6, "unimplemented/");
        createItem(GenerationsItems.X_ATTACK_2, "unimplemented/");
        createItem(GenerationsItems.X_ATTACK_3, "unimplemented/");
        createItem(GenerationsItems.X_ATTACK_6, "unimplemented/");
        createItem(GenerationsItems.X_DEFENSE_2, "unimplemented/");
        createItem(GenerationsItems.X_DEFENSE_3, "unimplemented/");
        createItem(GenerationsItems.X_DEFENSE_6, "unimplemented/");
        createItem(GenerationsItems.X_SPECIAL_ATTACK_2, "unimplemented/");
        createItem(GenerationsItems.X_SPECIAL_ATTACK_3, "unimplemented/");
        createItem(GenerationsItems.X_SPECIAL_ATTACK_6, "unimplemented/");
        createItem(GenerationsItems.X_SPECIAL_DEFENSE_2, "unimplemented/");
        createItem(GenerationsItems.X_SPECIAL_DEFENSE_3, "unimplemented/");
        createItem(GenerationsItems.X_SPECIAL_DEFENSE_6, "unimplemented/");
        createItem(GenerationsItems.X_SPEED_2, "unimplemented/");
        createItem(GenerationsItems.X_SPEED_3, "unimplemented/");
        createItem(GenerationsItems.X_SPEED_6, "unimplemented/");
        createItem(GenerationsItems.X_TRANSCEIVER_BLUE, "unimplemented/");
        createItem(GenerationsItems.X_TRANSCEIVER_RED, "unimplemented/");
        createItem(GenerationsItems.X_TRANSCEIVER_YELLOW, "unimplemented/");
        createItem(GenerationsItems.YELLOW_PETAL, "unimplemented/");
        createItem(GenerationsItems.YELLOW_SCARF, "unimplemented/");
        createItem(GenerationsItems.Z_POWER_RING, "unimplemented/");
        createItem(GenerationsItems.Z_RING, "unimplemented/");

        //aluminium
        createItem(GenerationsItems.RAW_ALUMINUM, "rawores/");
        createItem(GenerationsItems.ALUMINUM_NUGGET, "nuggets/");

        createItem(GenerationsItems.GHOST_BOAT_ITEM, "boat/");
        createItem(GenerationsItems.GHOST_CHEST_BOAT_ITEM, "chest_boat/");
        createItem(GenerationsItems.ULTRA_DARK_BOAT_ITEM, "boat/");
        createItem(GenerationsItems.ULTRA_DARK_CHEST_BOAT_ITEM, "chest_boat/");
        createItem(GenerationsItems.ULTRA_JUNGLE_BOAT_ITEM, "boat/");
        createItem(GenerationsItems.ULTRA_JUNGLE_CHEST_BOAT_ITEM, "chest_boat/");

        createCurry();
        createImbuedFlute();

        createItem(GenerationsItems.TUMBLESTONE, "tumblestone/");
        createItem(GenerationsItems.BLACK_TUMBLESTONE, "tumblestone/");
        createItem(GenerationsItems.RARE_TUMBLESTONE, "tumblestone/");
        createItem(GenerationsItems.SKY_TUMBLESTONE, "tumblestone/");

        createItemBlock(GenerationsBlocks.BALLONLEA_BLUE_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.BALLONLEA_GREEN_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.BALLONLEA_PINK_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.BALLONLEA_YELLOW_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.GROUP_BALLONLEA_BLUE_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.GROUP_BALLONLEA_GREEN_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.GROUP_BALLONLEA_PINK_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.GROUP_BALLONLEA_YELLOW_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.TALL_BALLONLEA_BLUE_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.TALL_BALLONLEA_GREEN_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.TALL_BALLONLEA_PINK_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.TALL_BALLONLEA_YELLOW_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.DOUBLE_BALLONLEA_BLUE_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.DOUBLE_BALLONLEA_GREEN_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.DOUBLE_BALLONLEA_PINK_MUSHROOM, "block/");
        createItemBlock(GenerationsBlocks.DOUBLE_BALLONLEA_YELLOW_MUSHROOM, "block/");

        createItemBlock(GenerationsDecorationBlocks.SNORLAX_BEAN_BAG, "item/blocks/bean_bags/");
        createItemBlock(GenerationsDecorationBlocks.HOUSE_LAMP, "item/blocks/decorations/");
        createItemBlock(GenerationsDecorationBlocks.SWITCH, "item/blocks/decorations/");
        createItemBlock(GenerationsDecorationBlocks.LITWICK_CANDLE, "item/blocks/decorations/");
        createItemBlock(GenerationsDecorationBlocks.LITWICK_CANDLES, "item/blocks/decorations/");
        GenerationsDecorationBlocks.UMBRELLA_BLOCKS.forEach(block -> createItemBlockDir(block, "umbrellas"));
        GenerationsDecorationBlocks.POKEDOLL_RUG_BLOCKS.forEach(block -> createItemBlockDir(block, "rugs"));
        GenerationsDecorationBlocks.WATER_FLOAT_BLOCKS.forEach(block -> createItemBlockDir(block, "water_floats"));
        GenerationsDecorationBlocks.PASTEL_BEAN_BAG_BLOCKS.forEach(block -> createItemBlockDir(block, "bean_bags"));
        GenerationsDecorationBlocks.VENDING_MACHINE_BLOCKS.forEach(block -> createItemBlockDir(block, "vending_machines"));

        createItemBlock(GenerationsUtilityBlocks.BOX, "utility_blocks/");
        createItemBlock(GenerationsUtilityBlocks.COOKING_POT, "item/blocks/utility_blocks/");
        GenerationsUtilityBlocks.HEALER_BLOCKS.forEach(block -> createItemBlockDir(block, "utility_blocks/healer"));
        GenerationsUtilityBlocks.PC_BLOCKS.forEach(block -> createItemBlockDir(block, "utility_blocks/pc"));
        GenerationsUtilityBlocks.CLOCK_BLOCKS.forEach(block -> createItemBlockDir(block, "clocks"));
        GenerationsUtilityBlocks.BALL_LOOTS.forEach(block -> createItemBlock(block, "ball_loots/"));
        createItemBlock(GenerationsUtilityBlocks.TRASH_CAN, "item/blocks/utility_blocks/");

        createItemBlock(GenerationsBlocks.POKECENTER_SCARLET_SIGN, "item/blocks/sign/");

        createPointedDripstoneItem(GenerationsBlocks.POINTED_CHARGE_DRIPSTONE, "item/blocks/dripstone/");

        GenerationsShrines.SHRINES.forEach(shrine -> createItemBlock(shrine, "item/blocks/shrines/"));

        createItemBlock(GenerationsBlocks.POKECENTER_DOOR, "item/blocks/doors/");
        createItemBlock(GenerationsWood.ULTRA_JUNGLE_DOOR, "item/blocks/doors/");
        createItemBlock(GenerationsWood.ULTRA_DARK_DOOR, "item/blocks/doors/");
        createItemBlock(GenerationsWood.GHOST_DOOR, "item/blocks/doors/");
        createItem(GenerationsItems.ULTRA_DARK_SIGN, "blocks/sign/");
        createItem(GenerationsItems.ULTRA_DARK_HANGING_SIGN, "blocks/sign/");
        createItem(GenerationsItems.ULTRA_JUNGLE_SIGN, "blocks/sign/");
        createItem(GenerationsItems.ULTRA_JUNGLE_HANGING_SIGN, "blocks/sign/");
        createItem(GenerationsItems.GHOST_SIGN, "blocks/sign/");
        createItem(GenerationsItems.GHOST_HANGING_SIGN, "blocks/sign/");

        createItem(GenerationsItems.MUSIC_DISC_BEAST_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_CHERISH_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_DIVE_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_DREAM_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_DUSK_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_FAST_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_FEATHER, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_FRIEND_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_GREAT_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_GS_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_HEAL_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_HEAVY_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_LEADEN_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_LEVEL_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_LOVE_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_LURE_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_LUXURY_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_MASTER_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_MOON_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_NEST_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_NET_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_OLD_POKEBALL_DISC, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_ORIGIN_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_PARK_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_POKE_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_PREMIER_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_QUICK_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_REPEAT_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_SAFARI_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_SPORT_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_STRANGE_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_TIMER_BALL, "discs/");
        createItem(GenerationsItems.MUSIC_DISC_ULTRA_BALL, "discs/");

        createItem(GenerationsItems.POKE_WALKMON, "utility_items/");
        createItem(GenerationsItems.GREAT_WALKMON, "utility_items/");
        createItem(GenerationsItems.ULTRA_WALKMON, "utility_items/");
        createItem(GenerationsItems.MASTER_WALKMON, "utility_items/");

        createItemBlock(GenerationsDecorationBlocks.EMPTY_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.POKE_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.GREAT_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.ULTRA_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.MASTER_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.CHERISH_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.DIVE_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.DUSK_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.FAST_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.FRIEND_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.GS_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.HEAL_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.HEAVY_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.LEVEL_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.LOVE_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.LURE_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.LUXURY_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.MOON_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.NEST_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.NET_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.PARK_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.PREMIER_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.QUICK_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.REPEAT_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.SAFARI_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.SPORT_BALL_DISPLAY, "item/blocks/ball_displays/");
        createItemBlock(GenerationsDecorationBlocks.TIMER_BALL_DISPLAY, "item/blocks/ball_displays/");
    }

    private void createCurry() {
        ItemModelBuilder model = generated(GenerationsItems.CURRY.getId().getPath(), CurryType.None.getResourceLocation());
        CurryType[] values = CurryType.values();
        for (int i = 0; i < values.length; i++) {
            CurryType type = values[i];
            model.override().model(generated(type.getResourceLocation().getPath(), type.getResourceLocation())).predicate(GenerationsCore.id("curry_type"), i).end();
        }
    }

    private void createImbuedFlute() {
        ItemModelBuilder model = createItem(GenerationsItems.MELODY_FLUTE, "legend_items/");

        BiConsumer<String, Float> consumer = (name, i) -> {
            ItemModelBuilder typeModel = generated("item/flute/" + name + "_flute", GenerationsCore.id("item/flute/" + name + "_flute"));
            model.override().model(typeModel).predicate(GenerationsCore.id("flute_type"), i).end();
        };

        consumer.accept("basic", 0f);
        consumer.accept("icy", 1f);
        consumer.accept("elegant", 2f);
        consumer.accept("static", 3f);
        consumer.accept("belligerent", 4f);
        consumer.accept("fiery", 5f);
        consumer.accept("sinister", 6f);
        consumer.accept("rainbow", 7f);
        consumer.accept("silver", 8f);
    }

    private void createMint(RegistrySupplier<Item> mint, String color) {
        ResourceLocation key = Objects.requireNonNull(ForgeRegistries.ITEMS.getKey(mint.get()), "Tried to create json model for unregistered Item.");
        generated(key.getPath(), GenerationsCore.id(String.format("item/restoration/%s_mint", color)));
    }

    private void createTmMaterial(RegistrySupplier<Item> material) {
        generated(material.getId().getPath(), GenerationsCore.id("item/tms/tm_material"));
    }

    private void createHeldItem(RegistrySupplier<Item> held) {
        this.createHeldItem(held, "");
    }

    private void createHeldItem(RegistrySupplier<Item> held, String directory) {
        createItem(held, "held_items/" + directory);
    }

    public void createPokedoll(RegistrySupplier<Block> block) {
        ResourceLocation key = Objects.requireNonNull(ForgeRegistries.BLOCKS.getKey(block.get()), "Tried to create json model for unregistered Item.");
        ResourceLocation texPath = GenerationsCore.id("item/dolls/" + key.getPath());
        if(key.getPath().startsWith("shiny_"))
            texPath = GenerationsCore.id("item/dolls/shiny/" + key.getPath().replace("shiny_", ""));

        generated(key.getPath(), texPath);
    }

    public void createItemBlock(RegistrySupplier<? extends Block> block, String directory) {
        ResourceLocation key = Objects.requireNonNull(ForgeRegistries.BLOCKS.getKey(block.get()), "Tried to create json model for unregistered Item.");
        generated(key.getPath(), GenerationsCore.id(directory + key.getPath()));
    }

    public void createPointedDripstoneItem(RegistrySupplier<? extends Block> block, String directory) {
        ResourceLocation key = Objects.requireNonNull(ForgeRegistries.BLOCKS.getKey(block.get()), "Tried to create json model for unregistered Item.");
        singleTexture(key.getPath(), mcLoc("item/pointed_dripstone"), "layer0", GenerationsCore.id(directory.concat(key.getPath())));
    }
    public void createItemBlockDir(RegistrySupplier<? extends Item> block, String directory) {
        ResourceLocation key = Objects.requireNonNull(ForgeRegistries.ITEMS.getKey(block.get()), "Tried to create json model for unregistered Item.");
        generated(key.getPath(), GenerationsCore.id("item/blocks/" + directory + "/" + key.getPath()));
    }


    public ItemModelBuilder createItem(RegistrySupplier<Item> item) {
        return this.createItem(item, "");
    }

    public ItemModelBuilder createCurryType(CurryType type) {
        return generated("item/curry/" + type.getSerializedName(), type.getResourceLocation());
    }

    public ItemModelBuilder createItem(RegistrySupplier<? extends Item> item, String directory) {
        try {
            ResourceLocation key = Objects.requireNonNull(ForgeRegistries.ITEMS.getKey(item.get()), "Tried to create json model for unregistered Item.");
            return generated(key.getPath(), GenerationsCore.id("item/" + directory + key.getPath()));
        } catch (Exception e) {
            LOGGER.error(item.getId() + " -> " + directory);
            return null;
        }
    }

    public ItemModelBuilder generated(String name, ResourceLocation model) {
        try {
            return this.singleTexture(name, new ResourceLocation("item/generated"), "layer0", model);
        } catch (Exception e) {
            LOGGER.error(name + " -> " + model);
            return null;
        }
    }

    private <T extends Item> void handheldItem(RegistrySupplier<T> item) {
        withExistingParent(item.getId().getPath(),
                new ResourceLocation("item/handheld")).texture("layer0",
                new ResourceLocation(GenerationsCore.MOD_ID, "item/tools/" + item.getId().getPath()));
    }
}
