package generations.gg.generations.core.generationscore.forge.datagen.generators.loot

import com.cobblemon.mod.common.CobblemonItems
import generations.gg.generations.core.generationscore.common.world.item.GenerationsItems
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.POKE_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.PREMIER_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.QUICK_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.REPEAT_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.SAFARI_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.SPORT_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.STRANGE_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.TIMER_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.ULTRA_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.WING_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.registerBallLootPoolConstant
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.registerBallLootPoolUniform
import net.minecraft.resources.ResourceKey
import net.minecraft.world.item.Items
import net.minecraft.world.level.storage.loot.LootTable
import java.util.function.BiConsumer

object ChestLootDataGenC {
    fun generate(output: BiConsumer<ResourceKey<LootTable>, LootTable.Builder>) {
        registerBallLootPoolUniform(
            output,
            POKE_BALL,
            1f,
            3f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.AGUAV_BERRY,
            CobblemonItems.AIR_BALLOON,
            CobblemonItems.ANTIDOTE,
            CobblemonItems.APICOT_BERRY,
            CobblemonItems.ASPEAR_BERRY,
            CobblemonItems.BABIRI_BERRY,
            GenerationsItems.BACHS_FOOD_TIN,
            GenerationsItems.BOBS_FOOD_TIN,
            GenerationsItems.BOILED_EGG,
            GenerationsItems.BREAD,
            CobblemonItems.BURN_HEAL,
            CobblemonItems.CELL_BATTERY,
            CobblemonItems.CHARTI_BERRY,
            CobblemonItems.CHESTO_BERRY,
            CobblemonItems.CUSTAP_BERRY,
            CobblemonItems.DIRE_HIT,
            CobblemonItems.ELIXIR,
            GenerationsItems.ENERGY_POWDER,
            CobblemonItems.ENERGY_ROOT,
            GenerationsItems.ESCAPE_ROPE,
            CobblemonItems.FLOAT_STONE,
            GenerationsItems.FLUFFY_TAIL,
            CobblemonItems.FOCUS_BAND,
            CobblemonItems.FRIEND_BALL,
            CobblemonItems.GALARICA_CUFF,
            CobblemonItems.GREAT_BALL,
            CobblemonItems.GUARD_SPEC,
            CobblemonItems.HEAL_POWDER,
            GenerationsItems.HEALTH_CANDY,
            CobblemonItems.IAPAPA_BERRY,
            GenerationsItems.INSTANT_NOODLES,
            CobblemonItems.LEVEL_BALL,
            CobblemonItems.LOVE_BALL,
            CobblemonItems.LURE_BALL,
            CobblemonItems.MARANGA_BERRY,
            CobblemonItems.METAL_POWDER,
            CobblemonItems.MICLE_BERRY,
            GenerationsItems.MOOMOO_CHEESE,
            CobblemonItems.ORAN_BERRY,
            GenerationsItems.PACKAGED_CURRY,
            CobblemonItems.PETAYA_BERRY,
            CobblemonItems.POKE_BALL,
            GenerationsItems.PRECOOKED_BURGER,
            GenerationsItems.PRETTY_FEATHER,
            CobblemonItems.QUALOT_BERRY,
            GenerationsItems.QUICK_CANDY,
            CobblemonItems.REPEAT_BALL,
            GenerationsItems.ROTOM_CATALOG,
            GenerationsItems.REPEL,
            CobblemonItems.SHED_SHELL,
            GenerationsItems.SMART_CANDY,
            CobblemonItems.SMOKE_BALL,
            CobblemonItems.TIMER_BALL,
            GenerationsItems.TINY_MUSHROOM,
            GenerationsItems.TOUGH_CANDY,
            CobblemonItems.X_ATTACK,
            GenerationsItems.X_SPECIAL_ATTACK_3,
            CobblemonItems.BLACK_APRICORN,
            CobblemonItems.BLUE_APRICORN,
            CobblemonItems.GREEN_APRICORN,
            CobblemonItems.PINK_APRICORN,
            CobblemonItems.RED_APRICORN,
            CobblemonItems.WHITE_APRICORN,
            CobblemonItems.YELLOW_APRICORN,
            Items.IRON_INGOT,
            Items.LEATHER,
            Items.INK_SAC,
            Items.MUSIC_DISC_13,
            GenerationsItems.FILM,
            GenerationsItems.CAMERA,
            GenerationsItems.CRYSTAL,
            GenerationsItems.SAPPHIRE,
            GenerationsItems.SILICON,
            GenerationsItems.RUSTY_IRON_KEY_2,
            GenerationsItems.SHATTERED_ICE_KEY_2,
            GenerationsItems.CRUMBLED_ROCK_KEY_2,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_2,
            GenerationsItems.DISCHARGED_ELEKI_KEY_2,
            GenerationsItems.SHATTERED_RELIC_SONG_2,
            CobblemonItems.EXPERIENCE_CANDY_XS,
            GenerationsItems.POKEMAIL_ORANGE,
            GenerationsItems.POKEMAIL_REPLY,
            GenerationsItems.POKEMAIL_RETRO,
            GenerationsItems.POKEMAIL_RSVP,
            GenerationsItems.POKEMAIL_SHADOW,
            GenerationsItems.POKEMAIL_SNOW,
            GenerationsItems.POKEMAIL_SPACE,
            GenerationsItems.POKEMAIL_STEEL,
            GenerationsItems.POKEMAIL_THANKS,
            GenerationsItems.POKEMAIL_TROPIC,
            GenerationsItems.POKEMAIL_TUNNEL,
            GenerationsItems.POKEMAIL_WAVE,
            GenerationsItems.POKEMAIL_WOOD,
            GenerationsItems.DYNITE_ORE,
            GenerationsItems.TM_172,
            GenerationsItems.TM_183,
            GenerationsItems.TM_191,
            GenerationsItems.TM_193,
            GenerationsItems.TM_202,
            GenerationsItems.TM_203,
            GenerationsItems.TM_204,
            GenerationsItems.TM_205,
            GenerationsItems.TM_234,
            GenerationsItems.TM_236,
            GenerationsItems.TM_237,
            GenerationsItems.TM_182,
            GenerationsItems.TM_185,
            GenerationsItems.TM_219
        )

        registerBallLootPoolUniform(
            output, PREMIER_BALL, 1f, 2f,
            POKE_BALL, GenerationsItems.BIG_MALASADA, GenerationsItems.BIG_MUSHROOM,
            CobblemonItems.BLACK_GLASSES, GenerationsItems.BLUE_FLUTE, GenerationsItems.BOTTLE_CAP,
            CobblemonItems.CARBOS, GenerationsItems.CASTELIACONE, CobblemonItems.CHIPPED_POT,
            CobblemonItems.CORNN_BERRY, CobblemonItems.DARK_GEM, CobblemonItems.DEEP_SEA_SCALE,
            CobblemonItems.DESTINY_KNOT, GenerationsItems.DIRE_HIT_3, GenerationsItems.DISCOUNT_COUPON,
            CobblemonItems.DRAGON_GEM, CobblemonItems.DRAGON_SCALE, CobblemonItems.DURIN_BERRY,
            GenerationsItems.DYNAMAX_CANDY, CobblemonItems.ELECTRIC_GEM, CobblemonItems.EXPERIENCE_CANDY_L,
            GenerationsItems.FANCY_APPLE, GenerationsItems.FRUIT_BUNCH, CobblemonItems.GALARICA_WREATH,
            CobblemonItems.GUARD_SPEC, GenerationsItems.HEALTH_CANDY_XL, GenerationsItems.HEART_SCALE,
            GenerationsItems.ELEGANT_WING, CobblemonItems.ICE_GEM, GenerationsItems.ITEM_DROP,
            GenerationsItems.LOOKER_TICKET, CobblemonItems.MAGOST_BERRY, GenerationsItems.MOOMOO_MILK,
            CobblemonItems.MUSCLE_BAND, CobblemonItems.NORMAL_GEM, GenerationsItems.NUGGET,
            CobblemonItems.POISON_GEM, CobblemonItems.PP_UP, CobblemonItems.PREMIER_BALL,
            CobblemonItems.PRISM_SCALE, CobblemonItems.PROTEIN, CobblemonItems.RIBBON_SWEET,
            CobblemonItems.RINDO_BERRY, CobblemonItems.ROCKY_HELMET, CobblemonItems.ROWAP_BERRY,
            CobblemonItems.SCOPE_LENS, CobblemonItems.STEEL_GEM, GenerationsItems.TINY_MUSHROOM,
            CobblemonItems.ULTRA_BALL, CobblemonItems.UTILITY_UMBRELLA, CobblemonItems.WHITE_HERB,
            GenerationsItems.GHOST_CANDY, GenerationsItems.X_ATTACK_2, Items.GOLD_INGOT,
            Items.INK_SAC, Items.BLAZE_POWDER, Items.QUARTZ, Items.MUSIC_DISC_STAL, GenerationsItems.EXP_CHARM,
            GenerationsItems.SPARKLING_SHARD, GenerationsItems.ELECTRIC_MEMORY_DRIVE, GenerationsItems.ZAP_PLATE,
            GenerationsItems.TM_17, GenerationsItems.TM_29, GenerationsItems.TM_42,
            GenerationsItems.TM_61, GenerationsItems.TM_114, GenerationsItems.TM_151,
            GenerationsItems.TM_3, GenerationsItems.TM_18, GenerationsItems.TM_30,
            GenerationsItems.TM_43, GenerationsItems.TM_62, GenerationsItems.TM_87,
            GenerationsItems.TM_94, GenerationsItems.TM_108, GenerationsItems.TM_140, CobblemonItems.HEAVY_BALL,
            GenerationsItems.IRIS_DISC,
            GenerationsItems.NESSA_DISC,
            GenerationsItems.TEAM_ROCKET_DISC,
            GenerationsItems.SADA_AND_TURO_DISC,
            GenerationsItems.SOUTH_PROVINCE_DISC,
            GenerationsItems.RIVAL_DISC,
            GenerationsItems.LUSAMINE_DISC,
            GenerationsItems.XY_LEGENDARY_DISC,
            GenerationsItems.KANTO_DISC,
            GenerationsItems.ULTRA_NECROZMA_DISC,
            GenerationsItems.HI_TECH_EARBUDS
        )

        registerBallLootPoolUniform(
            output,
            QUICK_BALL,
            1f,
            2f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.ANTIDOTE,
            CobblemonItems.BERRY_JUICE,
            GenerationsItems.BLUE_SHARD,
            CobblemonItems.BLUNDER_POLICY,
            GenerationsItems.BOILED_EGG,
            GenerationsItems.CASTELIACONE,
            CobblemonItems.CELL_BATTERY,
            CobblemonItems.CHOICE_SCARF,
            CobblemonItems.CUSTAP_BERRY,
            CobblemonItems.FLOAT_STONE,
            GenerationsItems.FRESH_CREAM,
            GenerationsItems.FULL_INCENSE,
            GenerationsItems.GRIP_CLAW,
            CobblemonItems.HABAN_BERRY,
            CobblemonItems.HARD_STONE,
            CobblemonItems.HEALTH_FEATHER,
            GenerationsItems.HEART_SCALE,
            GenerationsItems.HONEY,
            CobblemonItems.KASIB_BERRY,
            GenerationsItems.LAGGING_TAIL,
            CobblemonItems.MAX_POTION,
            GenerationsItems.MAX_REPEL,
            CobblemonItems.METAL_POWDER,
            CobblemonItems.METRONOME,
            CobblemonItems.NANAB_BERRY,
            CobblemonItems.POMEG_BERRY,
            CobblemonItems.POWER_ANKLET,
            CobblemonItems.POWER_BAND,
            GenerationsItems.PRECOOKED_BURGER,
            CobblemonItems.PREMIER_BALL,
            CobblemonItems.PROTECTOR,
            GenerationsItems.DISCHARGED_ELEKI_KEY_1,
            GenerationsItems.DISCHARGED_ELEKI_KEY_2,
            GenerationsItems.DISCHARGED_ELEKI_KEY_3,
            GenerationsItems.DISCHARGED_ELEKI_KEY_4,
            CobblemonItems.QUICK_BALL,
            GenerationsItems.QUICK_CANDY_XL,
            CobblemonItems.QUICK_CLAW,
            GenerationsItems.RED_FLUTE,
            GenerationsItems.ICY_WING,
            GenerationsItems.ROLLER_SKATES,
            CobblemonItems.ROOM_SERVICE,
            CobblemonItems.SALAC_BERRY,
            GenerationsItems.SMOKED_POKE_TAIL,
            CobblemonItems.SPELON_BERRY,
            GenerationsItems.STATIC_WING,
            CobblemonItems.TERRAIN_EXTENDER,
            GenerationsItems.THICK_CLUB,
            GenerationsItems.NORMAL_CANDY,
            GenerationsItems.ELECTRIC_CANDY,
            GenerationsItems.X_ACCURACY_2,
            GenerationsItems.X_ATTACK_3,
            GenerationsItems.X_SPECIAL_ATTACK_3,
            GenerationsItems.X_SPECIAL_DEFENSE_3,
            GenerationsItems.X_SPEED_6,
            GenerationsItems.YELLOW_NECTAR,
            GenerationsItems.YELLOW_SHARD,
            CobblemonItems.ZINC,
            CobblemonItems.ZOOM_LENS,
            Items.FEATHER,
            Items.PORKCHOP,
            Items.RABBIT_FOOT,
            Items.MUSIC_DISC_STAL,
            GenerationsItems.DRAGON_SOUL,
            CobblemonItems.SASSY_MINT,
            CobblemonItems.CAREFUL_MINT,
            GenerationsItems.DARK_MEMORY_DRIVE,
            GenerationsItems.DREAD_PLATE,
            GenerationsItems.TM_1,
            GenerationsItems.TM_6,
            GenerationsItems.TM_7,
            GenerationsItems.TM_25,
            GenerationsItems.TM_32,
            GenerationsItems.TM_47,
            GenerationsItems.TM_57,
            GenerationsItems.TM_66,
            GenerationsItems.TM_70,
            GenerationsItems.TM_80,
            GenerationsItems.TM_88,
            GenerationsItems.TM_103,
            GenerationsItems.TM_117,
            GenerationsItems.TM_122,
            GenerationsItems.TM_130,
            GenerationsItems.TM_132,
            GenerationsItems.TM_152,
            GenerationsItems.TM_163,
            GenerationsItems.TM_171,
            GenerationsItems.TM_9,
            GenerationsItems.TM_23,
            GenerationsItems.TM_48,
            GenerationsItems.TM_68,
            GenerationsItems.TM_72,
            GenerationsItems.TM_82,
            GenerationsItems.TM_96,
            GenerationsItems.TM_126,
            GenerationsItems.TM_136,
            GenerationsItems.TM_147,
            GenerationsItems.TM_166,
            GenerationsItems.TM_173,
            GenerationsItems.TM_210,
            GenerationsItems.TM_211,
            GenerationsItems.CASCARRAFA_CITY_DISC,
            GenerationsItems.SLUMBERING_WEALD_DISC,
            GenerationsItems.POKEMON_CENTER_DISC,
            GenerationsItems.AZALEA_TOWN_DISC,
            GenerationsItems.LILLIE_DISC,
            GenerationsItems.ROUTE_228_DISC,
            GenerationsItems.JUBILIFE_VILLAGE_DISC,
            GenerationsItems.GOLDENROD_CITY_DISC,
            GenerationsItems.ETERNA_CITY_DISC,
            GenerationsItems.VERMILION_CITY_DISC
        )

        registerBallLootPoolUniform(
            output,
            REPEAT_BALL,
            1f,
            3f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.AIR_BALLOON,
            CobblemonItems.BINDING_BAND,
            CobblemonItems.CELL_BATTERY,
            CobblemonItems.CHOPLE_BERRY,
            GenerationsItems.SINISTER_WING,
            CobblemonItems.COLBUR_BERRY,
            CobblemonItems.CUSTAP_BERRY,
            CobblemonItems.EJECT_BUTTON,
            CobblemonItems.ELECTRIC_SEED,
            CobblemonItems.FAST_BALL,
            CobblemonItems.FOCUS_BAND,
            CobblemonItems.FOCUS_SASH,
            GenerationsItems.FRIED_FOOD,
            CobblemonItems.GRASSY_SEED,
            CobblemonItems.GUARD_SPEC,
            CobblemonItems.HEAVY_BALL,
            CobblemonItems.HYPER_POTION,
            GenerationsItems.ITEM_URGE,
            GenerationsItems.LONE_EARRING,
            GenerationsItems.MAX_REPEL,
            CobblemonItems.MISTY_SEED,
            GenerationsItems.OLD_GATEAU,
            CobblemonItems.PASSHO_BERRY,
            GenerationsItems.POWER_PLANT_PASS,
            CobblemonItems.PROTEIN,
            CobblemonItems.PSYCHIC_SEED,
            CobblemonItems.RED_CARD,
            CobblemonItems.REPEAT_BALL,
            CobblemonItems.REVIVE,
            CobblemonItems.SMOKE_BALL,
            GenerationsItems.TIN_OF_BEANS,
            GenerationsItems.X_ATTACK_6,
            GenerationsItems.X_DEFENSE_2,
            CobblemonItems.X_SP_ATK,
            GenerationsItems.X_SPECIAL_DEFENSE_3,
            CobblemonItems.X_SPEED,
            GenerationsItems.YELLOW_SHARD,
            CobblemonItems.ZINC,
            CobblemonItems.BLACK_APRICORN,
            CobblemonItems.BLUE_APRICORN,
            CobblemonItems.GREEN_APRICORN,
            CobblemonItems.PINK_APRICORN,
            CobblemonItems.RED_APRICORN,
            CobblemonItems.WHITE_APRICORN,
            CobblemonItems.YELLOW_APRICORN,
            Items.STRING,
            Items.MUSIC_DISC_MALL,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_1,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_2,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_3,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_4,
            GenerationsItems.FIGHTING_CANDY,
            GenerationsItems.FILM,
            GenerationsItems.CAMERA,
            GenerationsItems.POKEMAIL_ORANGE,
            GenerationsItems.POKEMAIL_REPLY,
            GenerationsItems.POKEMAIL_RETRO,
            GenerationsItems.POKEMAIL_RSVP,
            GenerationsItems.POKEMAIL_SHADOW,
            GenerationsItems.POKEMAIL_SNOW,
            GenerationsItems.POKEMAIL_SPACE,
            GenerationsItems.POKEMAIL_STEEL,
            GenerationsItems.POKEMAIL_THANKS,
            GenerationsItems.POKEMAIL_TROPIC,
            GenerationsItems.POKEMAIL_TUNNEL,
            GenerationsItems.POKEMAIL_WAVE,
            GenerationsItems.POKEMAIL_WOOD,
            GenerationsItems.TM_12,
            GenerationsItems.TM_39,
            GenerationsItems.TM_58,
            GenerationsItems.TM_64,
            GenerationsItems.TM_73,
            GenerationsItems.TM_89,
            GenerationsItems.TM_112,
            GenerationsItems.TM_134,
            GenerationsItems.TM_158,
            GenerationsItems.TM_167,
            GenerationsItems.TM_172,
            GenerationsItems.TM_183,
            GenerationsItems.TM_191,
            GenerationsItems.TM_193,
            GenerationsItems.TM_202,
            GenerationsItems.TM_203,
            GenerationsItems.TM_204,
            GenerationsItems.TM_205,
            GenerationsItems.TM_234,
            GenerationsItems.TM_236,
            GenerationsItems.TM_237,
            GenerationsItems.TM_173,
            GenerationsItems.TM_210,
            GenerationsItems.TM_211,
            GenerationsItems.TM_182,
            GenerationsItems.TM_185,
            GenerationsItems.TM_219
        )

        registerBallLootPoolUniform(
            output,
            SAFARI_BALL,
            1f,
            2f,
            CobblemonItems.POKE_BALL,
            GenerationsItems.ADRENALINE_ORB,
            CobblemonItems.AGUAV_BERRY,
            GenerationsItems.BALM_MUSHROOM,
            GenerationsItems.BIG_MUSHROOM,
            CobblemonItems.BUG_GEM,
            GenerationsItems.COMET_SHARD,
            GenerationsItems.COURAGE_CANDY_L,
            CobblemonItems.DRAGON_SCALE,
            CobblemonItems.ETHER,
            CobblemonItems.EXPERIENCE_CANDY_S,
            CobblemonItems.EXP_SHARE,
            GenerationsItems.FANCY_APPLE,
            GenerationsItems.FESTIVAL_TICKET,
            CobblemonItems.FIGY_BERRY,
            GenerationsItems.FRESH_WATER,
            GenerationsItems.FRUIT_BUNCH,
            GenerationsItems.FULL_INCENSE,
            CobblemonItems.GALARICA_WREATH,
            CobblemonItems.GREAT_BALL,
            CobblemonItems.GROUND_GEM,
            GenerationsItems.DISCHARGED_ELEKI_KEY_1,
            GenerationsItems.DISCHARGED_ELEKI_KEY_2,
            GenerationsItems.DISCHARGED_ELEKI_KEY_3,
            GenerationsItems.DISCHARGED_ELEKI_KEY_4,
            CobblemonItems.HEAL_BALL,
            GenerationsItems.INSTANT_NOODLES,
            CobblemonItems.KASIB_BERRY,
            GenerationsItems.LEEK,
            CobblemonItems.LEFTOVERS,
            CobblemonItems.MENTAL_HERB,
            GenerationsItems.MIGHTY_CANDY,
            CobblemonItems.MIRACLE_SEED,
            GenerationsItems.ODD_INCENSE,
            CobblemonItems.PAMTRE_BERRY,
            GenerationsItems.PASS_ORB,
            GenerationsItems.POLISHED_MUD_BALL,
            GenerationsItems.RED_SCARF,
            CobblemonItems.REVIVE,
            GenerationsItems.ROCK_INCENSE,
            CobblemonItems.ROSELI_BERRY,
            CobblemonItems.SAFARI_BALL,
            GenerationsItems.SALAD_MIX,
            GenerationsItems.SILVER_LEAF,
            CobblemonItems.SILVER_POWDER,
            CobblemonItems.SOOTHE_BELL,
            GenerationsItems.STAR_PIECE,
            GenerationsItems.SUPER_REPEL,
            GenerationsItems.TINY_MUSHROOM,
            CobblemonItems.WIKI_BERRY,
            CobblemonItems.WISE_GLASSES,
            GenerationsItems.X_ACCURACY_3,
            GenerationsItems.X_ATTACK_6,
            GenerationsItems.X_DEFENSE_2,
            GenerationsItems.X_SPECIAL_ATTACK_6,
            GenerationsItems.X_SPECIAL_DEFENSE_3,
            GenerationsItems.YELLOW_NECTAR,
            CobblemonItems.BLACK_APRICORN,
            CobblemonItems.BLUE_APRICORN,
            CobblemonItems.GREEN_APRICORN,
            CobblemonItems.PINK_APRICORN,
            CobblemonItems.RED_APRICORN,
            CobblemonItems.WHITE_APRICORN,
            CobblemonItems.YELLOW_APRICORN,
            Items.MILK_BUCKET,
            Items.BONE,
            Items.SPIDER_EYE,
            Items.CRIMSON_FUNGUS,
            Items.MUSIC_DISC_MALL,
            GenerationsItems.BASIC_SWEET_POKE_PUFF,
            GenerationsItems.BASIC_MINT_POKE_PUFF,
            GenerationsItems.BASIC_CITRUS_POKE_PUFF,
            GenerationsItems.BASIC_MOCHA_POKE_PUFF,
            GenerationsItems.BASIC_SPICE_POKE_PUFF,
            GenerationsItems.RUSTY_FRAGMENT,
            GenerationsItems.SCROLL_PAGE,
            GenerationsItems.GRASS_MEMORY_DRIVE,
            GenerationsItems.MEADOW_PLATE,
            GenerationsItems.GRASS_CANDY,
            GenerationsItems.GROUND_CANDY,
            GenerationsItems.TM_20,
            GenerationsItems.TM_33,
            GenerationsItems.TM_56,
            GenerationsItems.TM_71,
            GenerationsItems.TM_81,
            GenerationsItems.TM_111,
            GenerationsItems.TM_119,
            GenerationsItems.TM_137,
            GenerationsItems.TM_146,
            GenerationsItems.TM_155,
            GenerationsItems.TM_159,
            GenerationsItems.TM_168,
            GenerationsItems.TM_5,
            GenerationsItems.TM_28,
            GenerationsItems.TM_35,
            GenerationsItems.TM_55,
            GenerationsItems.TM_84,
            GenerationsItems.TM_90,
            GenerationsItems.TM_106,
            GenerationsItems.TM_133,
            GenerationsItems.TM_149,
            GenerationsItems.TM_189,
            GenerationsItems.TM_195,
            GenerationsItems.TM_207,
            GenerationsItems.TM_181,
            GenerationsItems.TM_199,
            GenerationsItems.TM_221
        )

        registerBallLootPoolUniform(
            output,
            SPORT_BALL,
            1f,
            2f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.APICOT_BERRY,
            CobblemonItems.ASPEAR_BERRY,
            CobblemonItems.ASSAULT_VEST,
            CobblemonItems.BLACK_BELT,
            CobblemonItems.BLACK_GLASSES,
            GenerationsItems.BLUE_FLUTE,
            GenerationsItems.BREAD,
            CobblemonItems.BRIGHT_POWDER,
            CobblemonItems.CHARCOAL,
            CobblemonItems.CHILAN_BERRY,
            CobblemonItems.CHOPLE_BERRY,
            GenerationsItems.DIRE_HIT_3,
            CobblemonItems.DIVE_BALL,
            CobblemonItems.ENERGY_ROOT,
            CobblemonItems.EXPERT_BELT,
            CobblemonItems.FIGHTING_GEM,
            CobblemonItems.FIRE_STONE,
            CobblemonItems.FOCUS_BAND,
            CobblemonItems.FOCUS_SASH,
            CobblemonItems.HARD_STONE,
            CobblemonItems.HEAL_BALL,
            CobblemonItems.HEAVY_DUTY_BOOTS,
            CobblemonItems.IRON,
            CobblemonItems.KELPSY_BERRY,
            CobblemonItems.KINGS_ROCK,
            GenerationsItems.LAVA_COOKIE,
            CobblemonItems.LEVEL_BALL,
            CobblemonItems.LIECHI_BERRY,
            GenerationsItems.LUCKY_PUNCH,
            GenerationsItems.MACHO_BRACE,
            GenerationsItems.MIGHTY_CANDY,
            CobblemonItems.MUSCLE_BAND,
            GenerationsItems.BELLIGERENT_WING,
            CobblemonItems.OCCA_BERRY,
            GenerationsItems.PINK_SCARF,
            CobblemonItems.POWER_ANKLET,
            CobblemonItems.POWER_BRACER,
            GenerationsItems.ELEGANT_WING,
            CobblemonItems.PROTECTIVE_PADS,
            CobblemonItems.PROTEIN,
            GenerationsItems.PUNGENT_ROOT,
            CobblemonItems.QUICK_CLAW,
            CobblemonItems.SAFETY_GOGGLES,
            GenerationsItems.SHOAL_SALT,
            GenerationsItems.SMART_CANDY,
            CobblemonItems.SOFT_SAND,
            GenerationsItems.SPICE_MIX,
            CobblemonItems.SPORT_BALL,
            CobblemonItems.STICKY_BARB,
            CobblemonItems.SUPER_POTION,
            CobblemonItems.TERRAIN_EXTENDER,
            CobblemonItems.UTILITY_UMBRELLA,
            GenerationsItems.WHITE_FLUTE,
            CobblemonItems.WIDE_LENS,
            GenerationsItems.FIGHTING_CANDY,
            GenerationsItems.X_DEFENSE_3,
            CobblemonItems.X_SP_DEF,
            Items.STRING,
            Items.GUNPOWDER,
            Items.SADDLE,
            Items.RABBIT_FOOT,
            Items.RABBIT_HIDE,
            Items.MUSIC_DISC_WAIT,
            GenerationsItems.MARK_CHARM,
            GenerationsItems.ROCKSTAR_COSTUME,
            GenerationsItems.BELLE_COSTUME,
            GenerationsItems.POPSTAR_COSTUME,
            GenerationsItems.PHD_COSTUME,
            GenerationsItems.LIBRE_COSTUME,
            GenerationsItems.OLD_ROD,
            GenerationsItems.GOOD_ROD,
            GenerationsItems.SUPER_ROD,
            GenerationsItems.RUSTY_IRON_KEY_4,
            GenerationsItems.SHATTERED_ICE_KEY_4,
            GenerationsItems.CRUMBLED_ROCK_KEY_4,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_4,
            GenerationsItems.DISCHARGED_ELEKI_KEY_4,
            GenerationsItems.SHATTERED_RELIC_SONG_4,
            GenerationsItems.FIRE_MEMORY_DRIVE,
            GenerationsItems.FIGHTING_MEMORY_DRIVE,
            GenerationsItems.FLAME_PLATE,
            GenerationsItems.FIST_PLATE,
            GenerationsItems.TM_12,
            GenerationsItems.TM_39,
            GenerationsItems.TM_58,
            GenerationsItems.TM_64,
            GenerationsItems.TM_73,
            GenerationsItems.TM_89,
            GenerationsItems.TM_112,
            GenerationsItems.TM_134,
            GenerationsItems.TM_158,
            GenerationsItems.TM_167,
            GenerationsItems.TM_189,
            GenerationsItems.TM_195,
            GenerationsItems.TM_207,
            GenerationsItems.TM_179,
            GenerationsItems.TM_220,
            GenerationsItems.TM_184,
            GenerationsItems.TM_192,
            GenerationsItems.TM_213,
            GenerationsItems.TM_229
        )

        registerBallLootPoolConstant(
            output, STRANGE_BALL, 1f,
            POKE_BALL, CobblemonItems.SURPRISE_MULCH, CobblemonItems.GROWTH_MULCH,
            CobblemonItems.RICH_MULCH, GenerationsItems.SCROLL_PAGE, GenerationsItems.RUSTY_FRAGMENT,
            GenerationsItems.SPARKLING_SHARD, GenerationsItems.HOOPA_RING, GenerationsItems.DRAGON_SOUL,
            GenerationsItems.LEGEND_PLATE, GenerationsItems.GHOST_CANDY, GenerationsItems.PERMIT,
            GenerationsItems.PLASMA_CARD, POKE_BALL, CobblemonItems.POWER_WEIGHT,
            CobblemonItems.PP_UP, CobblemonItems.RARE_CANDY, GenerationsItems.RESET_URGE,
            GenerationsItems.ROLLER_SKATES, CobblemonItems.ROOM_SERVICE, GenerationsItems.SHALOUR_SABLE,
            GenerationsItems.PRECOOKED_BURGER, GenerationsItems.PUNGENT_ROOT, GenerationsItems.ORB,
            GenerationsItems.MIXED_MUSHROOMS, GenerationsItems.GIGANTAMIX, GenerationsItems.Z_INGOT,
            GenerationsItems.POKEMAIL_RETRO, GenerationsItems.POKEMAIL_RSVP, GenerationsItems.POKEMAIL_SPACE,
            CobblemonItems.ENIGMA_BERRY, CobblemonItems.POMEG_BERRY, CobblemonItems.YACHE_BERRY,
            CobblemonItems.HONDEW_BERRY, GenerationsItems.ROCKSTAR_COSTUME, GenerationsItems.BELLE_COSTUME,
            GenerationsItems.POPSTAR_COSTUME, GenerationsItems.PHD_COSTUME, GenerationsItems.LIBRE_COSTUME,
            GenerationsItems.MEWTWO_ARMOR, GenerationsItems.ROTOM_CATALOG, GenerationsItems.PINK_NECTAR,
            GenerationsItems.PURPLE_NECTAR, GenerationsItems.RED_NECTAR, GenerationsItems.YELLOW_NECTAR,
            GenerationsItems.OLD_ROD, GenerationsItems.GOOD_ROD, GenerationsItems.SUPER_ROD,
            GenerationsItems.WAILMER_PAIL, GenerationsItems.SPRINK_LOTAD, GenerationsItems.REPEL,
            GenerationsItems.SUPER_REPEL, GenerationsItems.MAX_REPEL, GenerationsItems.CAMERA,
            GenerationsItems.FILM, GenerationsItems.SNAP_CAMERA, GenerationsItems.FULL_INCENSE,
            GenerationsItems.LAX_INCENSE, GenerationsItems.ODD_INCENSE, GenerationsItems.PURE_INCENSE,
            GenerationsItems.ROCK_INCENSE, GenerationsItems.ROSE_INCENSE, GenerationsItems.SEA_INCENSE,
            GenerationsItems.WAVE_INCENSE, GenerationsItems.TM_17, GenerationsItems.TM_29,
            GenerationsItems.TM_42, GenerationsItems.TM_61, GenerationsItems.TM_114,
            GenerationsItems.TM_151, GenerationsItems.TM_3, GenerationsItems.TM_18,
            GenerationsItems.TM_30, GenerationsItems.TM_43, GenerationsItems.TM_62,
            GenerationsItems.TM_87, GenerationsItems.TM_94, GenerationsItems.TM_108,
            GenerationsItems.TM_140, GenerationsItems.TM_189, GenerationsItems.TM_195, GenerationsItems.TM_207,
            Items.TOTEM_OF_UNDYING, GenerationsItems.ENIGMA_FRAGMENT, GenerationsItems.MEW_FOSSIL,
            GenerationsItems.TM_175, GenerationsItems.TM_214, GenerationsItems.TM_200,
            GenerationsItems.TM_222, GenerationsItems.TM_226,
            GenerationsItems.LUGIA_DISC,
            GenerationsItems.LAVENDER_TOWN_DISC,
            GenerationsItems.MT_PYRE_DISC
        )

        registerBallLootPoolUniform(
            output,
            TIMER_BALL,
            1f,
            3f,
            CobblemonItems.POKE_BALL,
            GenerationsItems.ABILITY_URGE,
            CobblemonItems.BLUNDER_POLICY,
            CobblemonItems.BRIGHT_POWDER,
            CobblemonItems.COBA_BERRY,
            GenerationsItems.COCONUT_MILK,
            CobblemonItems.CORNN_BERRY,
            CobblemonItems.DAMP_ROCK,
            GenerationsItems.DIRE_HIT_2,
            CobblemonItems.DUBIOUS_DISC,
            CobblemonItems.ELECTRIC_SEED,
            GenerationsItems.ESCAPE_ROPE,
            CobblemonItems.FAST_BALL,
            GenerationsItems.FESTIVAL_TICKET,
            GenerationsItems.FLUFFY_TAIL,
            GenerationsItems.FRESH_CREAM,
            CobblemonItems.FULL_RESTORE,
            GenerationsItems.GRIP_CLAW,
            GenerationsItems.GRUBBY_HANKY,
            CobblemonItems.HEAL_POWDER,
            GenerationsItems.HEALTH_CANDY_L,
            CobblemonItems.HEAT_ROCK,
            CobblemonItems.IAPAPA_BERRY,
            CobblemonItems.ICY_ROCK,
            CobblemonItems.KASIB_BERRY,
            CobblemonItems.KINGS_ROCK,
            GenerationsItems.LAVA_COOKIE,
            CobblemonItems.LIFE_ORB,
            CobblemonItems.LIGHT_CLAY,
            CobblemonItems.LUCKY_EGG,
            CobblemonItems.MAGOST_BERRY,
            CobblemonItems.MAX_REVIVE,
            CobblemonItems.MUSCLE_BAND,
            CobblemonItems.NANAB_BERRY,
            CobblemonItems.NOMEL_BERRY,
            GenerationsItems.PEWTER_CRUNCHIES,
            GenerationsItems.PLASMA_CARD,
            CobblemonItems.POMEG_BERRY,
            CobblemonItems.POWER_HERB,
            CobblemonItems.QUICK_CLAW,
            CobblemonItems.RABUTA_BERRY,
            CobblemonItems.REVIVE,
            CobblemonItems.SALAC_BERRY,
            GenerationsItems.SALAD_MIX,
            CobblemonItems.SHARP_BEAK,
            GenerationsItems.SILVER_LEAF,
            GenerationsItems.ORB,
            GenerationsItems.ROTOM_CATALOG,
            CobblemonItems.SPORT_BALL,
            CobblemonItems.TERRAIN_EXTENDER,
            CobblemonItems.TIMER_BALL,
            GenerationsItems.TIN_OF_BEANS,
            CobblemonItems.WIKI_BERRY,
            CobblemonItems.WISE_GLASSES,
            GenerationsItems.ICE_CANDY,
            GenerationsItems.X_ACCURACY_2,
            GenerationsItems.X_ATTACK_6,
            GenerationsItems.X_SPECIAL_ATTACK_3,
            Items.SADDLE,
            Items.LEATHER,
            Items.BLAZE_POWDER,
            Items.MUSIC_DISC_WAIT,
            GenerationsItems.BASIC_SWEET_POKE_PUFF,
            GenerationsItems.BASIC_MINT_POKE_PUFF,
            GenerationsItems.BASIC_CITRUS_POKE_PUFF,
            GenerationsItems.BASIC_MOCHA_POKE_PUFF,
            GenerationsItems.BASIC_SPICE_POKE_PUFF,
            Items.AMETHYST_SHARD,
            GenerationsItems.RUBY,
            GenerationsItems.POKEMAIL_ORANGE,
            GenerationsItems.POKEMAIL_REPLY,
            GenerationsItems.POKEMAIL_RETRO,
            GenerationsItems.POKEMAIL_RSVP,
            GenerationsItems.POKEMAIL_SHADOW,
            GenerationsItems.POKEMAIL_SNOW,
            GenerationsItems.POKEMAIL_SPACE,
            GenerationsItems.POKEMAIL_STEEL,
            GenerationsItems.POKEMAIL_THANKS,
            GenerationsItems.POKEMAIL_TROPIC,
            GenerationsItems.POKEMAIL_TUNNEL,
            GenerationsItems.POKEMAIL_WAVE,
            GenerationsItems.POKEMAIL_WOOD,
            CobblemonItems.SURPRISE_MULCH,
            CobblemonItems.GROWTH_MULCH,
            GenerationsItems.TM_172,
            GenerationsItems.TM_183,
            GenerationsItems.TM_191,
            GenerationsItems.TM_193,
            GenerationsItems.TM_202,
            GenerationsItems.TM_203,
            GenerationsItems.TM_204,
            GenerationsItems.TM_205,
            GenerationsItems.TM_234,
            GenerationsItems.TM_236,
            GenerationsItems.TM_237,
            GenerationsItems.TM_173,
            GenerationsItems.TM_210,
            GenerationsItems.TM_211,
            GenerationsItems.TM_181,
            GenerationsItems.TM_199,
            GenerationsItems.TM_221,
            GenerationsItems.TM_178,
            GenerationsItems.TM_217,
            GenerationsItems.TM_218,
            GenerationsItems.TM_228,
            GenerationsItems.TM_235,
            GenerationsItems.CERULEAN_CITY_DISC,
            GenerationsItems.ICIRRUS_CITY_DISC,
            GenerationsItems.LAVERRE_CITY_DISC,
            GenerationsItems.SURF_DISC,
            GenerationsItems.LAKE_OF_RAGE_DISC,
            GenerationsItems.PENNY_DISC,
            GenerationsItems.NEMONA_DISC,
            GenerationsItems.ZINNIA_DISC,
            GenerationsItems.CYNTHIA_DISC,
            GenerationsItems.DEOXYS_DISC
        )

        registerBallLootPoolUniform(
            output,
            ULTRA_BALL,
            1f,
            3f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.ABSORB_BULB,
            GenerationsItems.ADRENALINE_ORB,
            CobblemonItems.AWAKENING,
            GenerationsItems.BALM_MUSHROOM,
            CobblemonItems.BERRY_SWEET,
            CobblemonItems.BLACK_BELT,
            CobblemonItems.BLACK_SLUDGE,
            CobblemonItems.BLUK_BERRY,
            CobblemonItems.BLUNDER_POLICY,
            CobblemonItems.BURN_HEAL,
            CobblemonItems.CALCIUM,
            CobblemonItems.CELL_BATTERY,
            CobblemonItems.CHARCOAL,
            CobblemonItems.CHERI_BERRY,
            CobblemonItems.CHERI_BERRY,
            CobblemonItems.CHIPPED_POT,
            CobblemonItems.CHOICE_BAND,
            CobblemonItems.CLOVER_SWEET,
            CobblemonItems.CORNN_BERRY,
            GenerationsItems.COURAGE_CANDY_L,
            CobblemonItems.DEEP_SEA_TOOTH,
            CobblemonItems.DIRE_HIT,
            CobblemonItems.DRAGON_FANG,
            CobblemonItems.DREAM_BALL,
            CobblemonItems.DUSK_BALL,
            CobblemonItems.EJECT_PACK,
            CobblemonItems.EXPERIENCE_CANDY_L,
            CobblemonItems.EXPERT_BELT,
            CobblemonItems.FAST_BALL,
            CobblemonItems.FLAME_ORB,
            GenerationsItems.FRUIT_BUNCH,
            CobblemonItems.FULL_HEAL,
            CobblemonItems.FULL_RESTORE,
            GenerationsItems.FIERY_WING,
            CobblemonItems.GHOST_GEM,
            GenerationsItems.GRIP_CLAW,
            GenerationsItems.GRUBBY_HANKY,
            CobblemonItems.HEAL_BALL,
            GenerationsItems.HEALTH_CANDY_XL,
            CobblemonItems.HEAVY_DUTY_BOOTS,
            CobblemonItems.KEE_BERRY,
            CobblemonItems.KELPSY_BERRY,
            GenerationsItems.LOOKER_TICKET,
            CobblemonItems.MAGNET,
            CobblemonItems.MAX_ELIXIR,
            CobblemonItems.MAX_REVIVE,
            GenerationsItems.MIGHTY_CANDY_XL,
            CobblemonItems.NEVER_MELT_ICE,
            CobblemonItems.NORMAL_GEM,
            GenerationsItems.PERMIT,
            GenerationsItems.PLASMA_CARD,
            CobblemonItems.POKE_BALL,
            CobblemonItems.POWER_WEIGHT,
            CobblemonItems.PP_UP,
            CobblemonItems.RARE_CANDY,
            GenerationsItems.RESET_URGE,
            GenerationsItems.ROLLER_SKATES,
            CobblemonItems.ROOM_SERVICE,
            GenerationsItems.SHALOUR_SABLE,
            CobblemonItems.SHARP_BEAK,
            CobblemonItems.SOFT_SAND,
            GenerationsItems.SOUL_DEW,
            GenerationsItems.STARDUST,
            CobblemonItems.SUPER_POTION,
            CobblemonItems.THROAT_SPRAY,
            GenerationsItems.TOUGH_CANDY_L,
            CobblemonItems.ULTRA_BALL,
            CobblemonItems.WEAKNESS_POLICY,
            GenerationsItems.WHITE_FLUTE,
            GenerationsItems.X_ACCURACY_6,
            GenerationsItems.X_SPECIAL_ATTACK_6,
            GenerationsItems.X_SPECIAL_DEFENSE_2,
            Items.SADDLE,
            Items.LEATHER,
            Items.BLAZE_POWDER,
            Items.MUSIC_DISC_WAIT,
            GenerationsItems.BASIC_SWEET_POKE_PUFF,
            GenerationsItems.BASIC_MINT_POKE_PUFF,
            GenerationsItems.BASIC_CITRUS_POKE_PUFF,
            GenerationsItems.BASIC_MOCHA_POKE_PUFF,
            GenerationsItems.BASIC_SPICE_POKE_PUFF,
            Items.AMETHYST_SHARD,
            GenerationsItems.RUBY,
            GenerationsItems.POKEMAIL_ORANGE,
            GenerationsItems.POKEMAIL_REPLY,
            GenerationsItems.POKEMAIL_RETRO,
            GenerationsItems.POKEMAIL_RSVP,
            GenerationsItems.POKEMAIL_SHADOW,
            GenerationsItems.POKEMAIL_SNOW,
            GenerationsItems.POKEMAIL_SPACE,
            GenerationsItems.POKEMAIL_STEEL,
            GenerationsItems.POKEMAIL_THANKS,
            GenerationsItems.POKEMAIL_TROPIC,
            GenerationsItems.POKEMAIL_TUNNEL,
            GenerationsItems.POKEMAIL_WAVE,
            GenerationsItems.POKEMAIL_WOOD,
            CobblemonItems.SURPRISE_MULCH,
            CobblemonItems.GROWTH_MULCH,
            GenerationsItems.TM_173,
            GenerationsItems.TM_210,
            GenerationsItems.TM_211,
            GenerationsItems.TM_188,
            GenerationsItems.TM_196,
            GenerationsItems.TM_208,
            GenerationsItems.TM_209,
            GenerationsItems.TM_197,
            GenerationsItems.TM_216,
            GenerationsItems.TM_181,
            GenerationsItems.TM_199,
            GenerationsItems.TM_221,
            GenerationsItems.TM_175,
            GenerationsItems.TM_214,
            GenerationsItems.TM_200,
            GenerationsItems.TM_222,
            GenerationsItems.TM_226,
            GenerationsItems.TM_230,
            GenerationsItems.TM_231,
            GenerationsItems.IRIS_DISC,
            GenerationsItems.NESSA_DISC,
            GenerationsItems.TEAM_ROCKET_DISC,
            GenerationsItems.SADA_AND_TURO_DISC,
            GenerationsItems.SOUTH_PROVINCE_DISC,
            GenerationsItems.RIVAL_DISC,
            GenerationsItems.LUSAMINE_DISC,
            GenerationsItems.XY_LEGENDARY_DISC,
            GenerationsItems.KANTO_DISC,
            GenerationsItems.ULTRA_NECROZMA_DISC
        )

        registerBallLootPoolUniform(
            output, WING_BALL, 1f, 2f,
            POKE_BALL, GenerationsItems.ICY_WING, GenerationsItems.ELEGANT_WING,
            CobblemonItems.HEALTH_FEATHER, GenerationsItems.STATIC_WING, GenerationsItems.BELLIGERENT_WING,
            GenerationsItems.FIERY_WING, GenerationsItems.SINISTER_WING, GenerationsItems.SILVER_WING,
            GenerationsItems.RAINBOW_WING, CobblemonItems.COBA_BERRY, CobblemonItems.FLYING_GEM,
            GenerationsItems.FLYING_MEMORY_DRIVE, CobblemonItems.IRON_BALL,
            CobblemonItems.SHARP_BEAK, GenerationsItems.SKY_PLATE, CobblemonItems.UTILITY_UMBRELLA,
            CobblemonItems.AIR_BALLOON, CobblemonItems.GREPA_BERRY, CobblemonItems.LANSAT_BERRY,
            CobblemonItems.LUM_BERRY, CobblemonItems.LIGHT_BALL, GenerationsItems.PINK_NECTAR,
            GenerationsItems.PURPLE_NECTAR, GenerationsItems.RED_NECTAR, GenerationsItems.YELLOW_NECTAR,
            CobblemonItems.POWER_HERB, CobblemonItems.MENTAL_HERB, CobblemonItems.MIRROR_HERB,
            CobblemonItems.WHITE_HERB, CobblemonItems.ICY_ROCK, CobblemonItems.HEAT_ROCK,
            CobblemonItems.ASSAULT_VEST, CobblemonItems.ELECTRIC_SEED, CobblemonItems.GRASSY_SEED,
            CobblemonItems.MISTY_SEED, CobblemonItems.PSYCHIC_SEED, CobblemonItems.MIRACLE_SEED,
            CobblemonItems.ANTIDOTE, CobblemonItems.MAX_ELIXIR, CobblemonItems.HYPER_POTION,
            GenerationsItems.MOOMOO_MILK, CobblemonItems.GREAT_BALL, GenerationsItems.FRESH_WATER,
            GenerationsItems.SODA_POP, CobblemonItems.POTION, CobblemonItems.CALCIUM,
            GenerationsItems.HEALTH_CANDY, GenerationsItems.QUICK_CANDY, GenerationsItems.SMART_CANDY,
            GenerationsItems.SILVER_LEAF, GenerationsItems.GOLD_LEAF, GenerationsItems.HEART_SCALE,
            GenerationsItems.STARDUST, GenerationsItems.POKEMAIL_HARBOR, GenerationsItems.POKEMAIL_INQUIRY,
            GenerationsItems.POKEMAIL_TROPIC, GenerationsItems.POKEMAIL_AIR, GenerationsItems.POKEMAIL_REPLY,
            GenerationsItems.POKEMAIL_SPACE, CobblemonItems.CHOICE_BAND, GenerationsItems.COMET_SHARD,
            CobblemonItems.DESTINY_KNOT, GenerationsItems.BOILED_EGG, GenerationsItems.SAUSAGES,
            GenerationsItems.BOBS_FOOD_TIN, GenerationsItems.BACHS_FOOD_TIN, GenerationsItems.GRIP_CLAW,
            GenerationsItems.REPEL, GenerationsItems.SUPER_REPEL, CobblemonItems.EXPERIENCE_CANDY_XS,
            CobblemonItems.EXPERIENCE_CANDY_S, GenerationsItems.FLYING_CANDY, GenerationsItems.X_SPEED_2,
            CobblemonItems.X_SPEED, GenerationsItems.X_ACCURACY_6, CobblemonItems.X_ATTACK,
            GenerationsItems.TM_14, GenerationsItems.TM_27, GenerationsItems.TM_40,
            GenerationsItems.TM_65, GenerationsItems.TM_97, GenerationsItems.TM_113,
            GenerationsItems.TM_160, GenerationsItems.TM_164,
            GenerationsItems.TM_197, GenerationsItems.TM_216, GenerationsItems.TM_230, GenerationsItems.TM_231,
            GenerationsItems.CERULEAN_CITY_DISC,
            GenerationsItems.ICIRRUS_CITY_DISC,
            GenerationsItems.LAVERRE_CITY_DISC,
            GenerationsItems.SURF_DISC,
            GenerationsItems.LAKE_OF_RAGE_DISC,
            GenerationsItems.PENNY_DISC,
            GenerationsItems.NEMONA_DISC,
            GenerationsItems.ZINNIA_DISC,
            GenerationsItems.CYNTHIA_DISC,
            GenerationsItems.DEOXYS_DISC
        )
    }
}