package generations.gg.generations.core.generationscore.forge.datagen.generators.loot

import com.cobblemon.mod.common.CobblemonItems
import com.cobblemon.mod.common.CobblemonItems.BEAST_BALL
import generations.gg.generations.core.generationscore.common.world.item.GenerationsItems
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.CHERISH_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.DIVE_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.DREAM_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.DUSK_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.FAST_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.registerBallLootPoolUniform
import net.minecraft.resources.ResourceKey
import net.minecraft.world.item.Items
import net.minecraft.world.level.storage.loot.LootTable
import java.util.function.BiConsumer

object ChestLootDataGenA {
    fun generate(output: BiConsumer<ResourceKey<LootTable>, LootTable.Builder>) {
        registerBallLootPoolUniform(
            output,
            GenerationsChestLoot.BEAST_BALL,
            1.0f,
            3.0f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.ANTIDOTE,
            CobblemonItems.ASSAULT_VEST,
            CobblemonItems.BABIRI_BERRY,
            CobblemonItems.BEAST_BALL,
            GenerationsItems.BIG_NUGGET,
            CobblemonItems.BLACK_SLUDGE,
            CobblemonItems.BRIGHT_POWDER,
            GenerationsItems.BRITTLE_BONES,
            CobblemonItems.CELL_BATTERY,
            GenerationsItems.CHALKY_STONE,
            CobblemonItems.CHARCOAL,
            CobblemonItems.CHARTI_BERRY,
            CobblemonItems.CHOICE_BAND,
            CobblemonItems.CHOICE_SPECS,
            CobblemonItems.CHOPLE_BERRY,
            CobblemonItems.COLBUR_BERRY,
            GenerationsItems.COMET_SHARD,
            GenerationsItems.COURAGE_CANDY_XL,
            GenerationsItems.DNA_SPLICERS,
            CobblemonItems.DRAGON_GEM,
            GenerationsItems.DYNAMAX_CANDY,
            CobblemonItems.ENIGMA_BERRY,
            CobblemonItems.EXPERIENCE_CANDY_XL,
            CobblemonItems.FAIRY_GEM,
            CobblemonItems.FIRE_GEM,
            CobblemonItems.FLAME_ORB,
            CobblemonItems.FULL_HEAL,
            CobblemonItems.GANLON_BERRY,
            GenerationsItems.GIGANTAMIX,
            CobblemonItems.HEAL_POWDER,
            CobblemonItems.JABOCA_BERRY,
            GenerationsItems.LAVA_COOKIE,
            GenerationsItems.PERMIT,
            CobblemonItems.POMEG_BERRY,
            CobblemonItems.POWER_BELT,
            CobblemonItems.RAWST_BERRY,
            GenerationsItems.ROCK_INCENSE,
            GenerationsItems.SEA_INCENSE,
            GenerationsItems.SMART_CANDY_L,
            GenerationsItems.SODA_POP,
            GenerationsItems.STRANGE_SOUVENIR,
            CobblemonItems.WEAKNESS_POLICY,
            CobblemonItems.WEPEAR_BERRY,
            CobblemonItems.WIDE_LENS,
            GenerationsItems.X_SPECIAL_DEFENSE_2,
            CobblemonItems.X_SPEED,
            GenerationsItems.X_SPEED_6,
            CobblemonItems.YACHE_BERRY,
            GenerationsItems.YELLOW_NECTAR,
            GenerationsItems.DRAGON_CANDY,
            GenerationsItems.YELLOW_SHARD,
            CobblemonItems.ZINC,
            CobblemonItems.ZOOM_LENS,
            Items.PURPUR_BLOCK,
            Items.END_STONE,
            Items.PRISMARINE,
            Items.GLOWSTONE_DUST,
            Items.NETHER_WART,
            Items.SPIDER_EYE,
            Items.WARPED_FUNGUS,
            Items.MUSIC_DISC_CAT,
            GenerationsItems.Z_INGOT,
            Items.AMETHYST_SHARD,
            GenerationsItems.RUBY,
            GenerationsItems.LAVA_CRYSTAL,
            GenerationsItems.BELLIGERENT_WING,
            GenerationsItems.TM_44,
            GenerationsItems.TM_78,
            GenerationsItems.TM_100,
            GenerationsItems.TM_115,
            GenerationsItems.TM_156,
            GenerationsItems.TM_169,
            CobblemonItems.SURPRISE_MULCH,
            CobblemonItems.GROWTH_MULCH,
            Items.NETHERITE_SCRAP,
            CobblemonItems.RICH_MULCH,
            GenerationsItems.DYNITE_ORE,
            GenerationsItems.TM_181,
            GenerationsItems.TM_199,
            GenerationsItems.TM_221,
            GenerationsItems.LUGIA_DISC,
            GenerationsItems.LAVENDER_TOWN_DISC,
            GenerationsItems.MT_PYRE_DISC,
            GenerationsItems.ULTRITE_UPGRADE_SMITHING_TEMPLATE
        )

        registerBallLootPoolUniform(
            output,
            CHERISH_BALL,
            1.0f,
            2.0f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.ABILITY_PATCH,
            GenerationsItems.AMULET_COIN,
            CobblemonItems.ANTIDOTE,
            GenerationsItems.BACHS_FOOD_TIN,
            GenerationsItems.BEACH_GLASS,
            CobblemonItems.BERRY_JUICE,
            CobblemonItems.BERRY_SWEET,
            GenerationsItems.BLACK_FLUTE,
            GenerationsItems.BOILED_EGG,
            GenerationsItems.BREAD,
            CobblemonItems.CALCIUM,
            CHERISH_BALL,
            CobblemonItems.CHIPPED_POT,
            CobblemonItems.DARK_GEM,
            GenerationsItems.DISCOUNT_COUPON,
            CobblemonItems.ELECTIRIZER,
            CobblemonItems.ELECTRIC_GEM,
            CobblemonItems.EVERSTONE,
            CobblemonItems.EXPERIENCE_CANDY_M,
            CobblemonItems.FIRE_GEM,
            CobblemonItems.FLAME_ORB,
            CobblemonItems.FLOWER_SWEET,
            GenerationsItems.FRIED_FOOD,
            CobblemonItems.FRIEND_BALL,
            GenerationsItems.FRUIT_BUNCH,
            GenerationsItems.GALARICA_TWIG,
            CobblemonItems.GALARICA_WREATH,
            GenerationsItems.HEART_SCALE,
            CobblemonItems.HONDEW_BERRY,
            GenerationsItems.HONEY,
            CobblemonItems.HP_UP,
            CobblemonItems.ICE_GEM,
            CobblemonItems.JABOCA_BERRY,
            GenerationsItems.LAX_INCENSE,
            CobblemonItems.LIGHT_BALL,
            CobblemonItems.LOVE_BALL,
            CobblemonItems.LOVE_SWEET,
            CobblemonItems.METRONOME,
            GenerationsItems.MIGHTY_CANDY_L,
            CobblemonItems.MOON_BALL,
            CobblemonItems.PECHA_BERRY,
            CobblemonItems.PERSIM_BERRY,
            GenerationsItems.PINK_SCARF,
            CobblemonItems.POKE_BALL,
            CobblemonItems.POTION,
            CobblemonItems.POWER_BELT,
            GenerationsItems.PURE_INCENSE,
            GenerationsItems.RED_FLUTE,
            GenerationsItems.RELIC_SILVER,
            GenerationsItems.RESET_URGE,
            GenerationsItems.ROSE_INCENSE,
            CobblemonItems.SACHET,
            GenerationsItems.SAUSAGES,
            GenerationsItems.SHALOUR_SABLE,
            CobblemonItems.SHARP_BEAK,
            CobblemonItems.SILK_SCARF,
            GenerationsItems.SMALL_BOUQUET,
            GenerationsItems.SMART_CANDY,
            GenerationsItems.SPICE_MIX,
            CobblemonItems.STARF_BERRY,
            CobblemonItems.STICKY_BARB,
            GenerationsItems.STRETCHY_SPRING,
            CobblemonItems.SWEET_APPLE,
            GenerationsItems.SWEET_HEART,
            CobblemonItems.TART_APPLE,
            GenerationsItems.SYRUPY_APPLE,
            CobblemonItems.TOXIC_ORB,
            GenerationsItems.TROPICAL_SHELL,
            GenerationsItems.WAVE_INCENSE,
            GenerationsItems.X_SPECIAL_ATTACK_6,
            GenerationsItems.ROTOM_CATALOG,
            Items.GOLD_INGOT,
            Items.SADDLE,
            Items.QUARTZ,
            Items.PRISMARINE_SHARD,
            Items.RABBIT_HIDE,
            Items.MUSIC_DISC_CAT,
            GenerationsItems.EXP_CHARM,
            GenerationsItems.ROCKSTAR_COSTUME,
            GenerationsItems.BELLE_COSTUME,
            GenerationsItems.POPSTAR_COSTUME,
            GenerationsItems.PHD_COSTUME,
            GenerationsItems.LIBRE_COSTUME,
            GenerationsItems.RUSTY_IRON_KEY_1,
            GenerationsItems.SHATTERED_ICE_KEY_1,
            GenerationsItems.CRUMBLED_ROCK_KEY_1,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_1,
            GenerationsItems.DISCHARGED_ELEKI_KEY_1,
            GenerationsItems.SHATTERED_RELIC_SONG_1,
            CobblemonItems.SERIOUS_MINT,
            CobblemonItems.LONELY_MINT,
            CobblemonItems.BRAVE_MINT,
            GenerationsItems.DRAGON_MEMORY_DRIVE,
            GenerationsItems.DRACO_PLATE,
            GenerationsItems.ICE_CANDY,
            GenerationsItems.PSYCHIC_CANDY,
            GenerationsItems.TM_10,
            GenerationsItems.TM_34,
            GenerationsItems.TM_46,
            GenerationsItems.TM_52,
            GenerationsItems.TM_69,
            GenerationsItems.TM_124,
            GenerationsItems.TM_135,
            GenerationsItems.TM_143,
            GenerationsItems.TM_4,
            GenerationsItems.TM_16,
            GenerationsItems.TM_41,
            GenerationsItems.TM_54,
            GenerationsItems.TM_59,
            GenerationsItems.TM_63,
            GenerationsItems.TM_74,
            GenerationsItems.TM_75,
            GenerationsItems.TM_85,
            GenerationsItems.TM_92,
            GenerationsItems.TM_98,
            GenerationsItems.TM_109,
            GenerationsItems.TM_120,
            GenerationsItems.TM_128,
            GenerationsItems.TM_129,
            GenerationsItems.TM_138,
            GenerationsItems.TM_161,
            GenerationsItems.TM_201,
            GenerationsItems.TM_227
        )

        //output.accept(BuiltInLootTables.RUINED_PORTAL, LootTable.lootTable().withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))).withPool(CHERISH_BALL));
        registerBallLootPoolUniform(
            output, DIVE_BALL, 1.0f, 2.0f,
            CobblemonItems.POKE_BALL, CobblemonItems.ABSORB_BULB, GenerationsItems.BEACH_GLASS,
            GenerationsItems.BLUE_SHARD, CobblemonItems.DAMP_ROCK, CobblemonItems.DEEP_SEA_SCALE,
            CobblemonItems.DEEP_SEA_TOOTH, CobblemonItems.DIVE_BALL, GenerationsItems.HEALTH_CANDY,
            CobblemonItems.ICE_GEM, CobblemonItems.ICE_HEAL, CobblemonItems.ICE_STONE,
            CobblemonItems.ICY_ROCK, CobblemonItems.LANSAT_BERRY, GenerationsItems.LARGE_LEEK,
            GenerationsItems.LAX_INCENSE, CobblemonItems.LEPPA_BERRY, CobblemonItems.LEVEL_BALL,
            CobblemonItems.LIGHT_CLAY, GenerationsItems.LUCKY_PUNCH, CobblemonItems.LUM_BERRY,
            GenerationsItems.LUMINOUS_MOSS, GenerationsItems.LUMIOSE_GALETTE, GenerationsItems.LURE,
            CobblemonItems.LURE_BALL, CobblemonItems.LUXURY_BALL, CobblemonItems.MAGO_BERRY,
            GenerationsItems.MARBLE, GenerationsItems.MAX_LURE, CobblemonItems.MAX_POTION,
            GenerationsItems.MIGHTY_CANDY_L, CobblemonItems.MOON_STONE, CobblemonItems.MYSTIC_WATER,
            CobblemonItems.NET_BALL, CobblemonItems.PARALYZE_HEAL, GenerationsItems.PASS_ORB,
            CobblemonItems.PASSHO_BERRY, CobblemonItems.PERSIM_BERRY, CobblemonItems.PINAP_BERRY,
            GenerationsItems.POKE_DOLL, CobblemonItems.POTION, CobblemonItems.POWER_BELT,
            CobblemonItems.PRISM_SCALE, GenerationsItems.PUNGENT_ROOT, GenerationsItems.PURE_INCENSE,
            CobblemonItems.RABUTA_BERRY, GenerationsItems.RELIC_GOLD, GenerationsItems.SEA_INCENSE,
            GenerationsItems.SHOAL_SALT, GenerationsItems.SHOAL_SHELL, GenerationsItems.SMOKED_POKE_TAIL,
            CobblemonItems.SMOOTH_ROCK, CobblemonItems.SOFT_SAND, GenerationsItems.SPRINK_LOTAD,
            GenerationsItems.STRETCHY_SPRING, GenerationsItems.SUPER_LURE, CobblemonItems.TANGA_BERRY,
            GenerationsItems.TOUGH_CANDY_XL, GenerationsItems.TROPICAL_SHELL, CobblemonItems.WACAN_BERRY,
            CobblemonItems.WATER_GEM, CobblemonItems.WATMEL_BERRY, GenerationsItems.WAVE_INCENSE,
            CobblemonItems.YACHE_BERRY, Items.SPONGE, Items.PRISMARINE, Items.TURTLE_SCUTE, Items.INK_SAC,
            Items.PRISMARINE_SHARD, Items.PRISMARINE_CRYSTALS, Items.MUSIC_DISC_BLOCKS, GenerationsItems.DYNITE_ORE,
            GenerationsItems.OLD_ROD, GenerationsItems.GOOD_ROD, GenerationsItems.SUPER_ROD,
            GenerationsItems.WAILMER_PAIL, GenerationsItems.LAVA_CRYSTAL, CobblemonItems.ADAMANT_MINT,
            CobblemonItems.NAUGHTY_MINT, CobblemonItems.BOLD_MINT, GenerationsItems.WATER_MEMORY_DRIVE,
            GenerationsItems.SPLASH_PLATE, GenerationsItems.POKEMAIL_AIR, GenerationsItems.POKEMAIL_BLOOM,
            GenerationsItems.POKEMAIL_BRICK, GenerationsItems.POKEMAIL_BRIDGE_D, GenerationsItems.POKEMAIL_BRIDGE_M,
            GenerationsItems.POKEMAIL_BRIDGE_S, GenerationsItems.POKEMAIL_BRIDGE_T, GenerationsItems.POKEMAIL_BRIDGE_V,
            GenerationsItems.WATER_CANDY, GenerationsItems.SHATTERED_ICE_KEY_1, GenerationsItems.SHATTERED_ICE_KEY_2,
            GenerationsItems.SHATTERED_ICE_KEY_3, GenerationsItems.SHATTERED_ICE_KEY_4, GenerationsItems.TM_11,
            GenerationsItems.TM_22, GenerationsItems.TM_50, GenerationsItems.TM_77, GenerationsItems.TM_110,
            GenerationsItems.TM_123, GenerationsItems.TM_142, GenerationsItems.TM_145, GenerationsItems.TM_154,
            GenerationsItems.TM_188, GenerationsItems.TM_196, GenerationsItems.TM_208, GenerationsItems.TM_209
        )

        registerBallLootPoolUniform(
            output,
            DREAM_BALL,
            1.0f,
            2.0f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.AWAKENING,
            CobblemonItems.BIG_ROOT,
            CobblemonItems.CELL_BATTERY,
            GenerationsItems.CHALKY_STONE,
            CobblemonItems.CHESTO_BERRY,
            CobblemonItems.CLOVER_SWEET,
            GenerationsItems.COURAGE_CANDY,
            CobblemonItems.CRACKED_POT,
            CobblemonItems.DRAGON_GEM,
            CobblemonItems.DREAM_BALL,
            CobblemonItems.DUSK_BALL,
            CobblemonItems.EXPERIENCE_CANDY_L,
            CobblemonItems.FAIRY_GEM,
            GenerationsItems.FRESH_CREAM,
            GenerationsItems.FRIED_FOOD,
            CobblemonItems.IAPAPA_BERRY,
            CobblemonItems.KEBIA_BERRY,
            GenerationsItems.LARGE_LEEK,
            GenerationsItems.LEEK,
            GenerationsItems.LEMONADE,
            CobblemonItems.LIGHT_BALL,
            GenerationsItems.LOOKER_TICKET,
            GenerationsItems.MARBLE,
            CobblemonItems.MYSTIC_WATER,
            CobblemonItems.NORMAL_GEM,
            GenerationsItems.ODD_INCENSE,
            GenerationsItems.ODD_KEYSTONE,
            CobblemonItems.PARALYZE_HEAL,
            CobblemonItems.PAYAPA_BERRY,
            CobblemonItems.PERSIM_BERRY,
            CobblemonItems.POISON_GEM,
            GenerationsItems.POLISHED_MUD_BALL,
            CobblemonItems.POWER_LENS,
            CobblemonItems.PSYCHIC_GEM,
            GenerationsItems.RAGE_CANDY_BAR,
            CobblemonItems.RAZOR_CLAW,
            CobblemonItems.RAZOR_FANG,
            CobblemonItems.RED_CARD,
            GenerationsItems.RED_NECTAR,
            GenerationsItems.RED_SCARF,
            GenerationsItems.RED_SHARD,
            GenerationsItems.RELIC_BAND,
            GenerationsItems.ICY_WING,
            CobblemonItems.ROOM_SERVICE,
            CobblemonItems.ROSELI_BERRY,
            CobblemonItems.SCOPE_LENS,
            CobblemonItems.SILK_SCARF,
            CobblemonItems.SITRUS_BERRY,
            GenerationsItems.SMART_CANDY_XL,
            GenerationsItems.SNOWBALL,
            GenerationsItems.SODA_POP,
            GenerationsItems.SOUL_DEW,
            GenerationsItems.STAR_PIECE,
            GenerationsItems.STARDUST,
            CobblemonItems.THROAT_SPRAY,
            CobblemonItems.THUNDER_STONE,
            CobblemonItems.TWISTED_SPOON,
            CobblemonItems.UPGRADE,
            CobblemonItems.WHIPPED_DREAM,
            CobblemonItems.WIDE_LENS,
            CobblemonItems.X_ACCURACY,
            GenerationsItems.X_DEFENSE_6,
            GenerationsItems.X_SPECIAL_ATTACK_2,
            Items.PURPUR_BLOCK,
            Items.SLIME_BALL,
            Items.GHAST_TEAR,
            Items.CRIMSON_FUNGUS,
            Items.MUSIC_DISC_BLOCKS,
            GenerationsItems.MARK_CHARM,
            GenerationsItems.DYNITE_ORE,
            GenerationsItems.RUSTY_IRON_KEY_2,
            GenerationsItems.SHATTERED_ICE_KEY_2,
            GenerationsItems.CRUMBLED_ROCK_KEY_2,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_2,
            GenerationsItems.DISCHARGED_ELEKI_KEY_2,
            GenerationsItems.SHATTERED_RELIC_SONG_2,
            GenerationsItems.LAVA_CRYSTAL,
            CobblemonItems.RELAXED_MINT,
            CobblemonItems.IMPISH_MINT,
            CobblemonItems.GENTLE_MINT,
            GenerationsItems.POKEMAIL_AIR,
            GenerationsItems.POKEMAIL_BLOOM,
            GenerationsItems.POKEMAIL_BRICK,
            GenerationsItems.POKEMAIL_BRIDGE_D,
            GenerationsItems.POKEMAIL_BRIDGE_M,
            GenerationsItems.POKEMAIL_BRIDGE_S,
            GenerationsItems.POKEMAIL_BRIDGE_T,
            GenerationsItems.POKEMAIL_BRIDGE_V,
            GenerationsItems.POKEMAIL_BUBBLE,
            GenerationsItems.POKEMAIL_DREAM,
            GenerationsItems.POKEMAIL_FAB,
            GenerationsItems.POKEMAIL_FAVORED,
            GenerationsItems.FIRE_CANDY,
            GenerationsItems.ICE_CANDY,
            GenerationsItems.PSYCHIC_CANDY,
            GenerationsItems.TM_8,
            GenerationsItems.TM_24,
            GenerationsItems.TM_38,
            GenerationsItems.TM_49,
            GenerationsItems.TM_67,
            GenerationsItems.TM_107,
            GenerationsItems.TM_118,
            GenerationsItems.TM_125,
            GenerationsItems.TM_141,
            GenerationsItems.TM_144,
            GenerationsItems.TM_153,
            GenerationsItems.TM_157,
            GenerationsItems.TM_165,
            GenerationsItems.TM_232,
            GenerationsItems.TM_10,
            GenerationsItems.TM_34,
            GenerationsItems.TM_46,
            GenerationsItems.TM_52,
            GenerationsItems.TM_59,
            GenerationsItems.TM_63,
            GenerationsItems.TM_74,
            GenerationsItems.TM_75,
            GenerationsItems.TM_85,
            GenerationsItems.TM_92,
            GenerationsItems.TM_98,
            GenerationsItems.TM_109,
            GenerationsItems.TM_120,
            GenerationsItems.TM_128,
            GenerationsItems.TM_129,
            GenerationsItems.TM_138,
            GenerationsItems.TM_161,
            GenerationsItems.TM_235,
            GenerationsItems.LUGIA_DISC,
            GenerationsItems.LAVENDER_TOWN_DISC,
            GenerationsItems.MT_PYRE_DISC
        )

        registerBallLootPoolUniform(
            output,
            DUSK_BALL,
            1f,
            2f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.BELUE_BERRY,
            CobblemonItems.BIG_ROOT,
            CobblemonItems.BLACK_GLASSES,
            CobblemonItems.BLACK_SLUDGE,
            GenerationsItems.BRITTLE_BONES,
            CobblemonItems.CLEANSE_TAG,
            CobblemonItems.COLBUR_BERRY,
            CobblemonItems.DARK_GEM,
            CobblemonItems.DUSK_BALL,
            CobblemonItems.DUSK_STONE,
            CobblemonItems.EVIOLITE,
            CobblemonItems.EXPERT_BELT,
            CobblemonItems.GHOST_GEM,
            GenerationsItems.GRISEOUS_ORB,
            CobblemonItems.HEALTH_FEATHER,
            CobblemonItems.HEAT_ROCK,
            CobblemonItems.KASIB_BERRY,
            CobblemonItems.MAX_ETHER,
            GenerationsItems.MIGHTY_CANDY_L,
            GenerationsItems.MIXED_MUSHROOMS,
            CobblemonItems.MOON_STONE,
            CobblemonItems.MYSTIC_WATER,
            CobblemonItems.NEVER_MELT_ICE,
            CobblemonItems.NOMEL_BERRY,
            GenerationsItems.NUGGET,
            CobblemonItems.OCCA_BERRY,
            GenerationsItems.ODD_INCENSE,
            GenerationsItems.PACK_OF_POTATOES,
            GenerationsItems.PEARL,
            CobblemonItems.PECHA_BERRY,
            CobblemonItems.POISON_BARB,
            CobblemonItems.POWER_LENS,
            CobblemonItems.RABUTA_BERRY,
            CobblemonItems.RAZOR_FANG,
            CobblemonItems.REAPER_CLOTH,
            GenerationsItems.RELIC_STATUE,
            CobblemonItems.RING_TARGET,
            CobblemonItems.SAFETY_GOGGLES,
            CobblemonItems.SCOPE_LENS,
            CobblemonItems.SHINY_STONE,
            GenerationsItems.SMART_CANDY_XL,
            GenerationsItems.SNOWBALL,
            CobblemonItems.SPELL_TAG,
            CobblemonItems.STAR_SWEET,
            CobblemonItems.SUN_STONE,
            GenerationsItems.THICK_CLUB,
            CobblemonItems.TOXIC_ORB,
            CobblemonItems.TWISTED_SPOON,
            CobblemonItems.WIDE_LENS,
            CobblemonItems.WISE_GLASSES,
            GenerationsItems.WISHING_PIECE,
            CobblemonItems.X_ACCURACY,
            GenerationsItems.X_ATTACK_3,
            GenerationsItems.X_SPECIAL_ATTACK_2,
            GenerationsItems.X_SPECIAL_DEFENSE_6,
            GenerationsItems.SINISTER_WING,
            GenerationsItems.X_SPEED_2,
            Items.COBWEB,
            Items.END_STONE,
            Items.BONE,
            Items.SPIDER_EYE,
            Items.PHANTOM_MEMBRANE,
            Items.MUSIC_DISC_FAR,
            GenerationsItems.DARK_SOUL,
            GenerationsItems.DRAGON_SOUL,
            CobblemonItems.LAX_MINT,
            CobblemonItems.TIMID_MINT,
            CobblemonItems.HASTY_MINT,
            GenerationsItems.POISON_MEMORY_DRIVE,
            GenerationsItems.GHOST_MEMORY_DRIVE,
            GenerationsItems.TOXIC_PLATE,
            GenerationsItems.SPOOKY_PLATE,
            GenerationsItems.GHOST_CANDY,
            GenerationsItems.DARK_CANDY,
            GenerationsItems.TM_17,
            GenerationsItems.TM_29,
            GenerationsItems.TM_42,
            GenerationsItems.TM_61,
            GenerationsItems.TM_114,
            GenerationsItems.TM_151,
            GenerationsItems.TM_3,
            GenerationsItems.TM_18,
            GenerationsItems.TM_30,
            GenerationsItems.TM_43,
            GenerationsItems.TM_62,
            GenerationsItems.TM_87,
            GenerationsItems.TM_94,
            GenerationsItems.TM_108,
            GenerationsItems.TM_140,
            GenerationsItems.TM_174,
            GenerationsItems.TM_187,
            GenerationsItems.TM_212,
            GenerationsItems.TM_177,
            GenerationsItems.TM_198,
            GenerationsItems.TM_224,
            GenerationsItems.IRIS_DISC,
            GenerationsItems.NESSA_DISC,
            GenerationsItems.TEAM_ROCKET_DISC,
            GenerationsItems.SADA_AND_TURO_DISC,
            GenerationsItems.SOUTH_PROVINCE_DISC,
            GenerationsItems.RIVAL_DISC,
            GenerationsItems.LUSAMINE_DISC,
            GenerationsItems.XY_LEGENDARY_DISC,
            GenerationsItems.KANTO_DISC,
            GenerationsItems.ULTRA_NECROZMA_DISC
        )


        registerBallLootPoolUniform(
            output, FAST_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, GenerationsItems.ABILITY_URGE, CobblemonItems.AGUAV_BERRY,
            CobblemonItems.BELUE_BERRY, CobblemonItems.BLACK_BELT, CobblemonItems.BLUNDER_POLICY,
            CobblemonItems.CARBOS, CobblemonItems.CHESTO_BERRY, CobblemonItems.CHOICE_SCARF,
            CobblemonItems.EJECT_BUTTON, CobblemonItems.ELECTRIC_SEED, GenerationsItems.ESCAPE_ROPE,
            CobblemonItems.EXPERIENCE_CANDY_XS, CobblemonItems.FAST_BALL, CobblemonItems.GROWTH_MULCH,
            GenerationsItems.HEALTH_CANDY, CobblemonItems.IAPAPA_BERRY, CobblemonItems.ICE_GEM,
            GenerationsItems.INSTANT_NOODLES, CobblemonItems.KELPSY_BERRY,
            CobblemonItems.LIECHI_BERRY, GenerationsItems.MACHO_BRACE, CobblemonItems.MAGMARIZER,
            CobblemonItems.MAGNET, CobblemonItems.MIRACLE_SEED, GenerationsItems.MOOMOO_CHEESE,
            CobblemonItems.MOON_BALL, CobblemonItems.MOON_STONE, GenerationsItems.BELLIGERENT_WING,
            CobblemonItems.NEST_BALL, CobblemonItems.NET_BALL, GenerationsItems.PACK_OF_POTATOES,
            CobblemonItems.PAYAPA_BERRY, GenerationsItems.PINK_NECTAR, GenerationsItems.POLISHED_MUD_BALL,
            CobblemonItems.POWER_ANKLET, CobblemonItems.QUALOT_BERRY, CobblemonItems.QUICK_BALL,
            GenerationsItems.QUICK_CANDY_L, CobblemonItems.QUICK_POWDER, GenerationsItems.RELIC_CROWN,
            GenerationsItems.REPEL, GenerationsItems.ROLLER_SKATES, CobblemonItems.SALAC_BERRY,
            GenerationsItems.SNOWBALL, CobblemonItems.TAMATO_BERRY, CobblemonItems.THROAT_SPRAY,
            GenerationsItems.TOUGH_CANDY_L, CobblemonItems.ULTRA_BALL, CobblemonItems.WATMEL_BERRY,
            GenerationsItems.ELECTRIC_CANDY, GenerationsItems.X_ACCURACY_6, CobblemonItems.X_ATTACK,
            GenerationsItems.X_DEFENSE_3, GenerationsItems.FIERY_WING, Items.GLOWSTONE_DUST, Items.NETHER_WART,
            Items.PRISMARINE_SHARD, Items.WARPED_FUNGUS, Items.MUSIC_DISC_FAR, GenerationsItems.RUSTY_IRON_KEY_3,
            GenerationsItems.SHATTERED_ICE_KEY_3, GenerationsItems.CRUMBLED_ROCK_KEY_3,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_3, GenerationsItems.DISCHARGED_ELEKI_KEY_3,
            GenerationsItems.SHATTERED_RELIC_SONG_3, CobblemonItems.EXPERIENCE_CANDY_S,
            GenerationsItems.ICE_MEMORY_DRIVE, GenerationsItems.ICICLE_PLATE, GenerationsItems.POKEMAIL_AIR,
            GenerationsItems.POKEMAIL_BLOOM, GenerationsItems.POKEMAIL_BRICK, GenerationsItems.POKEMAIL_BRIDGE_D,
            GenerationsItems.POKEMAIL_BRIDGE_M, GenerationsItems.POKEMAIL_BRIDGE_S, GenerationsItems.POKEMAIL_BRIDGE_T,
            GenerationsItems.POKEMAIL_BRIDGE_V, GenerationsItems.POKEMAIL_BUBBLE, GenerationsItems.POKEMAIL_DREAM,
            GenerationsItems.POKEMAIL_FAB, GenerationsItems.POKEMAIL_FAVORED, GenerationsItems.POKEMAIL_FLAME,
            GenerationsItems.POKEMAIL_GLITTER, GenerationsItems.POKEMAIL_GRASS, GenerationsItems.POKEMAIL_GREET,
            GenerationsItems.POKEMAIL_HARBOR, GenerationsItems.POKEMAIL_HEART, GenerationsItems.POKEMAIL_INQUIRY,
            GenerationsItems.POKEMAIL_LIKE, GenerationsItems.POKEMAIL_MECH, GenerationsItems.POKEMAIL_MOSAIC,
            GenerationsItems.TM_9, GenerationsItems.TM_23, GenerationsItems.TM_48, GenerationsItems.TM_68,
            GenerationsItems.TM_72, GenerationsItems.TM_82, GenerationsItems.TM_96, GenerationsItems.TM_126,
            GenerationsItems.TM_136, GenerationsItems.TM_147, GenerationsItems.TM_166
        )
    }
}