package generations.gg.generations.core.generationscore.forge.datagen.generators.loot

import com.cobblemon.mod.common.CobblemonItems
import generations.gg.generations.core.generationscore.common.world.item.GenerationsItems
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.FRIEND_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.GIGATON_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.GREAT_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.HEAL_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.HEAVY_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.JET_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.LEADEN_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.LEVEL_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.LOVE_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.LURE_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.LUXURY_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.MASTER_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.MOON_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.NEST_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.NET_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.ORIGIN_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.PARK_BALL
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.registerBallLootPoolConstant
import generations.gg.generations.core.generationscore.forge.datagen.generators.loot.GenerationsChestLoot.Companion.registerBallLootPoolUniform
import net.minecraft.resources.ResourceKey
import net.minecraft.world.item.Items
import net.minecraft.world.level.storage.loot.LootTable
import java.util.function.BiConsumer

object ChestLootDataGenB {
    fun generate(output: BiConsumer<ResourceKey<LootTable>, LootTable.Builder>) {
        registerBallLootPoolUniform(
            output,
            FRIEND_BALL,
            1f,
            2f,
            CobblemonItems.POKE_BALL,
            GenerationsItems.ABILITY_URGE,
            GenerationsItems.ADRENALINE_ORB,
            CobblemonItems.APICOT_BERRY,
            GenerationsItems.BACHS_FOOD_TIN,
            CobblemonItems.BERRY_SWEET,
            GenerationsItems.BIG_MALASADA,
            GenerationsItems.BOBS_FOOD_TIN,
            CobblemonItems.BRIGHT_POWDER,
            CobblemonItems.CALCIUM,
            CobblemonItems.CHOICE_SPECS,
            CobblemonItems.CHOPLE_BERRY,
            CobblemonItems.EJECT_BUTTON,
            CobblemonItems.EJECT_PACK,
            CobblemonItems.ELECTIRIZER,
            GenerationsItems.ENERGY_POWDER,
            CobblemonItems.ENIGMA_BERRY,
            CobblemonItems.EVIOLITE,
            CobblemonItems.EXPERIENCE_CANDY_S,
            CobblemonItems.FIRE_STONE,
            CobblemonItems.FLOWER_SWEET,
            CobblemonItems.FOCUS_SASH,
            GenerationsItems.FRESH_CREAM,
            GenerationsItems.FRIED_FOOD,
            CobblemonItems.FRIEND_BALL,
            GenerationsItems.FULL_INCENSE,
            CobblemonItems.GALARICA_CUFF,
            GenerationsItems.GALARICA_TWIG,
            GenerationsItems.GREEN_SCARF,
            CobblemonItems.GREPA_BERRY,
            CobblemonItems.GROWTH_MULCH,
            CobblemonItems.HEAL_POWDER,
            GenerationsItems.HEALTH_CANDY_XL,
            GenerationsItems.HEART_SCALE,
            GenerationsItems.ROTOM_CATALOG,
            GenerationsItems.LUSTROUS_GLOBE,
            GenerationsItems.GRISEOUS_CORE,
            GenerationsItems.ADAMANT_CRYSTAL,
            CobblemonItems.HONDEW_BERRY,
            GenerationsItems.ITEM_DROP,
            CobblemonItems.KINGS_ROCK,
            CobblemonItems.LANSAT_BERRY,
            CobblemonItems.LEFTOVERS,
            CobblemonItems.LIGHT_BALL,
            CobblemonItems.LUXURY_BALL,
            CobblemonItems.MAX_ELIXIR,
            GenerationsItems.MOOMOO_CHEESE,
            CobblemonItems.OCCA_BERRY,
            CobblemonItems.OVAL_STONE,
            GenerationsItems.PACKAGED_CURRY,
            GenerationsItems.PASTA,
            GenerationsItems.PINK_NECTAR,
            GenerationsItems.POKE_TOY,
            CobblemonItems.POMEG_BERRY,
            CobblemonItems.POWER_WEIGHT,
            GenerationsItems.PRECOOKED_BURGER,
            CobblemonItems.PROTECTIVE_PADS,
            CobblemonItems.QUALOT_BERRY,
            GenerationsItems.QUICK_CANDY_L,
            CobblemonItems.QUICK_POWDER,
            CobblemonItems.RAWST_BERRY,
            CobblemonItems.RAZOR_CLAW,
            GenerationsItems.REPEL,
            CobblemonItems.REVIVAL_HERB,
            CobblemonItems.RING_TARGET,
            CobblemonItems.SACHET,
            GenerationsItems.SAUSAGES,
            CobblemonItems.SHED_SHELL,
            CobblemonItems.SILVER_POWDER,
            CobblemonItems.STAR_SWEET,
            GenerationsItems.STATIC_WING,
            CobblemonItems.TANGA_BERRY,
            CobblemonItems.THROAT_SPRAY,
            GenerationsItems.TIN_OF_BEANS,
            CobblemonItems.TWISTED_SPOON,
            CobblemonItems.WACAN_BERRY,
            CobblemonItems.WEAKNESS_POLICY,
            CobblemonItems.WHIPPED_DREAM,
            CobblemonItems.X_ATTACK,
            GenerationsItems.SHATTERED_RELIC_SONG_1,
            GenerationsItems.SHATTERED_ICE_KEY_2,
            GenerationsItems.SHATTERED_ICE_KEY_3,
            GenerationsItems.SHATTERED_ICE_KEY_4,
            GenerationsItems.CORNERSTONE_MASK,
            Items.PORKCHOP,
            Items.MILK_BUCKET,
            Items.RABBIT_FOOT,
            Items.MUSIC_DISC_STRAD,
            GenerationsItems.BUG_CANDY,
            GenerationsItems.ROCK_CANDY,
            GenerationsItems.PURPLE_JUICE,
            GenerationsItems.BLUE_JUICE,
            GenerationsItems.GREEN_JUICE,
            GenerationsItems.PINK_JUICE,
            GenerationsItems.BASIC_SWEET_POKE_PUFF,
            GenerationsItems.BASIC_MINT_POKE_PUFF,
            GenerationsItems.BASIC_CITRUS_POKE_PUFF,
            GenerationsItems.BASIC_MOCHA_POKE_PUFF,
            GenerationsItems.BASIC_SPICE_POKE_PUFF,
            GenerationsItems.SUN_FLUTE,
            GenerationsItems.MOON_FLUTE,
            GenerationsItems.N_SOLARIZER,
            GenerationsItems.N_LUNARIZER,
            GenerationsItems.MELODY_FLUTE,
            GenerationsItems.TM_15,
            GenerationsItems.TM_21,
            GenerationsItems.TM_60,
            GenerationsItems.TM_95,
            GenerationsItems.TM_105,
            GenerationsItems.TM_131,
            GenerationsItems.TM_162,
            GenerationsItems.TM_36,
            GenerationsItems.TM_51,
            GenerationsItems.TM_76,
            GenerationsItems.TM_86,
            GenerationsItems.TM_101,
            GenerationsItems.TM_116,
            GenerationsItems.TM_105,
            GenerationsItems.DYNITE_ORE,
            GenerationsItems.TM_201,
            GenerationsItems.TM_227,
            GenerationsItems.HI_TECH_EARBUDS
        )

        registerBallLootPoolConstant(
            output, GIGATON_BALL, 1.0f,
            CobblemonItems.POKE_BALL, CobblemonItems.HEAVY_BALL,
            CobblemonItems.HEAVY_DUTY_BOOTS, CobblemonItems.HYPER_POTION,
            CobblemonItems.IRON, CobblemonItems.IRON_BALL,
            GenerationsItems.DRAGON_SOUL, GenerationsItems.METEORITE_SHARD,
            GenerationsItems.LEGEND_PLATE, CobblemonItems.ROCK_GEM,
            CobblemonItems.ROCKY_HELMET, CobblemonItems.SAFETY_GOGGLES,
            GenerationsItems.SPRINK_LOTAD, CobblemonItems.STEEL_GEM,
            CobblemonItems.STICKY_BARB, GenerationsItems.STRANGE_SOUVENIR,
            GenerationsItems.STRETCHY_SPRING, CobblemonItems.TIMER_BALL,
            GenerationsItems.TOUGH_CANDY_XL, CobblemonItems.UPGRADE,
            GenerationsItems.STEEL_CANDY, CobblemonItems.EXPERIENCE_CANDY_XL,
            GenerationsItems.TIN_OF_BEANS, GenerationsItems.SMOKED_POKE_TAIL,
            GenerationsItems.LARGE_LEEK, GenerationsItems.PACK_OF_POTATOES,
            GenerationsItems.BOTTLE_CAP, CobblemonItems.EJECT_BUTTON,
            CobblemonItems.ASSAULT_VEST, CobblemonItems.KINGS_ROCK,
            CobblemonItems.METAL_POWDER, CobblemonItems.METRONOME,
            CobblemonItems.SOOTHE_BELL, CobblemonItems.BABIRI_BERRY,
            GenerationsItems.IRON_PLATE, CobblemonItems.METAL_COAT,
            GenerationsItems.STEEL_MEMORY_DRIVE, CobblemonItems.ENIGMA_BERRY,
            CobblemonItems.SITRUS_BERRY, CobblemonItems.ORAN_BERRY,
            CobblemonItems.FIGY_BERRY, CobblemonItems.ABSORB_BULB,
            CobblemonItems.DAMP_ROCK, GenerationsItems.CRUMBLED_ROCK_KEY_1,
            GenerationsItems.CRUMBLED_ROCK_KEY_2, GenerationsItems.CRUMBLED_ROCK_KEY_3,
            GenerationsItems.CRUMBLED_ROCK_KEY_4, GenerationsItems.LUSTROUS_GLOBE,
            GenerationsItems.GRISEOUS_CORE, GenerationsItems.ADAMANT_CRYSTAL,
            CobblemonItems.EVIOLITE, CobblemonItems.HARD_STONE,
            CobblemonItems.LUCKY_EGG, CobblemonItems.POWER_ANKLET,
            CobblemonItems.POWER_BAND, CobblemonItems.POWER_BELT,
            CobblemonItems.POWER_BRACER, CobblemonItems.POWER_LENS,
            CobblemonItems.POWER_WEIGHT, CobblemonItems.ROCKY_HELMET,
            CobblemonItems.ROOM_SERVICE, CobblemonItems.SOFT_SAND,
            GenerationsItems.THICK_CLUB, CobblemonItems.WIDE_LENS, GenerationsItems.DYNITE_ORE,
            GenerationsItems.Z_INGOT, GenerationsItems.TM_31, GenerationsItems.TM_53,
            GenerationsItems.TM_93, GenerationsItems.TM_43, GenerationsItems.TM_99,
            GenerationsItems.TM_104, GenerationsItems.TM_121, GenerationsItems.TM_170,
            GenerationsItems.TM_180, GenerationsItems.TM_223, GenerationsItems.TM_225,
            GenerationsItems.TM_179, GenerationsItems.TM_220, GenerationsItems.TM_184,
            GenerationsItems.TM_192, GenerationsItems.TM_213, GenerationsItems.TM_229,
            GenerationsItems.CASCARRAFA_CITY_DISC, GenerationsItems.SLUMBERING_WEALD_DISC,
            GenerationsItems.POKEMON_CENTER_DISC, GenerationsItems.AZALEA_TOWN_DISC,
            GenerationsItems.LILLIE_DISC, GenerationsItems.ROUTE_228_DISC,
            GenerationsItems.JUBILIFE_VILLAGE_DISC, GenerationsItems.GOLDENROD_CITY_DISC,
            GenerationsItems.ETERNA_CITY_DISC, GenerationsItems.VERMILION_CITY_DISC, GenerationsItems.MEW_FOSSIL
        )

        registerBallLootPoolUniform(
            output, GREAT_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, GenerationsItems.MIRROR,
            GenerationsItems.BACHS_FOOD_TIN, CobblemonItems.BERRY_JUICE,
            GenerationsItems.BIG_MUSHROOM, GenerationsItems.BIG_NUGGET,
            CobblemonItems.BLACK_GLASSES, GenerationsItems.BLUE_FLUTE,
            GenerationsItems.BREAD, CobblemonItems.BRIGHT_POWDER,
            CobblemonItems.BUG_GEM, GenerationsItems.CHALKY_STONE,
            CobblemonItems.CHERI_BERRY, CobblemonItems.CHILAN_BERRY,
            CobblemonItems.CHOICE_SCARF, CobblemonItems.CLEANSE_TAG,
            GenerationsItems.SINISTER_WING, GenerationsItems.COCONUT_MILK,
            CobblemonItems.DAMP_ROCK, CobblemonItems.DEEP_SEA_SCALE,
            GenerationsItems.DIRE_HIT_2, CobblemonItems.DIVE_BALL,
            CobblemonItems.DRAGON_SCALE, CobblemonItems.DURIN_BERRY,
            CobblemonItems.ETHER, CobblemonItems.EXPERIENCE_CANDY_S,
            GenerationsItems.FANCY_APPLE, CobblemonItems.FIRE_GEM,
            GenerationsItems.FRESH_WATER, CobblemonItems.GANLON_BERRY,
            CobblemonItems.GRASS_GEM, GREAT_BALL,
            CobblemonItems.HEAL_BALL, CobblemonItems.HYPER_POTION,
            GenerationsItems.ITEM_URGE, CobblemonItems.LEAF_STONE,
            GenerationsItems.LUMIOSE_GALETTE, GenerationsItems.MARBLE,
            CobblemonItems.MAX_ETHER, CobblemonItems.MENTAL_HERB,
            CobblemonItems.MICLE_BERRY, GenerationsItems.MIGHTY_CANDY,
            GenerationsItems.MIXED_MUSHROOMS, GenerationsItems.MOOMOO_MILK,
            CobblemonItems.NEST_BALL, GenerationsItems.NUGGET,
            CobblemonItems.ORAN_BERRY, GenerationsItems.PACK_OF_POTATOES,
            CobblemonItems.PARALYZE_HEAL, CobblemonItems.PASSHO_BERRY,
            GenerationsItems.PEARL, CobblemonItems.PETAYA_BERRY,
            CobblemonItems.POWER_LENS, CobblemonItems.PRISM_SCALE,
            GenerationsItems.PUNGENT_ROOT, CobblemonItems.QUICK_BALL,
            GenerationsItems.RAGE_CANDY_BAR, GenerationsItems.RED_NECTAR,
            CobblemonItems.REVIVAL_HERB, CobblemonItems.RINDO_BERRY,
            CobblemonItems.SAFARI_BALL, CobblemonItems.SILK_SCARF,
            GenerationsItems.SMART_CANDY_L, CobblemonItems.STRAWBERRY_SWEET,
            GenerationsItems.TIN_OF_BEANS, CobblemonItems.ULTRA_BALL,
            GenerationsItems.X_SPECIAL_ATTACK_2, CobblemonItems.BLACK_APRICORN,
            CobblemonItems.BLUE_APRICORN, CobblemonItems.GREEN_APRICORN,
            CobblemonItems.PINK_APRICORN, CobblemonItems.RED_APRICORN,
            CobblemonItems.WHITE_APRICORN, CobblemonItems.YELLOW_APRICORN,
            Items.END_STONE, Items.GOLD_INGOT, Items.GHAST_TEAR, Items.BLAZE_POWDER,
            Items.MUSIC_DISC_STRAD, GenerationsItems.CRYSTAL, GenerationsItems.Z_INGOT,
            GenerationsItems.SAPPHIRE, GenerationsItems.SILICON, GenerationsItems.MEW_FOSSIL,
            GenerationsItems.RUSTY_IRON_KEY_1, GenerationsItems.SHATTERED_ICE_KEY_1,
            GenerationsItems.CRUMBLED_ROCK_KEY_1, GenerationsItems.FRAGMENTED_DRAGO_KEY_1,
            GenerationsItems.DISCHARGED_ELEKI_KEY_1, GenerationsItems.SHATTERED_RELIC_SONG_1,
            CobblemonItems.EXPERIENCE_CANDY_M, GenerationsItems.TM_5,
            GenerationsItems.TM_28, GenerationsItems.TM_35, GenerationsItems.TM_55,
            GenerationsItems.TM_84, GenerationsItems.TM_90, GenerationsItems.TM_106,
            GenerationsItems.TM_133, GenerationsItems.TM_149, GenerationsItems.TM_44,
            GenerationsItems.TM_78, GenerationsItems.TM_100, GenerationsItems.TM_115,
            GenerationsItems.TM_156, GenerationsItems.TM_169, GenerationsItems.TM_180,
            GenerationsItems.TM_223, GenerationsItems.TM_225,
            GenerationsItems.CASCARRAFA_CITY_DISC,
            GenerationsItems.SLUMBERING_WEALD_DISC,
            GenerationsItems.POKEMON_CENTER_DISC,
            GenerationsItems.AZALEA_TOWN_DISC,
            GenerationsItems.LILLIE_DISC,
            GenerationsItems.ROUTE_228_DISC,
            GenerationsItems.JUBILIFE_VILLAGE_DISC,
            GenerationsItems.GOLDENROD_CITY_DISC,
            GenerationsItems.ETERNA_CITY_DISC,
            GenerationsItems.VERMILION_CITY_DISC
        )

        registerBallLootPoolUniform(
            output, HEAL_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, CobblemonItems.AGUAV_BERRY,
            CobblemonItems.ANTIDOTE, CobblemonItems.ASPEAR_BERRY,
            CobblemonItems.AWAKENING, CobblemonItems.BERRY_JUICE,
            CobblemonItems.BIG_ROOT, CobblemonItems.BLACK_SLUDGE,
            GenerationsItems.BLUE_SCARF, GenerationsItems.BRITTLE_BONES,
            CobblemonItems.BURN_HEAL, GenerationsItems.CASTELIACONE,
            CobblemonItems.CHERI_BERRY, CobblemonItems.CHESTO_BERRY,
            CobblemonItems.CLEANSE_TAG, GenerationsItems.COCONUT_MILK,
            GenerationsItems.COURAGE_CANDY, CobblemonItems.CUSTAP_BERRY,
            CobblemonItems.DREAM_BALL, CobblemonItems.EJECT_PACK,
            CobblemonItems.ELIXIR, GenerationsItems.ENERGY_POWDER,
            CobblemonItems.ENIGMA_BERRY, CobblemonItems.FIGY_BERRY,
            GenerationsItems.FRESH_WATER, CobblemonItems.FULL_HEAL,
            CobblemonItems.FULL_RESTORE, GREAT_BALL,
            CobblemonItems.GUARD_SPEC, CobblemonItems.HEAL_BALL,
            CobblemonItems.HEAL_POWDER, CobblemonItems.HP_UP,
            CobblemonItems.HYPER_POTION, CobblemonItems.ICE_HEAL,
            CobblemonItems.LANSAT_BERRY, GenerationsItems.LEMONADE,
            CobblemonItems.LEPPA_BERRY, CobblemonItems.LUM_BERRY,
            CobblemonItems.MAGO_BERRY, CobblemonItems.MAX_POTION,
            CobblemonItems.MAX_REVIVE, GenerationsItems.MOOMOO_MILK,
            GenerationsItems.OLD_GATEAU, CobblemonItems.PARALYZE_HEAL,
            CobblemonItems.PINAP_BERRY, GenerationsItems.PURPLE_NECTAR,
            GenerationsItems.RAGE_CANDY_BAR, CobblemonItems.REVIVE,
            CobblemonItems.SALAC_BERRY, GenerationsItems.SHALOUR_SABLE,
            CobblemonItems.SHED_SHELL, GenerationsItems.SODA_POP,
            CobblemonItems.SUPER_POTION, CobblemonItems.TAMATO_BERRY,
            GenerationsItems.POISON_CANDY, GenerationsItems.FAIRY_CANDY,
            GenerationsItems.X_SPECIAL_DEFENSE_2, GenerationsItems.X_SPEED_2,
            Items.MILK_BUCKET, Items.MUSIC_DISC_MELLOHI, Items.TOTEM_OF_UNDYING,
            GenerationsItems.HOOPA_RING, GenerationsItems.GRACIDEA,
            CobblemonItems.EXPERIENCE_CANDY_S, GenerationsItems.TM_13,
            GenerationsItems.TM_26, GenerationsItems.TM_45, GenerationsItems.TM_83,
            GenerationsItems.TM_91, GenerationsItems.TM_102, GenerationsItems.TM_148,
            GenerationsItems.TM_2, GenerationsItems.TM_19, GenerationsItems.TM_37,
            GenerationsItems.TM_79, GenerationsItems.TM_127, GenerationsItems.TM_139,
            GenerationsItems.TM_201, GenerationsItems.TM_227,
            GenerationsItems.CASCARRAFA_CITY_DISC,
            GenerationsItems.SLUMBERING_WEALD_DISC,
            GenerationsItems.POKEMON_CENTER_DISC,
            GenerationsItems.AZALEA_TOWN_DISC,
            GenerationsItems.LILLIE_DISC,
            GenerationsItems.ROUTE_228_DISC,
            GenerationsItems.JUBILIFE_VILLAGE_DISC,
            GenerationsItems.GOLDENROD_CITY_DISC,
            GenerationsItems.ETERNA_CITY_DISC,
            GenerationsItems.VERMILION_CITY_DISC
        )

        registerBallLootPoolConstant(
            output, HEAVY_BALL, 1.0f,
            CobblemonItems.POKE_BALL, GenerationsItems.ADAMANT_ORB,
            CobblemonItems.AIR_BALLOON, CobblemonItems.BABIRI_BERRY,
            GenerationsItems.BIG_PEARL, CobblemonItems.BINDING_BAND,
            CobblemonItems.CHESTO_BERRY, CobblemonItems.CHILAN_BERRY,
            CobblemonItems.CHOICE_BAND, CobblemonItems.COBA_BERRY,
            GenerationsItems.COURAGE_CANDY, GenerationsItems.COURAGE_CANDY_XL,
            GenerationsItems.DIRE_HIT_3, CobblemonItems.DRAGON_FANG,
            CobblemonItems.DUBIOUS_DISC, CobblemonItems.FIGHTING_GEM,
            CobblemonItems.FIGY_BERRY, CobblemonItems.FLOAT_STONE,
            GenerationsItems.FULL_INCENSE, CobblemonItems.GANLON_BERRY,
            GenerationsItems.GREEN_SHARD, CobblemonItems.GROUND_GEM,
            CobblemonItems.HABAN_BERRY, CobblemonItems.HARD_STONE,
            GenerationsItems.HEALTH_CANDY_L, CobblemonItems.HEAVY_BALL,
            CobblemonItems.HEAVY_DUTY_BOOTS, CobblemonItems.HYPER_POTION,
            CobblemonItems.IRON, CobblemonItems.IRON_BALL,
            GenerationsItems.ITEM_DROP, CobblemonItems.KEE_BERRY,
            GenerationsItems.LAGGING_TAIL, GenerationsItems.LAVA_COOKIE,
            CobblemonItems.LIFE_ORB, GenerationsItems.MACHO_BRACE,
            CobblemonItems.MAGMARIZER, CobblemonItems.MARANGA_BERRY,
            CobblemonItems.MAX_ETHER, CobblemonItems.METAL_COAT,
            CobblemonItems.PECHA_BERRY, GenerationsItems.POKE_TOY,
            CobblemonItems.POWER_BAND, CobblemonItems.PROTECTIVE_PADS,
            GenerationsItems.QUICK_CANDY, GenerationsItems.RED_SHARD,
            GenerationsItems.RELIC_COPPER, CobblemonItems.REPEAT_BALL,
            GenerationsItems.ICY_WING, CobblemonItems.ROCK_GEM,
            CobblemonItems.ROCKY_HELMET, CobblemonItems.SAFETY_GOGGLES,
            GenerationsItems.SPRINK_LOTAD, CobblemonItems.STEEL_GEM,
            CobblemonItems.STICKY_BARB, GenerationsItems.STRANGE_SOUVENIR,
            GenerationsItems.STRETCHY_SPRING, CobblemonItems.TIMER_BALL,
            GenerationsItems.TOUGH_CANDY_XL, CobblemonItems.UPGRADE,
            GenerationsItems.X_ATTACK_2, GenerationsItems.X_DEFENSE_6,
            GenerationsItems.X_SPECIAL_DEFENSE_6, Items.IRON_INGOT, Items.GUNPOWDER,
            Items.QUARTZ, Items.MUSIC_DISC_MELLOHI, Items.NETHERITE_SCRAP,
            GenerationsItems.MEWTWO_ARMOR, CobblemonItems.EXPERIENCE_CANDY_L,
            GenerationsItems.ROCK_MEMORY_DRIVE, GenerationsItems.STEEL_MEMORY_DRIVE,
            GenerationsItems.STONE_PLATE, GenerationsItems.IRON_PLATE,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_1, GenerationsItems.FRAGMENTED_DRAGO_KEY_2,
            GenerationsItems.FRAGMENTED_DRAGO_KEY_3, GenerationsItems.FRAGMENTED_DRAGO_KEY_4,
            GenerationsItems.CORNERSTONE_MASK,
            GenerationsItems.ROCK_CANDY, GenerationsItems.STEEL_CANDY, GenerationsItems.MEW_FOSSIL,
            GenerationsItems.TM_36, GenerationsItems.TM_51,
            GenerationsItems.TM_76, GenerationsItems.TM_86,
            GenerationsItems.TM_101, GenerationsItems.TM_116,
            GenerationsItems.TM_150, GenerationsItems.TM_31,
            GenerationsItems.TM_53, GenerationsItems.TM_93,
            GenerationsItems.TM_43, GenerationsItems.TM_99,
            GenerationsItems.TM_104, GenerationsItems.TM_121,
            GenerationsItems.TM_180, GenerationsItems.TM_223,
            GenerationsItems.TM_225, GenerationsItems.Z_INGOT,
            GenerationsItems.TM_176, GenerationsItems.TM_186, GenerationsItems.TM_215
        )

        registerBallLootPoolUniform(
            output, JET_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, CobblemonItems.COBA_BERRY,
            CobblemonItems.FLYING_GEM, GenerationsItems.FLYING_MEMORY_DRIVE,
            CobblemonItems.SHARP_BEAK, CobblemonItems.IRON_BALL,
            GenerationsItems.SKY_PLATE, CobblemonItems.CLEVER_FEATHER,
            CobblemonItems.GENIUS_FEATHER, CobblemonItems.HEALTH_FEATHER,
            CobblemonItems.MUSCLE_FEATHER, GenerationsItems.PRETTY_FEATHER,
            CobblemonItems.RESIST_FEATHER, CobblemonItems.SWIFT_FEATHER,
            CobblemonItems.EJECT_PACK, CobblemonItems.CELL_BATTERY,
            CobblemonItems.EJECT_BUTTON, CobblemonItems.MIRACLE_SEED,
            CobblemonItems.LIGHT_BALL, CobblemonItems.POWER_HERB,
            CobblemonItems.MENTAL_HERB, CobblemonItems.MIRROR_HERB,
            CobblemonItems.WHITE_HERB, CobblemonItems.SILK_SCARF,
            CobblemonItems.MAX_POTION, GenerationsItems.MAX_REPEL,
            CobblemonItems.METAL_POWDER, CobblemonItems.METRONOME,
            CobblemonItems.NANAB_BERRY, CobblemonItems.POMEG_BERRY,
            CobblemonItems.POWER_ANKLET, CobblemonItems.POWER_BAND,
            GenerationsItems.PRECOOKED_BURGER, CobblemonItems.PREMIER_BALL,
            CobblemonItems.PROTECTOR, CobblemonItems.QUICK_BALL,
            CobblemonItems.CHESTO_BERRY, CobblemonItems.CHOICE_SCARF,
            CobblemonItems.TERRAIN_EXTENDER, CobblemonItems.AWAKENING,
            CobblemonItems.ENERGY_ROOT, CobblemonItems.HEAL_POWDER,
            GenerationsItems.COURAGE_CANDY, GenerationsItems.QUICK_CANDY,
            GenerationsItems.LEMONADE, CobblemonItems.PARALYZE_HEAL,
            CobblemonItems.ZINC, GenerationsItems.RELIC_SILVER,
            GenerationsItems.RELIC_COPPER, GenerationsItems.RELIC_GOLD,
            GenerationsItems.ODD_KEYSTONE, GenerationsItems.POKEMAIL_BRIDGE_D,
            GenerationsItems.POKEMAIL_BRIDGE_M, GenerationsItems.POKEMAIL_BRIDGE_S,
            GenerationsItems.POKEMAIL_BRIDGE_T, GenerationsItems.POKEMAIL_BRIDGE_V,
            GenerationsItems.FLYING_CANDY, GenerationsItems.HEALTH_CANDY_XL,
            GenerationsItems.HONEY, GenerationsItems.LEEK, GenerationsItems.ENIGMA_FRAGMENT,
            CobblemonItems.LEFTOVERS, GenerationsItems.LONE_EARRING,
            GenerationsItems.LUSTROUS_ORB, GenerationsItems.BREAD,
            GenerationsItems.PASTA, GenerationsItems.FANCY_APPLE,
            GenerationsItems.SPICE_MIX, GenerationsItems.PACKAGED_CURRY,
            GenerationsItems.X_SPEED_6, CobblemonItems.X_ACCURACY,
            GenerationsItems.X_ATTACK_3, CobblemonItems.EXPERIENCE_CANDY_M,
            CobblemonItems.EXPERIENCE_CANDY_XS, GenerationsItems.ORB,
            GenerationsItems.TM_14, GenerationsItems.TM_27,
            GenerationsItems.TM_40, GenerationsItems.TM_65,
            GenerationsItems.TM_97, GenerationsItems.TM_113,
            GenerationsItems.TM_160, GenerationsItems.TM_164,
            GenerationsItems.TM_197, GenerationsItems.TM_216,
            GenerationsItems.TM_230, GenerationsItems.TM_231,
            GenerationsItems.CASCARRAFA_CITY_DISC,
            GenerationsItems.SLUMBERING_WEALD_DISC,
            GenerationsItems.POKEMON_CENTER_DISC,
            GenerationsItems.AZALEA_TOWN_DISC,
            GenerationsItems.LILLIE_DISC,
            GenerationsItems.ROUTE_228_DISC,
            GenerationsItems.JUBILIFE_VILLAGE_DISC,
            GenerationsItems.GOLDENROD_CITY_DISC,
            GenerationsItems.ETERNA_CITY_DISC,
            GenerationsItems.VERMILION_CITY_DISC
        )

        registerBallLootPoolUniform(
            output, LEADEN_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, GenerationsItems.RUSTY_FRAGMENT,
            GenerationsItems.RUSTY_IRON_KEY_1, GenerationsItems.RUSTY_IRON_KEY_2,
            GenerationsItems.RUSTY_IRON_KEY_3, GenerationsItems.RUSTY_IRON_KEY_4,
            GenerationsItems.MIRROR, GenerationsItems.METEORITE_SHARD,
            CobblemonItems.ROCK_GEM, CobblemonItems.ROCKY_HELMET,
            CobblemonItems.SAFETY_GOGGLES, GenerationsItems.SPRINK_LOTAD,
            CobblemonItems.STEEL_GEM, CobblemonItems.AIR_BALLOON,
            CobblemonItems.BABIRI_BERRY, GenerationsItems.BIG_PEARL,
            CobblemonItems.BINDING_BAND, CobblemonItems.CHESTO_BERRY,
            CobblemonItems.CHILAN_BERRY, CobblemonItems.CHOICE_BAND,
            CobblemonItems.IRON, CobblemonItems.IRON_BALL,
            GenerationsItems.ITEM_DROP, CobblemonItems.KEE_BERRY,
            GenerationsItems.LAGGING_TAIL, GenerationsItems.LAVA_COOKIE,
            CobblemonItems.LIFE_ORB, GenerationsItems.MACHO_BRACE,
            CobblemonItems.MAGMARIZER, CobblemonItems.MARANGA_BERRY,
            CobblemonItems.MAX_ETHER, CobblemonItems.METAL_COAT,
            GenerationsItems.FIRE_CANDY, GenerationsItems.ROCK_CANDY,
            GenerationsItems.STEEL_CANDY, GenerationsItems.BRITTLE_BONES,
            GenerationsItems.SALAD_MIX, GenerationsItems.FRIED_FOOD,
            GenerationsItems.MOOMOO_CHEESE, CobblemonItems.EJECT_PACK,
            CobblemonItems.GANLON_BERRY, CobblemonItems.APICOT_BERRY,
            CobblemonItems.KEE_BERRY, CobblemonItems.MARANGA_BERRY,
            CobblemonItems.FLOAT_STONE, CobblemonItems.FOCUS_BAND,
            CobblemonItems.FOCUS_SASH, GenerationsItems.LAGGING_TAIL,
            GenerationsItems.GRIP_CLAW, CobblemonItems.DEEP_SEA_TOOTH,
            CobblemonItems.METRONOME, CobblemonItems.RING_TARGET,
            CobblemonItems.SHED_SHELL, CobblemonItems.SHELL_BELL,
            GenerationsItems.ROCK_INCENSE, GenerationsItems.PURE_INCENSE,
            CobblemonItems.WEAKNESS_POLICY, CobblemonItems.ZOOM_LENS,
            GenerationsItems.CRYSTAL, GenerationsItems.RUBY,
            GenerationsItems.SAPPHIRE, GenerationsItems.SILICON,
            CobblemonItems.EXPERIENCE_CANDY_L, GenerationsItems.TM_8,
            GenerationsItems.TM_24, GenerationsItems.TM_38,
            GenerationsItems.TM_49, GenerationsItems.TM_67,
            GenerationsItems.TM_107, GenerationsItems.TM_118,
            GenerationsItems.TM_125, GenerationsItems.TM_141,
            GenerationsItems.TM_144, GenerationsItems.TM_153,
            GenerationsItems.TM_157, GenerationsItems.TM_165, GenerationsItems.TM_232,
            GenerationsItems.TM_36, GenerationsItems.TM_51,
            GenerationsItems.TM_76, GenerationsItems.TM_86,
            GenerationsItems.TM_101, GenerationsItems.TM_116, GenerationsItems.TM_150,
            GenerationsItems.TM_176, GenerationsItems.TM_186, GenerationsItems.TM_215,
            GenerationsItems.CERULEAN_CITY_DISC,
            GenerationsItems.ICIRRUS_CITY_DISC,
            GenerationsItems.LAVERRE_CITY_DISC,
            GenerationsItems.SURF_DISC,
            GenerationsItems.LAKE_OF_RAGE_DISC,
            GenerationsItems.PENNY_DISC,
            GenerationsItems.NEMONA_DISC,
            GenerationsItems.ZINNIA_DISC,
            GenerationsItems.CYNTHIA_DISC,
            GenerationsItems.DEOXYS_DISC
        )

        registerBallLootPoolUniform(
            output,
            LEVEL_BALL,
            1f,
            2f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.ABSORB_BULB,
            GenerationsItems.AMULET_COIN,
            CobblemonItems.BLACK_BELT,
            GenerationsItems.BLUE_SHARD,
            GenerationsItems.BOBS_FOOD_TIN,
            CobblemonItems.CARBOS,
            CobblemonItems.ELECTIRIZER,
            CobblemonItems.ETHER,
            CobblemonItems.EVERSTONE,
            CobblemonItems.EXPERIENCE_CANDY_XL,
            CobblemonItems.EXP_SHARE,
            CobblemonItems.FIRE_STONE,
            CobblemonItems.GRASS_GEM,
            CobblemonItems.GRASSY_SEED,
            CobblemonItems.HARD_STONE,
            CobblemonItems.HEAT_ROCK,
            CobblemonItems.HEAVY_DUTY_BOOTS,
            CobblemonItems.HONDEW_BERRY,
            CobblemonItems.ICY_ROCK,
            GenerationsItems.INSTANT_NOODLES,
            CobblemonItems.IRON_BALL,
            GenerationsItems.ITEM_URGE,
            CobblemonItems.KELPSY_BERRY,
            GenerationsItems.LAGGING_TAIL,
            CobblemonItems.LANSAT_BERRY,
            GenerationsItems.LARGE_LEEK,
            GenerationsItems.LEAF_LETTER,
            CobblemonItems.LEVEL_BALL,
            CobblemonItems.LUCKY_EGG,
            CobblemonItems.LUM_BERRY,
            CobblemonItems.LURE_BALL,
            CobblemonItems.MAGMARIZER,
            GenerationsItems.MAX_LURE,
            CobblemonItems.METAL_COAT,
            GenerationsItems.MIGHTY_CANDY_XL,
            CobblemonItems.ORAN_BERRY,
            CobblemonItems.OVAL_STONE,
            GenerationsItems.PASTA,
            GenerationsItems.PEARL_STRING,
            CobblemonItems.POWER_BRACER,
            CobblemonItems.PRISM_SCALE,
            CobblemonItems.PROTECTOR,
            CobblemonItems.QUICK_POWDER,
            CobblemonItems.RARE_CANDY,
            CobblemonItems.RAZOR_CLAW,
            CobblemonItems.RAZOR_FANG,
            CobblemonItems.REAPER_CLOTH,
            CobblemonItems.RIBBON_SWEET,
            CobblemonItems.RINDO_BERRY,
            CobblemonItems.ROCK_GEM,
            GenerationsItems.ROCK_INCENSE,
            CobblemonItems.SACHET,
            CobblemonItems.SAFARI_BALL,
            CobblemonItems.SHINY_STONE,
            GenerationsItems.SMALL_BOUQUET,
            GenerationsItems.SMART_CANDY_L,
            CobblemonItems.SOOTHE_BELL,
            CobblemonItems.SPELL_TAG,
            GenerationsItems.SPICE_MIX,
            CobblemonItems.STRAWBERRY_SWEET,
            CobblemonItems.SUN_STONE,
            CobblemonItems.SWEET_APPLE,
            GenerationsItems.STATIC_WING,
            CobblemonItems.TAMATO_BERRY,
            CobblemonItems.TART_APPLE,
            GenerationsItems.SYRUPY_APPLE,
            GenerationsItems.THICK_CLUB,
            CobblemonItems.THUNDER_STONE,
            GenerationsItems.TOUGH_CANDY_XL,
            CobblemonItems.ULTRA_BALL,
            CobblemonItems.UPGRADE,
            CobblemonItems.UTILITY_UMBRELLA,
            CobblemonItems.WATER_GEM,
            CobblemonItems.WATER_STONE,
            CobblemonItems.WHIPPED_DREAM,
            CobblemonItems.ZINC,
            Items.GUNPOWDER,
            Items.PORKCHOP,
            Items.SLIME_BALL,
            Items.WARPED_FUNGUS,
            Items.MUSIC_DISC_WARD,
            GenerationsItems.PURPLE_JUICE,
            GenerationsItems.RED_JUICE,
            GenerationsItems.YELLOW_JUICE,
            GenerationsItems.BLUE_JUICE,
            GenerationsItems.GREEN_JUICE,
            GenerationsItems.PINK_JUICE,
            GenerationsItems.EXP_CHARM,
            CobblemonItems.BERRY_SWEET,
            GenerationsItems.CRUMBLED_ROCK_KEY_1,
            GenerationsItems.CRUMBLED_ROCK_KEY_2,
            GenerationsItems.CRUMBLED_ROCK_KEY_3,
            GenerationsItems.CRUMBLED_ROCK_KEY_4,
            GenerationsItems.ROCKSTAR_COSTUME,
            GenerationsItems.BELLE_COSTUME,
            GenerationsItems.POPSTAR_COSTUME,
            GenerationsItems.PHD_COSTUME,
            GenerationsItems.LIBRE_COSTUME,
            GenerationsItems.ORB,
            GenerationsItems.RAINBOW_WING,
            CobblemonItems.EXPERIENCE_CANDY_XS,
            CobblemonItems.EXPERIENCE_CANDY_S,
            CobblemonItems.EXPERIENCE_CANDY_M,
            CobblemonItems.EXPERIENCE_CANDY_L,
            CobblemonItems.EXPERIENCE_CANDY_XL,
            CobblemonItems.QUIET_MINT,
            CobblemonItems.RASH_MINT,
            CobblemonItems.MILD_MINT,
            CobblemonItems.CALM_MINT,
            GenerationsItems.FIGHTING_CANDY,
            GenerationsItems.TM_1,
            GenerationsItems.TM_6,
            GenerationsItems.TM_7,
            GenerationsItems.TM_25,
            GenerationsItems.TM_32,
            GenerationsItems.TM_47,
            GenerationsItems.TM_58,
            GenerationsItems.TM_64,
            GenerationsItems.TM_73,
            GenerationsItems.TM_89,
            GenerationsItems.TM_112,
            GenerationsItems.TM_134,
            GenerationsItems.TM_158,
            GenerationsItems.TM_167,
            GenerationsItems.TM_190,
            GenerationsItems.TM_194,
            GenerationsItems.TM_206,
            GenerationsItems.TM_233,
            GenerationsItems.DYNITE_ORE
        )

        registerBallLootPoolUniform(
            output, LOVE_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, GenerationsItems.ABILITY_URGE, CobblemonItems.AIR_BALLOON,
            CobblemonItems.BINDING_BAND, CobblemonItems.BURN_HEAL, CobblemonItems.CHERI_BERRY,
            CobblemonItems.CHERISH_BALL, CobblemonItems.CLOVER_SWEET, GenerationsItems.COURAGE_CANDY_XL,
            CobblemonItems.DESTINY_KNOT, CobblemonItems.DRAGON_SCALE, CobblemonItems.DUBIOUS_DISC,
            CobblemonItems.EVERSTONE, CobblemonItems.EXPERIENCE_CANDY_XS, GenerationsItems.FANCY_APPLE,
            GenerationsItems.FRESH_WATER, CobblemonItems.GUARD_SPEC, CobblemonItems.HABAN_BERRY,
            GenerationsItems.HEALTH_CANDY_L, GenerationsItems.HONEY, CobblemonItems.HP_UP,
            CobblemonItems.ICE_HEAL, CobblemonItems.ICE_STONE, CobblemonItems.LEPPA_BERRY,
            CobblemonItems.LOVE_BALL, CobblemonItems.LOVE_SWEET, CobblemonItems.MAX_POTION,
            CobblemonItems.OVAL_STONE, GenerationsItems.PEARL_STRING, GenerationsItems.PINK_SCARF,
            GenerationsItems.POKE_DOLL, CobblemonItems.POTION, CobblemonItems.POWER_ANKLET,
            CobblemonItems.POWER_BRACER, GenerationsItems.MIRROR,
            GenerationsItems.QUICK_CANDY, CobblemonItems.RIBBON_SWEET, CobblemonItems.ROWAP_BERRY,
            GenerationsItems.SAUSAGES, CobblemonItems.SITRUS_BERRY, GenerationsItems.SMOKED_POKE_TAIL,
            CobblemonItems.SMOOTH_ROCK, CobblemonItems.STARF_BERRY, GenerationsItems.STRANGE_SOUVENIR,
            CobblemonItems.STRAWBERRY_SWEET, GenerationsItems.TOUGH_CANDY, CobblemonItems.WATER_GEM,
            CobblemonItems.WATER_STONE, CobblemonItems.WATMEL_BERRY, CobblemonItems.WEPEAR_BERRY,
            GenerationsItems.WHITE_FLUTE, CobblemonItems.WHITE_HERB, GenerationsItems.X_DEFENSE_3,
            Items.TURTLE_SCUTE, Items.MUSIC_DISC_WARD, GenerationsItems.PURPLE_JUICE, GenerationsItems.RED_JUICE,
            GenerationsItems.YELLOW_JUICE, GenerationsItems.BLUE_JUICE, GenerationsItems.GREEN_JUICE,
            GenerationsItems.PINK_JUICE, GenerationsItems.SUN_FLUTE, GenerationsItems.MOON_FLUTE,
            GenerationsItems.N_SOLARIZER, GenerationsItems.N_LUNARIZER, GenerationsItems.MELODY_FLUTE,
            GenerationsItems.LIGHT_SOUL, CobblemonItems.EXPERIENCE_CANDY_M, GenerationsItems.POKEMAIL_BUBBLE,
            GenerationsItems.POKEMAIL_DREAM, GenerationsItems.POKEMAIL_FAB, GenerationsItems.POKEMAIL_FAVORED,
            GenerationsItems.POKEMAIL_FLAME, GenerationsItems.POKEMAIL_GLITTER, GenerationsItems.POKEMAIL_GRASS,
            GenerationsItems.POKEMAIL_GREET, GenerationsItems.POKEMAIL_HARBOR, GenerationsItems.POKEMAIL_HEART,
            GenerationsItems.POKEMAIL_INQUIRY, GenerationsItems.POKEMAIL_LIKE, GenerationsItems.POKEMAIL_MECH,
            GenerationsItems.POKEMAIL_MOSAIC, GenerationsItems.FAIRY_CANDY, GenerationsItems.TM_2,
            GenerationsItems.TM_19, GenerationsItems.TM_37, GenerationsItems.TM_79,
            GenerationsItems.TM_127, GenerationsItems.TM_139, GenerationsItems.TM_178,
            GenerationsItems.TM_217, GenerationsItems.TM_218, GenerationsItems.TM_228, GenerationsItems.TM_235,
            GenerationsItems.TM_174, GenerationsItems.TM_187, GenerationsItems.TM_212,
            GenerationsItems.TM_177, GenerationsItems.TM_198, GenerationsItems.TM_224,
            GenerationsItems.CERULEAN_CITY_DISC,
            GenerationsItems.ICIRRUS_CITY_DISC,
            GenerationsItems.LAVERRE_CITY_DISC,
            GenerationsItems.SURF_DISC,
            GenerationsItems.LAKE_OF_RAGE_DISC,
            GenerationsItems.PENNY_DISC,
            GenerationsItems.NEMONA_DISC,
            GenerationsItems.ZINNIA_DISC,
            GenerationsItems.CYNTHIA_DISC,
            GenerationsItems.DEOXYS_DISC
        )

        registerBallLootPoolUniform(
            output, LURE_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, GenerationsItems.ADRENALINE_ORB, CobblemonItems.BABIRI_BERRY,
            CobblemonItems.BIG_ROOT, GenerationsItems.BLUE_SHARD, CobblemonItems.BLUK_BERRY,
            GenerationsItems.BOBS_FOOD_TIN, CobblemonItems.CHARCOAL, CobblemonItems.CHARTI_BERRY,
            CobblemonItems.CLEANSE_TAG, CobblemonItems.COBA_BERRY, CobblemonItems.EXPERIENCE_CANDY_XS,
            GenerationsItems.GREEN_SHARD, CobblemonItems.GROWTH_MULCH, CobblemonItems.HEAT_ROCK,
            GenerationsItems.HONEY, CobblemonItems.ICE_HEAL, CobblemonItems.JABOCA_BERRY,
            CobblemonItems.KASIB_BERRY, CobblemonItems.KEBIA_BERRY, GenerationsItems.LAGGING_TAIL,
            GenerationsItems.LAX_INCENSE, GenerationsItems.LEAF_LETTER, GenerationsItems.LEMONADE,
            GenerationsItems.LONE_EARRING, GenerationsItems.LUCK_INCENSE, GenerationsItems.LUCKY_PUNCH,
            GenerationsItems.LURE, CobblemonItems.LURE_BALL, CobblemonItems.MAGO_BERRY,
            GenerationsItems.MAX_LURE, GenerationsItems.MAX_REPEL, CobblemonItems.METAL_POWDER,
            GenerationsItems.OLD_GATEAU, CobblemonItems.PAMTRE_BERRY, GenerationsItems.PASS_ORB,
            GenerationsItems.PASTA, CobblemonItems.PINAP_BERRY, GenerationsItems.POKE_DOLL,
            GenerationsItems.POKE_TOY, CobblemonItems.POWER_HERB, GenerationsItems.POWER_PLANT_PASS,
            GenerationsItems.PURE_INCENSE, GenerationsItems.PURPLE_NECTAR, CobblemonItems.RAWST_BERRY,
            CobblemonItems.RED_CARD, GenerationsItems.REPEL, GenerationsItems.ROCK_INCENSE,
            CobblemonItems.ROCKY_HELMET, GenerationsItems.ROSE_INCENSE, CobblemonItems.ROWAP_BERRY,
            GenerationsItems.SALAD_MIX, GenerationsItems.SEA_INCENSE, CobblemonItems.SMOKE_BALL,
            CobblemonItems.SPELON_BERRY, GenerationsItems.SPRINK_LOTAD, CobblemonItems.STARF_BERRY,
            GenerationsItems.SUPER_LURE, GenerationsItems.SUPER_REPEL, GenerationsItems.SWEET_HEART,
            GenerationsItems.TINY_MUSHROOM, GenerationsItems.TOUGH_CANDY_L, CobblemonItems.WACAN_BERRY,
            GenerationsItems.WAVE_INCENSE, GenerationsItems.X_ACCURACY_3, GenerationsItems.X_SPEED_2,
            Items.PRISMARINE, Items.FEATHER, Items.BONE, Items.GHAST_TEAR, GenerationsItems.Z_INGOT,
            Items.PRISMARINE_CRYSTALS, Items.MUSIC_DISC_CHIRP, GenerationsItems.MARK_CHARM,
            GenerationsItems.FILM, GenerationsItems.CAMERA, GenerationsItems.WAILMER_PAIL,
            GenerationsItems.RUSTY_IRON_KEY_1, GenerationsItems.RUSTY_IRON_KEY_2,
            GenerationsItems.RUSTY_IRON_KEY_3, GenerationsItems.RUSTY_IRON_KEY_4,
            CobblemonItems.EXPERIENCE_CANDY_S, GenerationsItems.GRASS_CANDY, GenerationsItems.TM_20,
            GenerationsItems.TM_33, GenerationsItems.TM_56, GenerationsItems.TM_71,
            GenerationsItems.TM_81, GenerationsItems.TM_111, GenerationsItems.TM_119,
            GenerationsItems.TM_137, GenerationsItems.TM_146, GenerationsItems.TM_155,
            GenerationsItems.TM_159, GenerationsItems.TM_168, GenerationsItems.TM_5,
            GenerationsItems.TM_28, GenerationsItems.TM_35, GenerationsItems.TM_55,
            GenerationsItems.TM_84, GenerationsItems.TM_90, GenerationsItems.TM_106,
            GenerationsItems.TM_133, GenerationsItems.TM_149
        )

        registerBallLootPoolUniform(
            output,
            LUXURY_BALL,
            1f,
            2f,
            CobblemonItems.POKE_BALL,
            CobblemonItems.ABILITY_CAPSULE,
            GenerationsItems.AMULET_COIN,
            CobblemonItems.BELUE_BERRY,
            GenerationsItems.BIG_NUGGET,
            GenerationsItems.BLACK_FLUTE,
            GenerationsItems.BLUE_SCARF,
            CobblemonItems.BLUK_BERRY,
            GenerationsItems.COCONUT_MILK,
            GenerationsItems.COURAGE_CANDY_L,
            CobblemonItems.CRACKED_POT,
            CobblemonItems.DAWN_STONE,
            CobblemonItems.DEEP_SEA_TOOTH,
            CobblemonItems.DRAGON_FANG,
            CobblemonItems.DUSK_STONE,
            GenerationsItems.ELEVATOR_KEY,
            CobblemonItems.EXPERIENCE_CANDY_M,
            CobblemonItems.EXP_SHARE,
            GenerationsItems.FESTIVAL_TICKET,
            CobblemonItems.FLOWER_SWEET,
            CobblemonItems.FULL_HEAL,
            GenerationsItems.FIERY_WING,
            CobblemonItems.GREAT_BALL,
            GenerationsItems.GREEN_SCARF,
            CobblemonItems.GREPA_BERRY,
            GenerationsItems.HEALTH_CANDY_L,
            CobblemonItems.ICE_HEAL,
            CobblemonItems.ICE_STONE,
            CobblemonItems.LOVE_SWEET,
            GenerationsItems.LUCK_INCENSE,
            CobblemonItems.LUCKY_EGG,
            GenerationsItems.LUMIOSE_GALETTE,
            GenerationsItems.LURE,
            CobblemonItems.LUXURY_BALL,
            GenerationsItems.MARBLE,
            GenerationsItems.MAX_LURE,
            GenerationsItems.MIGHTY_CANDY_XL,
            CobblemonItems.NOMEL_BERRY,
            GenerationsItems.ODD_KEYSTONE,
            CobblemonItems.PAMTRE_BERRY,
            GenerationsItems.PEARL,
            GenerationsItems.PERMIT,
            GenerationsItems.PEWTER_CRUNCHIES,
            CobblemonItems.POWER_BAND,
            CobblemonItems.PREMIER_BALL,
            CobblemonItems.PSYCHIC_SEED,
            GenerationsItems.QUICK_CANDY_XL,
            GenerationsItems.RARE_BONE,
            GenerationsItems.RED_FLUTE,
            CobblemonItems.ROOM_SERVICE,
            GenerationsItems.SHOAL_SALT,
            CobblemonItems.SILK_SCARF,
            GenerationsItems.SMART_CANDY_XL,
            CobblemonItems.SOOTHE_BELL,
            GenerationsItems.SWEET_HEART,
            GenerationsItems.TOUGH_CANDY,
            GenerationsItems.TROPICAL_SHELL,
            GenerationsItems.X_DEFENSE_6,
            GenerationsItems.YELLOW_FLUTE,
            Items.QUARTZ_BLOCK,
            Items.DIAMOND,
            Items.LEATHER,
            GenerationsItems.ELEGANT_WING,
            Items.MUSIC_DISC_CHIRP,
            Items.NETHERITE_SCRAP,
            GenerationsItems.CRYSTAL,
            GenerationsItems.SAPPHIRE,
            GenerationsItems.SILICON,
            GenerationsItems.SPARKLING_SHARD,
            CobblemonItems.EXPERIENCE_CANDY_L,
            GenerationsItems.POISON_CANDY,
            GenerationsItems.DRAGON_CANDY,
            GenerationsItems.TM_13,
            GenerationsItems.TM_26,
            GenerationsItems.TM_45,
            GenerationsItems.TM_83,
            GenerationsItems.TM_91,
            GenerationsItems.TM_102,
            GenerationsItems.TM_148,
            GenerationsItems.TM_44,
            GenerationsItems.TM_78,
            GenerationsItems.TM_100,
            GenerationsItems.TM_115,
            GenerationsItems.TM_156,
            GenerationsItems.TM_169,
            GenerationsItems.TM_178,
            GenerationsItems.TM_217,
            GenerationsItems.TM_218,
            GenerationsItems.TM_228,
            GenerationsItems.TM_235,
            GenerationsItems.TM_174,
            GenerationsItems.TM_187,
            GenerationsItems.TM_212,
            GenerationsItems.TM_177,
            GenerationsItems.TM_198,
            GenerationsItems.TM_224,
            GenerationsItems.IRIS_DISC,
            GenerationsItems.NESSA_DISC,
            GenerationsItems.TEAM_ROCKET_DISC,
            GenerationsItems.SADA_AND_TURO_DISC,
            GenerationsItems.SOUTH_PROVINCE_DISC,
            GenerationsItems.RIVAL_DISC,
            GenerationsItems.LUSAMINE_DISC,
            GenerationsItems.XY_LEGENDARY_DISC,
            GenerationsItems.KANTO_DISC,
            GenerationsItems.ULTRA_NECROZMA_DISC
        )

        registerBallLootPoolConstant(
            output, MASTER_BALL, 1f,
            CobblemonItems.POKE_BALL, CobblemonItems.ABILITY_CAPSULE, CobblemonItems.ABILITY_PATCH,
            GenerationsItems.AMULET_COIN, CobblemonItems.ASSAULT_VEST, CobblemonItems.BEAST_BALL,
            GenerationsItems.BLACK_FLUTE, GenerationsItems.BLUE_SHARD, GenerationsItems.BOTTLE_CAP,
            CobblemonItems.BURN_HEAL, CobblemonItems.CHERI_BERRY, CobblemonItems.CHESTO_BERRY,
            CobblemonItems.CHOICE_SCARF, CobblemonItems.CHOPLE_BERRY, GenerationsItems.COURAGE_CANDY_XL,
            CobblemonItems.CRACKED_POT, CobblemonItems.DAMP_ROCK, CobblemonItems.DAWN_STONE,
            GenerationsItems.DIRE_HIT_3, GenerationsItems.DISCOUNT_COUPON, GenerationsItems.DNA_SPLICERS,
            GenerationsItems.DYNAMAX_CANDY, CobblemonItems.ELECTRIC_GEM, GenerationsItems.ELEVATOR_KEY,
            CobblemonItems.EXPERIENCE_CANDY_XL, CobblemonItems.FULL_RESTORE, GenerationsItems.GIGANTAMIX,
            GenerationsItems.GOLD_BOTTLE_CAP, GenerationsItems.GRISEOUS_ORB, GenerationsItems.HEALTH_CANDY,
            CobblemonItems.IRON, CobblemonItems.LEFTOVERS, CobblemonItems.LIFE_ORB,
            CobblemonItems.LUCKY_EGG, GenerationsItems.LUSTROUS_ORB, CobblemonItems.MASTER_BALL,
            GenerationsItems.MAX_HONEY, CobblemonItems.NEVER_MELT_ICE, GenerationsItems.ODD_KEYSTONE,
            CobblemonItems.PARK_BALL, GenerationsItems.PEWTER_CRUNCHIES, CobblemonItems.POISON_BARB,
            CobblemonItems.PP_MAX, CobblemonItems.PSYCHIC_GEM, GenerationsItems.QUICK_CANDY_XL,
            GenerationsItems.RARE_BONE, CobblemonItems.RARE_CANDY, CobblemonItems.RED_CARD,
            GenerationsItems.RELIC_BAND, GenerationsItems.RELIC_CROWN, GenerationsItems.RELIC_STATUE,
            GenerationsItems.RELIC_VASE, CobblemonItems.ROCKY_HELMET, GenerationsItems.SOUL_DEW,
            CobblemonItems.TOXIC_ORB, GenerationsItems.WISHING_PIECE, GenerationsItems.X_ACCURACY_6,
            Items.NETHER_STAR, Items.TRIDENT, Items.NAUTILUS_SHELL, Items.NETHERITE_SCRAP,
            Items.MUSIC_DISC_OTHERSIDE, GenerationsItems.RUSTY_FRAGMENT, GenerationsItems.SCROLL_PAGE,
            GenerationsItems.ORB, GenerationsItems.RAINBOW_WING, GenerationsItems.SINISTER_WING,
            GenerationsItems.FIERY_WING, CobblemonItems.HEALTH_FEATHER, GenerationsItems.BELLIGERENT_WING,
            GenerationsItems.ELEGANT_WING, GenerationsItems.ICY_WING, GenerationsItems.STATIC_WING,
            GenerationsItems.SILVER_WING, GenerationsItems.LAVA_CRYSTAL, CobblemonItems.EXPERIENCE_CANDY_XL,
            GenerationsItems.DRACO_PLATE, GenerationsItems.DREAD_PLATE, GenerationsItems.EARTH_PLATE,
            GenerationsItems.FIST_PLATE, GenerationsItems.FLAME_PLATE, GenerationsItems.ICICLE_PLATE,
            GenerationsItems.INSECT_PLATE, GenerationsItems.IRON_PLATE, GenerationsItems.MEADOW_PLATE,
            GenerationsItems.MIND_PLATE, GenerationsItems.PIXIE_PLATE, GenerationsItems.SKY_PLATE,
            GenerationsItems.SPLASH_PLATE, GenerationsItems.SPOOKY_PLATE, GenerationsItems.STONE_PLATE,
            GenerationsItems.TOXIC_PLATE, GenerationsItems.ZAP_PLATE, GenerationsItems.LEGEND_PLATE,
            GenerationsItems.SPARKLING_SHARD, GenerationsItems.MIRROR, GenerationsItems.DARK_SOUL,
            GenerationsItems.LIGHT_SOUL, GenerationsItems.METEORITE_SHARD, GenerationsItems.MEW_DNA_FIBER,
            GenerationsItems.LUSTROUS_GLOBE, GenerationsItems.GRISEOUS_CORE, GenerationsItems.ADAMANT_CRYSTAL,
            GenerationsItems.HEARTHFLAME_MASK, GenerationsItems.CORNERSTONE_MASK,
            GenerationsItems.CHILL_DRIVE, GenerationsItems.DOUSE_DRIVE,
            GenerationsItems.TM_9, GenerationsItems.TM_23, GenerationsItems.TM_48,
            GenerationsItems.TM_68, GenerationsItems.TM_72, GenerationsItems.TM_82,
            GenerationsItems.TM_96, GenerationsItems.TM_126, GenerationsItems.TM_136,
            GenerationsItems.TM_147, GenerationsItems.TM_166, GenerationsItems.MEW_FOSSIL
        )

        registerBallLootPoolUniform(
            output, MOON_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, CobblemonItems.AIR_BALLOON, GenerationsItems.BEACH_GLASS,
            GenerationsItems.BIG_PEARL, GenerationsItems.BLUE_SCARF, CobblemonItems.BLUK_BERRY,
            CobblemonItems.CALCIUM, CobblemonItems.CARBOS, GenerationsItems.CASTELIACONE,
            GenerationsItems.CHALKY_STONE, CobblemonItems.CHARTI_BERRY, CobblemonItems.COLBUR_BERRY,
            CobblemonItems.DAWN_STONE, CobblemonItems.DUSK_STONE, CobblemonItems.EVERSTONE,
            CobblemonItems.EVIOLITE, CobblemonItems.EXPERIENCE_CANDY_M, CobblemonItems.FAIRY_GEM,
            FRIEND_BALL, GenerationsItems.GALARICA_TWIG, CobblemonItems.GANLON_BERRY,
            CobblemonItems.GHOST_GEM, GenerationsItems.GREEN_SHARD, CobblemonItems.GROUND_GEM,
            HEAVY_BALL, CobblemonItems.HYPER_POTION,
            CobblemonItems.ICY_ROCK, CobblemonItems.IRON, GenerationsItems.ITEM_URGE,
            CobblemonItems.KEBIA_BERRY, CobblemonItems.KINGS_ROCK, CobblemonItems.LEPPA_BERRY,
            CobblemonItems.LIGHT_CLAY, GenerationsItems.LURE, GenerationsItems.LUSTROUS_ORB,
            CobblemonItems.MAGNET, CobblemonItems.MAX_ETHER, CobblemonItems.METAL_COAT,
            CobblemonItems.METAL_POWDER, CobblemonItems.METRONOME, CobblemonItems.MISTY_SEED,
            CobblemonItems.MOON_BALL, CobblemonItems.MOON_STONE, CobblemonItems.NEVER_MELT_ICE,
            CobblemonItems.PAYAPA_BERRY, CobblemonItems.POISON_GEM, CobblemonItems.POWER_WEIGHT,
            CobblemonItems.PROTECTOR, CobblemonItems.PSYCHIC_GEM, GenerationsItems.QUICK_CANDY_L,
            CobblemonItems.REAPER_CLOTH, GenerationsItems.RED_SCARF, GenerationsItems.RED_SHARD,
            GenerationsItems.RELIC_VASE, CobblemonItems.RING_TARGET, CobblemonItems.ROSELI_BERRY,
            CobblemonItems.SHINY_STONE, GenerationsItems.SHOAL_SHELL, CobblemonItems.SITRUS_BERRY,
            GenerationsItems.SMALL_BOUQUET, CobblemonItems.SMOOTH_ROCK, CobblemonItems.SPELL_TAG,
            GenerationsItems.STAR_PIECE, CobblemonItems.STAR_SWEET, GenerationsItems.STARDUST,
            CobblemonItems.STEEL_GEM, CobblemonItems.SUN_STONE, CobblemonItems.THUNDER_STONE,
            GenerationsItems.TOUGH_CANDY_L, CobblemonItems.WATER_STONE, CobblemonItems.WEPEAR_BERRY,
            GenerationsItems.WISHING_PIECE, CobblemonItems.X_SPEED, Items.PURPUR_BLOCK,
            Items.GLOWSTONE_DUST, Items.NETHER_WART, Items.PRISMARINE_CRYSTALS, Items.CRIMSON_FUNGUS,
            Items.MUSIC_DISC_11, GenerationsItems.WISHING_STAR, Items.AMETHYST_SHARD, GenerationsItems.RUBY,
            GenerationsItems.MEWTWO_ARMOR, GenerationsItems.METEORITE_SHARD, GenerationsItems.PSYCHIC_MEMORY_DRIVE,
            GenerationsItems.FAIRY_MEMORY_DRIVE, GenerationsItems.MIND_PLATE, GenerationsItems.PIXIE_PLATE,
            GenerationsItems.PSYCHIC_CANDY, GenerationsItems.FAIRY_CANDY, GenerationsItems.TM_4,
            GenerationsItems.TM_16, GenerationsItems.TM_41, GenerationsItems.TM_54,
            GenerationsItems.TM_59, GenerationsItems.TM_63, GenerationsItems.TM_74,
            GenerationsItems.TM_75, GenerationsItems.TM_85, GenerationsItems.TM_92,
            GenerationsItems.TM_98, GenerationsItems.TM_109, GenerationsItems.TM_120,
            GenerationsItems.TM_128, GenerationsItems.TM_129, GenerationsItems.TM_138,
            GenerationsItems.TM_161, GenerationsItems.TM_2, GenerationsItems.TM_19,
            GenerationsItems.TM_37, GenerationsItems.TM_79, GenerationsItems.TM_127,
            GenerationsItems.TM_139, GenerationsItems.HI_TECH_EARBUDS
        )

        registerBallLootPoolUniform(
            output, NEST_BALL, 1f, 2f,
            CobblemonItems.POKE_BALL, CobblemonItems.BUG_GEM, CobblemonItems.CHOICE_SPECS,
            CobblemonItems.CLEANSE_TAG, CobblemonItems.CLEVER_FEATHER, CobblemonItems.COBA_BERRY,
            GenerationsItems.COURAGE_CANDY_L, GenerationsItems.DIRE_HIT_2, CobblemonItems.EXPERIENCE_CANDY_S,
            GenerationsItems.FLUFFY_TAIL, CobblemonItems.FLYING_GEM, GenerationsItems.FRUIT_BUNCH,
            GenerationsItems.GALARICA_TWIG, CobblemonItems.GENIUS_FEATHER, CobblemonItems.GRASSY_SEED,
            CobblemonItems.GREPA_BERRY, CobblemonItems.HABAN_BERRY, CobblemonItems.HEALTH_FEATHER,
            CobblemonItems.KEBIA_BERRY, CobblemonItems.LEAF_STONE, GenerationsItems.LEEK,
            CobblemonItems.LIECHI_BERRY, CobblemonItems.LUM_BERRY, CobblemonItems.MENTAL_HERB,
            GenerationsItems.MIGHTY_CANDY_XL, GenerationsItems.MIXED_MUSHROOMS, CobblemonItems.MUSCLE_FEATHER,
            CobblemonItems.NANAB_BERRY, CobblemonItems.NEST_BALL, GenerationsItems.PACKAGED_CURRY,
            GenerationsItems.PEARL_STRING, GenerationsItems.PINK_NECTAR, CobblemonItems.POISON_BARB,
            GenerationsItems.POKE_TOY, CobblemonItems.POWER_HERB, GenerationsItems.PRETTY_FEATHER,
            GenerationsItems.PURPLE_NECTAR, CobblemonItems.REPEAT_BALL, CobblemonItems.RESIST_FEATHER,
            GenerationsItems.SALAD_MIX, CobblemonItems.SHARP_BEAK, GenerationsItems.SILVER_LEAF,
            GenerationsItems.SUPER_REPEL, CobblemonItems.SWEET_APPLE, CobblemonItems.SWIFT_FEATHER,
            CobblemonItems.WHITE_HERB, CobblemonItems.WIKI_BERRY, CobblemonItems.X_ACCURACY,
            GenerationsItems.X_ATTACK_2, CobblemonItems.X_DEFENSE, CobblemonItems.X_SP_ATK,
            CobblemonItems.X_SP_DEF, Items.COBWEB, Items.FEATHER, Items.MUSIC_DISC_11,
            GenerationsItems.CRYSTAL, GenerationsItems.SAPPHIRE,
            GenerationsItems.SILICON, GenerationsItems.FLYING_MEMORY_DRIVE, GenerationsItems.SKY_PLATE,
            GenerationsItems.POKEMAIL_ORANGE, GenerationsItems.POKEMAIL_REPLY, GenerationsItems.POKEMAIL_RETRO,
            GenerationsItems.POKEMAIL_RSVP, GenerationsItems.POKEMAIL_SHADOW, GenerationsItems.POKEMAIL_SNOW,
            GenerationsItems.POKEMAIL_SPACE, GenerationsItems.POKEMAIL_STEEL, GenerationsItems.POKEMAIL_THANKS,
            GenerationsItems.POKEMAIL_TROPIC, GenerationsItems.POKEMAIL_TUNNEL, GenerationsItems.POKEMAIL_WAVE,
            GenerationsItems.POKEMAIL_WOOD, GenerationsItems.FLYING_CANDY, GenerationsItems.BUG_CANDY,
            GenerationsItems.TM_14, GenerationsItems.TM_27, GenerationsItems.TM_40,
            GenerationsItems.TM_65, GenerationsItems.TM_97, GenerationsItems.TM_105,
            GenerationsItems.TM_190, GenerationsItems.TM_194, GenerationsItems.TM_206, GenerationsItems.TM_233,
            GenerationsItems.TM_131, GenerationsItems.TM_162,
            GenerationsItems.TM_179, GenerationsItems.TM_220, GenerationsItems.TM_184,
            GenerationsItems.TM_192, GenerationsItems.TM_213, GenerationsItems.TM_229,
            GenerationsItems.CERULEAN_CITY_DISC,
            GenerationsItems.ICIRRUS_CITY_DISC,
            GenerationsItems.LAVERRE_CITY_DISC,
            GenerationsItems.SURF_DISC,
            GenerationsItems.LAKE_OF_RAGE_DISC,
            GenerationsItems.PENNY_DISC,
            GenerationsItems.NEMONA_DISC,
            GenerationsItems.ZINNIA_DISC,
            GenerationsItems.CYNTHIA_DISC,
            GenerationsItems.DEOXYS_DISC
        )

        registerBallLootPoolUniform(
            output, NET_BALL, 1f, 3f,
            CobblemonItems.POKE_BALL, CobblemonItems.ABSORB_BULB, GenerationsItems.BIG_PEARL,
            CobblemonItems.CHILAN_BERRY, CobblemonItems.CHOICE_SPECS, CobblemonItems.CLOVER_SWEET,
            GenerationsItems.COURAGE_CANDY_XL, CobblemonItems.DIRE_HIT, CobblemonItems.DURIN_BERRY,
            CobblemonItems.ELIXIR, CobblemonItems.ENERGY_ROOT, FRIEND_BALL,
            CobblemonItems.GALARICA_CUFF, CobblemonItems.GRASS_GEM, CobblemonItems.KEE_BERRY,
            GenerationsItems.LEAF_LETTER, CobblemonItems.LEAF_STONE, GenerationsItems.LUCK_INCENSE,
            CobblemonItems.LUM_BERRY, LURE_BALL, CobblemonItems.MAGOST_BERRY,
            CobblemonItems.MARANGA_BERRY, CobblemonItems.MAX_ELIXIR, CobblemonItems.MICLE_BERRY,
            CobblemonItems.MIRACLE_SEED, NET_BALL, CobblemonItems.NOMEL_BERRY,
            CobblemonItems.PASSHO_BERRY, CobblemonItems.PETAYA_BERRY, GenerationsItems.PLASMA_CARD,
            GenerationsItems.RED_NECTAR, CobblemonItems.REVIVAL_HERB, CobblemonItems.RINDO_BERRY,
            GenerationsItems.ROSE_INCENSE, GenerationsItems.SEA_INCENSE, GenerationsItems.SHOAL_SHELL,
            CobblemonItems.SILVER_POWDER, CobblemonItems.SPORT_BALL, GenerationsItems.SUPER_LURE,
            CobblemonItems.TANGA_BERRY, CobblemonItems.TART_APPLE, CobblemonItems.WEPEAR_BERRY,
            GenerationsItems.WATER_CANDY, GenerationsItems.BUG_CANDY, GenerationsItems.X_ACCURACY_2,
            GenerationsItems.X_ATTACK_3, CobblemonItems.X_DEFENSE, CobblemonItems.X_SP_ATK,
            CobblemonItems.X_SP_DEF, CobblemonItems.X_SPEED, CobblemonItems.YACHE_BERRY,
            GenerationsItems.YELLOW_FLUTE, CobblemonItems.ZOOM_LENS, Items.STRING,
            Items.SLIME_BALL, Items.RABBIT_HIDE, Items.MUSIC_DISC_13, GenerationsItems.OLD_ROD,
            GenerationsItems.GOOD_ROD, GenerationsItems.SUPER_ROD,
            GenerationsItems.WAILMER_PAIL, CobblemonItems.JOLLY_MINT, CobblemonItems.NAIVE_MINT,
            CobblemonItems.MODEST_MINT, GenerationsItems.GROUND_MEMORY_DRIVE,
            GenerationsItems.BUG_MEMORY_DRIVE, GenerationsItems.EARTH_PLATE, GenerationsItems.INSECT_PLATE,
            GenerationsItems.WELLSPRING_MASK, GenerationsItems.DOUSE_DRIVE,
            GenerationsItems.TM_11, GenerationsItems.TM_22, GenerationsItems.TM_50,
            GenerationsItems.TM_77, GenerationsItems.TM_110, GenerationsItems.TM_123,
            GenerationsItems.TM_142, GenerationsItems.TM_145, GenerationsItems.TM_154,
            GenerationsItems.TM_15, GenerationsItems.TM_21, GenerationsItems.TM_60,
            GenerationsItems.TM_95, GenerationsItems.TM_105, GenerationsItems.TM_131,
            GenerationsItems.TM_162, GenerationsItems.TM_188, GenerationsItems.TM_196,
            GenerationsItems.TM_208, GenerationsItems.TM_209, GenerationsItems.TM_190,
            GenerationsItems.TM_194, GenerationsItems.TM_206, GenerationsItems.TM_233, GenerationsItems.TM_182,
            GenerationsItems.TM_185, GenerationsItems.TM_219,
            GenerationsItems.CASCARRAFA_CITY_DISC,
            GenerationsItems.SLUMBERING_WEALD_DISC,
            GenerationsItems.POKEMON_CENTER_DISC,
            GenerationsItems.AZALEA_TOWN_DISC,
            GenerationsItems.LILLIE_DISC,
            GenerationsItems.ROUTE_228_DISC,
            GenerationsItems.JUBILIFE_VILLAGE_DISC,
            GenerationsItems.GOLDENROD_CITY_DISC,
            GenerationsItems.ETERNA_CITY_DISC,
            GenerationsItems.VERMILION_CITY_DISC
        )

        registerBallLootPoolConstant(
            output, ORIGIN_BALL, 1f,
            CobblemonItems.POKE_BALL, GenerationsItems.SCROLL_PAGE, GenerationsItems.MEW_DNA_FIBER,
            GenerationsItems.LEGEND_PLATE, CobblemonItems.BLACK_APRICORN, CobblemonItems.BLUE_APRICORN,
            CobblemonItems.GREEN_APRICORN, CobblemonItems.PINK_APRICORN, CobblemonItems.RED_APRICORN,
            CobblemonItems.WHITE_APRICORN, CobblemonItems.YELLOW_APRICORN, GenerationsItems.HEALTH_CANDY_XL,
            GenerationsItems.HONEY, GenerationsItems.LEEK, CobblemonItems.LEFTOVERS,
            GenerationsItems.LONE_EARRING, GenerationsItems.LUSTROUS_ORB, GenerationsItems.GRISEOUS_ORB,
            GenerationsItems.ADAMANT_ORB, GenerationsItems.LUSTROUS_GLOBE, GenerationsItems.GRISEOUS_CORE,
            GenerationsItems.ADAMANT_CRYSTAL, GenerationsItems.GRACIDEA,
            GenerationsItems.RUBY, GenerationsItems.RELIC_BAND, GenerationsItems.RELIC_CROWN,
            GenerationsItems.RELIC_STATUE, GenerationsItems.RELIC_VASE, GenerationsItems.FRUIT_BUNCH,
            GenerationsItems.COCONUT_MILK, GenerationsItems.INSTANT_NOODLES, GenerationsItems.FRESH_CREAM,
            GenerationsItems.EXP_CHARM, CobblemonItems.ANTIDOTE, CobblemonItems.APICOT_BERRY,
            CobblemonItems.ASPEAR_BERRY, CobblemonItems.BABIRI_BERRY, CobblemonItems.BERRY_JUICE,
            CobblemonItems.BURN_HEAL, CobblemonItems.GROWTH_MULCH, CobblemonItems.RICH_MULCH,
            CobblemonItems.SURPRISE_MULCH, CobblemonItems.BERRY_SWEET, CobblemonItems.CLOVER_SWEET,
            CobblemonItems.FLOWER_SWEET, CobblemonItems.LOVE_SWEET, CobblemonItems.RIBBON_SWEET,
            CobblemonItems.STAR_SWEET, CobblemonItems.STRAWBERRY_SWEET, CobblemonItems.DEEP_SEA_SCALE,
            CobblemonItems.DEEP_SEA_TOOTH, CobblemonItems.DRAGON_SCALE, CobblemonItems.DUBIOUS_DISC,
            CobblemonItems.ELECTIRIZER, CobblemonItems.KINGS_ROCK, CobblemonItems.MAGMARIZER,
            CobblemonItems.METAL_COAT, CobblemonItems.OVAL_STONE, CobblemonItems.PRISM_SCALE,
            CobblemonItems.PROTECTOR, CobblemonItems.RAZOR_CLAW, CobblemonItems.RAZOR_FANG,
            CobblemonItems.REAPER_CLOTH, CobblemonItems.SACHET, CobblemonItems.UPGRADE,
            CobblemonItems.WHIPPED_DREAM, CobblemonItems.CHIPPED_POT, CobblemonItems.CRACKED_POT,
            CobblemonItems.GALARICA_CUFF, CobblemonItems.GALARICA_WREATH, CobblemonItems.SWEET_APPLE,
            CobblemonItems.TART_APPLE, GenerationsItems.SYRUPY_APPLE, GenerationsItems.TM_9, GenerationsItems.TM_23,
            GenerationsItems.TM_48, GenerationsItems.TM_68, GenerationsItems.TM_72,
            GenerationsItems.TM_82, GenerationsItems.TM_96, GenerationsItems.TM_126,
            GenerationsItems.TM_136, GenerationsItems.TM_147, GenerationsItems.TM_166,
            GenerationsItems.TM_44, GenerationsItems.TM_78, GenerationsItems.TM_100,
            GenerationsItems.TM_115, GenerationsItems.TM_156, GenerationsItems.TM_169, GenerationsItems.MEW_FOSSIL,
            GenerationsItems.TM_175, GenerationsItems.TM_214, GenerationsItems.TM_200,
            GenerationsItems.TM_222, GenerationsItems.TM_226,
            GenerationsItems.IRIS_DISC,
            GenerationsItems.NESSA_DISC,
            GenerationsItems.TEAM_ROCKET_DISC,
            GenerationsItems.SADA_AND_TURO_DISC,
            GenerationsItems.SOUTH_PROVINCE_DISC,
            GenerationsItems.RIVAL_DISC,
            GenerationsItems.LUSAMINE_DISC,
            GenerationsItems.XY_LEGENDARY_DISC,
            GenerationsItems.KANTO_DISC,
            GenerationsItems.ULTRA_NECROZMA_DISC
        )

        registerBallLootPoolConstant(
            output, PARK_BALL, 1f,
            CobblemonItems.POKE_BALL, CobblemonItems.ABILITY_PATCH, GenerationsItems.ADAMANT_ORB,
            CobblemonItems.AIR_BALLOON, GenerationsItems.BIG_MALASADA, GenerationsItems.BOILED_EGG,
            GenerationsItems.BOTTLE_CAP, CobblemonItems.CHARTI_BERRY, CobblemonItems.CHILAN_BERRY,
            CobblemonItems.CHOICE_BAND, GenerationsItems.COMET_SHARD, CobblemonItems.DESTINY_KNOT,
            GenerationsItems.ELEVATOR_KEY, CobblemonItems.EXPERIENCE_CANDY_XS, CobblemonItems.FIGHTING_GEM,
            GenerationsItems.FLUFFY_TAIL, GenerationsItems.SILVER_WING, GenerationsItems.RAINBOW_WING,
            GenerationsItems.GOLD_BOTTLE_CAP, GenerationsItems.GOLD_LEAF, CobblemonItems.GRASS_GEM,
            GenerationsItems.GREEN_SCARF, GenerationsItems.GRUBBY_HANKY, GenerationsItems.HEALTH_CANDY_XL,
            GenerationsItems.HONEY, GenerationsItems.LEEK, CobblemonItems.LEFTOVERS,
            GenerationsItems.LONE_EARRING, GenerationsItems.LUSTROUS_ORB, CobblemonItems.MASTER_BALL,
            GenerationsItems.MAX_MUSHROOMS, GenerationsItems.ODD_KEYSTONE, CobblemonItems.PARK_BALL,
            CobblemonItems.PP_MAX, GenerationsItems.RARE_BONE, GenerationsItems.RELIC_COPPER,
            GenerationsItems.RELIC_GOLD, GenerationsItems.RELIC_SILVER, CobblemonItems.ROCK_GEM,
            CobblemonItems.SPELON_BERRY, GenerationsItems.TOUGH_CANDY_XL, GenerationsItems.WHITE_FLUTE,
            GenerationsItems.X_ACCURACY_3, CobblemonItems.X_DEFENSE, GenerationsItems.X_SPECIAL_ATTACK_6,
            GenerationsItems.X_SPECIAL_DEFENSE_6, GenerationsItems.X_SPEED_3, GenerationsItems.X_SPEED_6,
            GenerationsItems.YELLOW_FLUTE, Items.DIAMOND, Items.MUSIC_DISC_OTHERSIDE,
            GenerationsItems.RUSTY_IRON_KEY_4, GenerationsItems.SHATTERED_ICE_KEY_4,
            GenerationsItems.CRUMBLED_ROCK_KEY_4, GenerationsItems.FRAGMENTED_DRAGO_KEY_4,
            GenerationsItems.DISCHARGED_ELEKI_KEY_4, GenerationsItems.SHATTERED_RELIC_SONG_4,
            GenerationsItems.SUN_FLUTE, GenerationsItems.MOON_FLUTE, GenerationsItems.N_SOLARIZER,
            GenerationsItems.N_LUNARIZER, GenerationsItems.MELODY_FLUTE, GenerationsItems.HOOPA_RING,
            GenerationsItems.GRACIDEA, GenerationsItems.HEARTHFLAME_MASK, CobblemonItems.SERIOUS_MINT, CobblemonItems.LONELY_MINT,
            CobblemonItems.BRAVE_MINT, CobblemonItems.ADAMANT_MINT, CobblemonItems.NAUGHTY_MINT,
            CobblemonItems.BOLD_MINT, CobblemonItems.RELAXED_MINT, CobblemonItems.IMPISH_MINT,
            CobblemonItems.GENTLE_MINT, CobblemonItems.LAX_MINT, CobblemonItems.TIMID_MINT,
            CobblemonItems.HASTY_MINT, CobblemonItems.JOLLY_MINT, CobblemonItems.NAIVE_MINT,
            CobblemonItems.MODEST_MINT, CobblemonItems.QUIET_MINT, CobblemonItems.RASH_MINT,
            CobblemonItems.MILD_MINT, CobblemonItems.CALM_MINT, CobblemonItems.SASSY_MINT,
            CobblemonItems.CAREFUL_MINT, GenerationsItems.BUG_MEMORY_DRIVE, GenerationsItems.DARK_MEMORY_DRIVE,
            GenerationsItems.DRAGON_MEMORY_DRIVE, GenerationsItems.ELECTRIC_MEMORY_DRIVE,
            GenerationsItems.FAIRY_MEMORY_DRIVE, GenerationsItems.FIGHTING_MEMORY_DRIVE,
            GenerationsItems.FIRE_MEMORY_DRIVE, GenerationsItems.FLYING_MEMORY_DRIVE,
            GenerationsItems.GHOST_MEMORY_DRIVE, GenerationsItems.GRASS_MEMORY_DRIVE,
            GenerationsItems.GROUND_MEMORY_DRIVE, GenerationsItems.ICE_MEMORY_DRIVE,
            GenerationsItems.POISON_MEMORY_DRIVE, GenerationsItems.PSYCHIC_MEMORY_DRIVE,
            GenerationsItems.ROCK_MEMORY_DRIVE, GenerationsItems.STEEL_MEMORY_DRIVE,
            GenerationsItems.WATER_MEMORY_DRIVE, GenerationsItems.TM_8, GenerationsItems.TM_24,
            GenerationsItems.TM_38, GenerationsItems.TM_49, GenerationsItems.TM_67,
            GenerationsItems.TM_107, GenerationsItems.TM_118, GenerationsItems.TM_125,
            GenerationsItems.TM_141, GenerationsItems.TM_144, GenerationsItems.TM_153,
            GenerationsItems.TM_157, GenerationsItems.TM_165, GenerationsItems.TM_232, GenerationsItems.TM_20,
            GenerationsItems.TM_33, GenerationsItems.TM_56, GenerationsItems.TM_71,
            GenerationsItems.TM_81, GenerationsItems.TM_111, GenerationsItems.TM_119,
            GenerationsItems.TM_137, GenerationsItems.TM_146, GenerationsItems.TM_155,
            GenerationsItems.TM_159, GenerationsItems.TM_168,
            GenerationsItems.TM_176, GenerationsItems.TM_186, GenerationsItems.TM_215
        )
    }
}