package generations.gg.generations.core.generationscore.common.datafixer

import com.google.common.util.concurrent.ThreadFactoryBuilder
import com.mojang.datafixers.DSL
import com.mojang.datafixers.DataFixer
import com.mojang.datafixers.DataFixerBuilder
import com.mojang.datafixers.schemas.Schema
import generations.gg.generations.core.generationscore.common.GenerationsCore
import generations.gg.generations.core.generationscore.common.datafixer.fixers.BotariumFix
import generations.gg.generations.core.generationscore.common.datafixer.schema.GenerationsRootSchema
import generations.gg.generations.core.generationscore.common.datafixer.schema.Generationsv1Schema
import generations.gg.generations.core.generationscore.common.generationsResource
import net.minecraft.util.datafix.fixes.ItemStackComponentizationFix
import net.minecraft.util.datafix.fixes.References
import java.util.concurrent.Executors

object GenerationsSchemas {
    const val VERSION_KEY = "${GenerationsCore.MOD_ID}:data_version"

    @JvmStatic val DATA_FIXER: DataFixer get() = RESULT.fixer()

    @JvmStatic val ADDED_TO_1_6_COBBLEMON = buildMap<String, String> {
        put("generations_core:electric_seed", "cobblemon:electric_seed")
        put("generations_core:misty_seed", "cobblemon:misty_seed")
        put("generations_core:grassy_seed", "cobblemon:grassy_seed")
        put("generations_core:psychic_seed", "cobblemon:psychic_seed")
        put("generations_core:metronome", "cobblemon:metronome")
        put("generations_core:protective_pads", "cobblemon:protective_pads")
        put("generations_core:room_service", "cobblemon:room_service")
        put("generations_core:scope_lens", "cobblemon:scope_lens")
        put("generations_core:shed_shell", "cobblemon:shed_shell")
        put("generations_core:terrain_extender", "cobblemon:terrain_extender")
        put("generations_core:throat_spray", "cobblemon:throat_spray")
        put("generations_core:utility_umbrella", "cobblemon:utility_umbrella")
        put("generations_core:wide_lens", "cobblemon:wide_lens")
        put("generations_core:zoom_lens", "cobblemon:zoom_lens")
        put("generations_core:pokedex", "cobblemon:pokedex_red")
    }

    @JvmStatic val TMS_TO_CONVERT_IN_1_8_COBBLEMON = buildMap<String, String> {
        putTM("tm_1", "takedown")
        putTM("tm_2", "charm")
        putTM("tm_3", "faketears")
        putTM("tm_4", "agility")
        putTM("tm_5", "mudslap")
        putTM("tm_6", "scaryface")
        putTM("tm_7", "protect")
        putTM("tm_8", "firefang")
        putTM("tm_9", "thunderfang")
        putTM("tm_10", "icefang")
        putTM("tm_11", "waterpulse")
        putTM("tm_12", "lowkick")
        putTM("tm_13", "acidspray")
        putTM("tm_14", "acrobatics")
        putTM("tm_15", "strugglebug")
        putTM("tm_16", "psybeam")
        putTM("tm_17", "confuseray")
        putTM("tm_18", "thief")
        putTM("tm_19", "disarmingvoice")
        putTM("tm_20", "trailblaze")
        putTM("tm_21", "pounce")
        putTM("tm_22", "chillingwater")
        putTM("tm_23", "chargebeam")
        putTM("tm_24", "firespin")
        putTM("tm_25", "facade")
        putTM("tm_26", "poisontail")
        putTM("tm_27", "aerialace")
        putTM("tm_28", "bulldoze")
        putTM("tm_29", "hex")
        putTM("tm_30", "snarl")
        putTM("tm_31", "metalclaw")
        putTM("tm_32", "swift")
        putTM("tm_33", "magicalleaf")
        putTM("tm_34", "icywind")
        putTM("tm_35", "mudshot")
        putTM("tm_36", "rocktomb")
        putTM("tm_37", "drainingkiss")
        putTM("tm_38", "flamecharge")
        putTM("tm_39", "lowsweep")
        putTM("tm_40", "aircutter")
        putTM("tm_41", "storedpower")
        putTM("tm_42", "nightshade")
        putTM("tm_43", "fling")
        putTM("tm_44", "dragontail")
        putTM("tm_45", "venoshock")
        putTM("tm_46", "avalanche")
        putTM("tm_47", "endure")
        putTM("tm_48", "voltswitch")
        putTM("tm_49", "sunnyday")
        putTM("tm_50", "raindance")
        putTM("tm_51", "sandstorm")
        putTM("tm_52", "snowscape")
        putTM("tm_53", "smartstrike")
        putTM("tm_54", "psyshock")
        putTM("tm_55", "dig")
        putTM("tm_56", "bulletseed")
        putTM("tm_57", "falseswipe")
        putTM("tm_58", "brickbreak")
        putTM("tm_59", "zenheadbutt")
        putTM("tm_60", "uturn")
        putTM("tm_61", "shadowclaw")
        putTM("tm_62", "foulplay")
        putTM("tm_63", "psychicfangs")
        putTM("tm_64", "bulkup")
        putTM("tm_65", "airslash")
        putTM("tm_66", "bodyslam")
        putTM("tm_67", "firepunch")
        putTM("tm_68", "thunderpunch")
        putTM("tm_69", "icepunch")
        putTM("tm_70", "sleeptalk")
        putTM("tm_71", "seedbomb")
        putTM("tm_72", "electroball")
        putTM("tm_73", "drainpunch")
        putTM("tm_74", "reflect")
        putTM("tm_75", "lightscreen")
        putTM("tm_76", "rockblast")
        putTM("tm_77", "waterfall")
        putTM("tm_78", "dragonclaw")
        putTM("tm_79", "dazzlinggleam")
        putTM("tm_80", "metronome")
        putTM("tm_81", "grassknot")
        putTM("tm_82", "thunderwave")
        putTM("tm_83", "poisonjab")
        putTM("tm_84", "stompingtantrum")
        putTM("tm_85", "rest")
        putTM("tm_86", "rockslide")
        putTM("tm_87", "taunt")
        putTM("tm_88", "swordsdance")
        putTM("tm_89", "bodypress")
        putTM("tm_90", "spikes")
        putTM("tm_91", "toxicspikes")
        putTM("tm_92", "imprison")
        putTM("tm_93", "flashcannon")
        putTM("tm_94", "darkpulse")
        putTM("tm_95", "leechlife")
        putTM("tm_96", "eerieimpulse")
        putTM("tm_97", "fly")
        putTM("tm_98", "skillswap")
        putTM("tm_99", "ironhead")
        putTM("tm_100", "dragondance")
        putTM("tm_101", "powergem")
        putTM("tm_102", "gunkshot")
        putTM("tm_103", "substitute")
        putTM("tm_104", "irondefense")
        putTM("tm_105", "xscissor")
        putTM("tm_106", "drillrun")
        putTM("tm_107", "willowisp")
        putTM("tm_108", "crunch")
        putTM("tm_109", "trick")
        putTM("tm_110", "liquidation")
        putTM("tm_111", "gigadrain")
        putTM("tm_112", "aurasphere")
        putTM("tm_113", "tailwind")
        putTM("tm_114", "shadowball")
        putTM("tm_115", "dragonpulse")
        putTM("tm_116", "stealthrock")
        putTM("tm_117", "hypervoice")
        putTM("tm_118", "heatwave")
        putTM("tm_119", "energyball")
        putTM("tm_120", "psychic")
        putTM("tm_121", "heavyslam")
        putTM("tm_122", "encore")
        putTM("tm_123", "surf")
        putTM("tm_124", "icespinner")
        putTM("tm_125", "flamethrower")
        putTM("tm_126", "thunderbolt")
        putTM("tm_127", "playrough")
        putTM("tm_128", "amnesia")
        putTM("tm_129", "calmmind")
        putTM("tm_130", "helpinghand")
        putTM("tm_131", "pollenpuff")
        putTM("tm_132", "batonpass")
        putTM("tm_133", "earthpower")
        putTM("tm_134", "reversal")
        putTM("tm_135", "icebeam")
        putTM("tm_136", "electricterrain")
        putTM("tm_137", "grassyterrain")
        putTM("tm_138", "psychicterrain")
        putTM("tm_139", "mistyterrain")
        putTM("tm_140", "nastyplot")
        putTM("tm_141", "fireblast")
        putTM("tm_142", "hydropump")
        putTM("tm_143", "blizzard")
        putTM("tm_144", "firepledge")
        putTM("tm_145", "waterpledge")
        putTM("tm_146", "grasspledge")
        putTM("tm_147", "wildcharge")
        putTM("tm_148", "sludgebomb")
        putTM("tm_149", "earthquake")
        putTM("tm_150", "stoneedge")
        putTM("tm_151", "phantomforce")
        putTM("tm_152", "gigaimpact")
        putTM("tm_153", "blastburn")
        putTM("tm_154", "hydrocannon")
        putTM("tm_155", "frenzyplant")
        putTM("tm_156", "outrage")
        putTM("tm_157", "overheat")
        putTM("tm_158", "focusblast")
        putTM("tm_159", "leafstorm")
        putTM("tm_160", "hurricane")
        putTM("tm_161", "trickroom")
        putTM("tm_162", "bugbuzz")
        putTM("tm_163", "hyperbeam")
        putTM("tm_164", "bravebird")
        putTM("tm_165", "flareblitz")
        putTM("tm_166", "thunder")
        putTM("tm_167", "closecombat")
        putTM("tm_168", "solarbeam")
        putTM("tm_169", "dracometeor")
        putTM("tm_170", "steelbeam")
        putTM("tm_171", "terablast")
        putTM("tm_172", "roar")
        putTM("tm_173", "charge")
        putTM("tm_174", "haze")
        putTM("tm_175", "toxic")
        putTM("tm_176", "sandtomb")
        putTM("tm_177", "spite")
        putTM("tm_178", "gravity")
        putTM("tm_179", "smackdown")
        putTM("tm_180", "gyroball")
        putTM("tm_181", "knockoff")
        putTM("tm_182", "bugbite")
        putTM("tm_183", "superfang")
        putTM("tm_184", "vacuumwave")
        putTM("tm_185", "lunge")
        putTM("tm_186", "highhorsepower")
        putTM("tm_187", "iciclespear")
        putTM("tm_188", "scald")
        putTM("tm_189", "heatcrash")
        putTM("tm_190", "solarblade")
        putTM("tm_191", "uproar")
        putTM("tm_192", "focuspunch")
        putTM("tm_193", "weatherball")
        putTM("tm_194", "grassyglide")
        putTM("tm_195", "burningjealousy")
        putTM("tm_196", "flipturn")
        putTM("tm_197", "dualwingbeat")
        putTM("tm_198", "poltergeist")
        putTM("tm_199", "lashout")
        putTM("tm_200", "scaleshot")
        putTM("tm_201", "mistyexplosion")
        putTM("tm_202", "painsplit")
        putTM("tm_203", "psychup")
        putTM("tm_204", "doubleedge")
        putTM("tm_205", "endeavor")
        putTM("tm_206", "petalblizzard")
        putTM("tm_207", "temperflare")
        putTM("tm_208", "whirlpool")
        putTM("tm_209", "muddywater")
        putTM("tm_210", "supercellslam")
        putTM("tm_211", "electroweb")
        putTM("tm_212", "tripleaxel")
        putTM("tm_213", "coaching")
        putTM("tm_214", "sludgewave")
        putTM("tm_215", "scorchingsands")
        putTM("tm_216", "featherdance")
        putTM("tm_217", "futuresight")
        putTM("tm_218", "expandingforce")
        putTM("tm_219", "skittersmack")
        putTM("tm_220", "meteorbeam")
        putTM("tm_221", "throatchop")
        putTM("tm_222", "breakingswipe")
        putTM("tm_223", "metalsound")
        putTM("tm_224", "curse")
        putTM("tm_225", "hardpress")
        putTM("tm_226", "dragoncheer")
        putTM("tm_227", "alluringvoice")
        putTM("tm_228", "psychicnoise")
        putTM("tm_229", "upperhand")
        putTM("tm_230", "defog")
        putTM("tm_231", "roost")
        putTM("tm_232", "mysticalfire")
        putTM("tm_233", "powerwhip")
        putTM("tm_234", "workup")
        putTM("tm_235", "allyswitch")
        putTM("tm_236", "triattack")
        putTM("tm_237", "return")
    }

    private fun MutableMap<String, String>.putTM(string: String, move: String) {
        this[string.generationsResource().toString()] = move
    }

    private val SAME: (Int, Schema) -> Schema = ::Schema
    private val RESULT: DataFixerBuilder.Result = this.create()

    const val DATA_VERSION = 1

    private fun create(): DataFixerBuilder.Result {
        val builder = DataFixerBuilder(DATA_VERSION)
        this.appendSchemas(builder)
        val types = hashSetOf<DSL.TypeReference>(
            References.ENTITY)

        val result = builder.build()
        if (types.isEmpty()) {
            return result
        }
        val executor = Executors.newSingleThreadExecutor(
            ThreadFactoryBuilder()
                .setNameFormat("${GenerationsCore.MOD_ID} Datafixer Bootstrap")
                .setDaemon(true)
                .setPriority(1)
                .build()
        )
        result.optimize(types, executor).join()
        return result
    }

    private fun appendSchemas(builder: DataFixerBuilder) {
        builder.addSchema(0, ::GenerationsRootSchema)
        val v1 = builder.addSchema(1, ::Generationsv1Schema)
        builder.addFixer(BotariumFix(v1))
//        builder.addFixer(ItemRenameFix.create(v1, "Remove items from generations added in 1.6 cobblemon") { name ->
//            print("Converted $name to ")
//
//            val newName = ADDED_TO_1_6_COBBLE.getOrDefault(name, name)
//
//            println(newName)
//            return@create newName
//        })
        builder.addFixer(ItemStackComponentizationFix(v1))
    }
}