# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Publish to Maven

on:
  push:
    branches:
      - master

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 20
          cache: gradle

      - name: Store gradle.properties secrets
        env:
          MAVEN_REPO_PROPERTIES: ${{ secrets.REPO_LOGIN }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${MAVEN_REPO_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle build and Publish to Maven
        run: ./gradlew publish publishAllPublicationsToGenerations-RepoRepository
